# Checking output files

In [3]:
from datetime import datetime, timedelta
import calendar
import collections
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
import sys

import glob
import pandas as pd
import xarray as xr
from IPython.display import display, HTML

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)


my_dir = "/g/data/eg3/spr548/projects/"
sys.path.append(os.path.join(my_dir, "nesp_bff")+os.sep)
from nathers import location_details

# import utils
# from utils import locations, model_dict, vars_1hr, vars_day

In [41]:
step = "step3"
show_only_if_flagged = True

#==========================================
root_dir = "/g/data/eg3/nesp_bff/"
# location = "Sydney"
# scenario = "ssp370"
# model = "CESM2"
# time_period = "2041-2060"
vars_to_summarise_step2 = ["tas","huss","sfcWind","psl","rsds","rsdsdir","rsdsdif"]
vars_to_summarise_step3 = ["tas","twbt","huss","psl","wind_speed","wind_dir","clt","rsds","rsdsdir","rsdsdif"]
locations = ["Darwin","Cairns","Brisbane","Longreach","Mildura","Adelaide","Perth","Sydney","Melbourne","Canberra","Hobart"]
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]

input_dir = f"{root_dir}step3_calc_missing_vars/" if step == "step3" else f"{root_dir}step2_qdc_scaling/BARPA-R/"
vars_to_summarise = vars_to_summarise_step3 if step == "step3" else vars_to_summarise_step2

In [42]:
files = glob.glob(f"{input_dir}*.nc")
len(files)

462

In [43]:
# # Old checkds
# qc_rows = []
# errors = []

# for file in sorted(files):
#     base = file.split("/")[-1]
#     parts = base.split("_")

#     loc = parts[0] if len(parts) > 0 else None
#     model_ = parts[2] if len(parts) > 2 else None
#     ssp = parts[3] if len(parts) > 3 else None
#     time_period_ = parts[9] if len(parts) > 9 else None

#     header = f"{loc}: {model_}, {ssp}, {time_period_}"
#     print(f"==================== {header} ====================")

#     try:
#         with xr.open_dataset(file) as da:
#             df = (
#                 da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
#                   [vars_to_summarise]
#                   .to_dataframe()
#             )

#         desc = df.describe()

#         flagged = df.isna().any().any() or (df.nunique(dropna=True) <= 1).any()

#         if (not show_only_if_flagged) or flagged:
#             print("⚠️ Flagged" if flagged else "OK")
#             display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
#             display(desc)
#             display(HTML("</div>"))

#         qc_rows.append({
#             "file": base,
#             "loc": loc,
#             "model": model_,
#             "ssp": ssp,
#             "time_period": time_period_,
#             "n_min": int(desc.loc["count"].min()),
#             "any_nan": bool(df.isna().any().any()),
#             "any_const": bool((df.nunique(dropna=True) <= 1).any()),
#             "rsds_min": float(desc.loc["min", "rsds"]) if "rsds" in desc.columns else None,
#             "rsds_max": float(desc.loc["max", "rsds"]) if "rsds" in desc.columns else None,
#         })

#     except Exception as e:
#         errors.append({
#             "file": base,
#             "loc": loc,
#             "model": model_,
#             "ssp": ssp,
#             "time_period": time_period_,
#             "error": repr(e),
#         })

# qc_df = pd.DataFrame(qc_rows)
# err_df = pd.DataFrame(errors)

# print("\n=== QC summary (all files) ===")
# display(qc_df)

# if not err_df.empty:
#     print("\n=== Errors ===")
#     display(err_df)

In [44]:
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]
RANGES = {
   # temps: keep the K→C heuristic because files might still be in K
   "tas":  {"min": -60, "max":  60, "units": "C_or_K"},
   "twbt": {"min": -60, "max":  60, "units": "C_or_K"},
   # specific humidity (g/kg)
   "huss": {"min": 0.0, "max": 40., "units": "g/kg"},
   # sea level pressure in kPa (typical ~ 90–110 kPa; give generous bounds)
   "psl":  {"min": 80.0, "max": 110.0, "units": "kPa"},
   # wind speed (m/s)
   "wind_speed": {"min": 0.0, "max": 60.0, "units": "m/s"},
   # 16-point direction code (0..16). If you treat 0 as calm, keep it allowed.
   "wind_dir": {"min": 0.0, "max": 16.0, "units": "dir16"},
   # cloud cover in oktas (0..8)
   "clt": {"min": 0.0, "max": 8.0, "units": "oktas"},
   # radiation (W/m²)
   "rsds":    {"min": 0.0, "max": 1300.0, "units": "W/m2"},
   "rsdsdir": {"min": 0.0, "max": 1300.0, "units": "W/m2"},
   "rsdsdif": {"min": 0.0, "max": 1300.0, "units": "W/m2"},
}

def _convert_for_check(var, vmin, vmax):
    rule = RANGES.get(var)
    if rule is None:
        return vmin, vmax, None, None, None
    rmin, rmax = rule["min"], rule["max"]
    note = None
    # Temperature heuristic: if values look like Kelvin, convert to Celsius for checking
    if var in ("tas", "twbt"):
        if np.isfinite(vmax) and vmax > 150:  # likely Kelvin
            vmin = vmin - 273.15
            vmax = vmax - 273.15
            note = "converted K→C (heuristic)"
    return vmin, vmax, rmin, rmax, note

def flag_df(df, desc, vars_to_check):
   reasons = []
   # NaN + constant checks (overall)
   if df[vars_to_check].isna().any().any():
       reasons.append("has NaNs")
   if (df[vars_to_check].nunique(dropna=True) <= 1).any():
       const_vars = list(df[vars_to_check].columns[(df[vars_to_check].nunique(dropna=True) <= 1)])
       reasons.append(f"constant: {const_vars[:5]}" + ("..." if len(const_vars) > 5 else ""))
   # Range checks per variable
   for v in vars_to_check:
       if v not in desc.columns:
           reasons.append(f"missing column: {v}")
           continue
       vmin = desc.loc["min", v]
       vmax = desc.loc["max", v]
       vmin2, vmax2, rmin, rmax, note = _convert_for_check(v, vmin, vmax)
       if rmin is None:
           continue
       out_low = np.isfinite(vmin2) and (vmin2 < rmin)
       out_high = np.isfinite(vmax2) and (vmax2 > rmax)
       if out_low or out_high:
           msg = f"{v} out of range [{rmin}, {rmax}]"
           if out_low:
               msg += f" (min={vmin2:.3g})"
           if out_high:
               msg += f" (max={vmax2:.3g})"
           if note:
               msg += f" [{note}]"
           reasons.append(msg)
   return reasons

qc_rows, errors = [], []
for file in sorted(files):
   base = file.split("/")[-1]
   parts = base.split("_")
   loc = parts[0] if len(parts) > 0 else None
   model_ = parts[2] if len(parts) > 2 else None
   ssp = parts[3] if len(parts) > 3 else None
   time_period_ = parts[9] if len(parts) > 9 else None
   header = f"{loc}: {model_}, {ssp}, {time_period_}"
   print(f"==================== {header} ====================")
   try:
       with xr.open_dataset(file) as da:
           df = (
               da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
                 [vars_to_summarise]
                 .to_dataframe()
           )
       desc = df.describe()
       reasons = flag_df(df, desc, vars_to_summarise)
       flagged = len(reasons) > 0
       if (not show_only_if_flagged) or flagged:
           print("⚠️ Flagged" if flagged else "OK")
           if flagged:
               print("Reasons:", "; ".join(reasons[:6]) + (" ..." if len(reasons) > 6 else ""))
           display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
           display(desc)
           display(HTML("</div>"))
       qc_rows.append({
           "file": base,
           "loc": loc,
           "model": model_,
           "ssp": ssp,
           "time_period": time_period_,
           "flagged": flagged,
           "flag_reason": "; ".join(reasons[:8]) + (" ..." if len(reasons) > 8 else ""),
           "n_min": int(desc.loc["count"].min()),
           "any_nan": bool(df.isna().any().any()),
           "any_const": bool((df.nunique(dropna=True) <= 1).any()),
       })
   except Exception as e:
       errors.append({
           "file": base,
           "loc": loc,
           "model": model_,
           "ssp": ssp,
           "time_period": time_period_,
           "error": repr(e),
       })
qc_df = pd.DataFrame(qc_rows)
err_df = pd.DataFrame(errors)
display(qc_df.sort_values(["flagged", "loc", "model"], ascending=[False, True, True]))
if not err_df.empty:
   display(err_df)

==================== Adelaide: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Adelaide: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Adelaide: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Adelaide: CESM2, ssp126, 2021-2040 ====================
==================== Adelaide: CESM2, ssp126, 2041-2060 ====================
==================== Adelaide: CESM2, ssp126, 2061-2080 ====================
==================== Adelaide: CESM2, ssp370, 2021-2040 ====================
==================== Adelaide: CESM2, ssp370, 2041-2060 ====================
==================== Adelaide: CESM2, ssp370, 2061-2080 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Adelaide: EC-Earth3, ssp126, 2021-2040 ====================
==================== Adelaide: EC-Earth3, ssp126, 2041-2060 ====================
==================== Adelaide: EC-Earth3, ssp126, 2061-2080 ====================
==================== Adelaide: EC-Earth3, ssp370, 2021-2040 ====================
==================== Adelaide: EC-Earth3, ssp370, 2041-2060 ====================
==================== Adelaide: EC-Earth3, ssp370, 2061-2080 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Brisbane: CESM2, ssp126, 2021-2040 ====================
==================== Brisbane: CESM2, ssp126, 2041-2060 ====================
==================== Brisbane: CESM2, ssp126, 2061-2080 ====================
==================== Brisbane: CESM2, ssp370, 2021-2040 ====================
==================== Brisbane: CESM2, ssp370, 2041-2060 ====================
==================== Brisbane: CESM2, ssp370, 2061-2080 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Brisbane: EC-Earth3, ssp126, 2021-2040 ====================
==================== Brisbane: EC-Earth3, ssp126, 2041-2060 ====================
==================== Brisbane: EC-Earth3, ssp126, 2061-2080 ====================
==================== Brisbane: EC-Earth3, ssp370, 2021-2040 ====================
==================== Brisbane: EC-Earth3, ssp370, 2041-2060 ====================
==================== Brisbane: EC-Earth3, ssp370, 2061-2080 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Cairns: ACCESS-CM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.411657      22.155165      15.471016     101.204277       4.286536       6.708042       4.805354     215.706558     224.774323      61.249191
std         3.412515       3.030259       3.333262       0.429621       2.242982       3.400200       2.418833     300.816040     282.856384      79.482162
min         9.387857       6.731903       3.296445      98.392296       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.154748      20.118215      13.040805     100.916870       2.923209       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.565057      22.458327      15.510452     101.232506       4.318677       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.746741      24.538730      18.111002     101.525482       5.660056       8.000000       7.000000     397.382576     465.965485     118.519346
max        40.765678      30.511023      27.007463     102.409813      22.466087      16.000000       8.000000    1470.000000    1092.411133     444.537598

==================== Cairns: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.809458      22.312113      15.553292     101.225014       4.432554       6.708042       4.805354     220.473816     233.914520      60.275497
std         3.597321       3.179941       3.476262       0.441653       2.277860       3.400200       2.418833     303.830566     290.730042      77.356110
min         9.227594       5.889141       2.749305      98.157471       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.508805      20.234712      13.096956     100.933319       3.069167       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.981287      22.662785      15.607604     101.260548       4.499134       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.239904      24.812951      18.326318     101.546516       5.862076       8.000000       7.000000     413.100533     487.058792     118.022793
max        40.455910      31.310020      27.179726     102.490105      20.816994      16.000000       8.000000    1470.000000    1104.624878     420.747681

==================== Cairns: ACCESS-CM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.054218      22.545029      15.778092     101.239326       4.267461       6.708042       4.805354     222.553452     239.094818      58.848625
std         3.571143       3.114716       3.447579       0.429007       2.220711       3.400200       2.418833     305.839142     296.501373      74.981049
min        10.107042       7.353178       3.037901      98.273544       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.782421      20.513542      13.330999     100.964201       2.901956       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.188122      22.924584      15.874635     101.255081       4.315156       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.460873      24.963270      18.459234     101.553474       5.643944       8.000000       7.000000     420.817574     499.415161     116.220791
max        41.172070      31.396511      27.023069     102.446335      19.820929      16.000000       8.000000    1470.000000    1114.916260     386.924713

==================== Cairns: ACCESS-CM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.375978      22.047279      15.358150     101.194511       4.328322       6.708042       4.805354     217.880920     230.192810      60.355125
std         3.524728       3.178611       3.480932       0.452927       2.245940       3.400200       2.418833     302.135284     289.256775      78.525299
min         9.973216       6.554768       2.940912      98.174004       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.066300      19.854732      12.748228     100.884117       3.000471       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.636621      22.350325      15.340223     101.237503       4.363607       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.798011      24.588550      18.116960     101.528175       5.721388       8.000000       7.000000     403.174850     480.861115     116.749304
max        43.686329      30.595339      27.293739     102.507912      25.633329      16.000000       8.000000    1470.000000    1063.996460     483.594147

==================== Cairns: ACCESS-CM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.356771      22.911915      16.178551     101.247169       4.376554       6.708042       4.805354     218.365250     229.916229      60.545952
std         3.418577       3.001582       3.464462       0.477650       2.273371       3.400200       2.418833     301.970856     287.007172      77.779716
min        10.958663       8.555707       3.279784      97.779839       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.017878      20.810412      13.627045     100.934343       3.008891       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.426945      23.104848      16.083969     101.305000       4.396139       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.696423      25.294023      18.895146     101.618792       5.744582       8.000000       7.000000     407.593079     478.387329     118.303732
max        42.060997      31.645397      27.981613     102.529999      25.348179      16.000000       8.000000    1470.000000    1090.083008     430.639832

==================== Cairns: ACCESS-CM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.246206      23.708025      17.012667     101.274635       4.411058       6.708042       4.805354     219.887177     233.706528      59.907433
std         3.470774       3.040458       3.624938       0.459740       2.253382       3.400200       2.418833     302.189789     289.687256      76.494225
min        12.322617       8.757006       3.294558      98.128998       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.902213      21.624674      14.386039     100.959801       3.091651       5.000000       2.000000       0.000000       0.000000       0.000000
50%        27.349944      23.898380      16.890728     101.324696       4.472926       7.000000       5.000000       0.000000       0.000000       0.000000
75%        29.558921      26.109533      19.811808     101.629059       5.753802       8.000000       7.000000     414.095726     486.243134     118.021885
max        43.410213      32.628750      29.197138     102.533897      21.702669      16.000000       8.000000    1470.000000    1103.625610     429.499084

==================== Cairns: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.188574      21.680151      14.903223     101.243210       4.547281       6.708042       4.805354     220.977310     236.021713      59.190468
std         3.631363       3.197163       3.389837       0.434131       2.352771       3.400200       2.418833     305.605072     293.672272      75.902802
min        10.484198       6.993027       2.828542      98.151176       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.866103      19.625770      12.528230     100.958082       3.143698       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.388829      22.041118      14.918219     101.294163       4.632113       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.653366      24.133189      17.472966     101.568207       6.011268       8.000000       7.000000     412.611145     491.686363     115.908712
max        40.657150      30.311153      26.626925     102.474785      19.366634      16.000000       8.000000    1470.000000    1098.455444     377.952515

==================== Cairns: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.554163      22.067652      15.287299     101.245186       4.511071       6.708042       4.805354     219.509048     233.756760      59.414417
std         3.504785       3.086386       3.364331       0.438590       2.328292       3.400200       2.418833     303.475983     290.831024      76.416992
min        11.113390       7.385887       3.022961      98.082954       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.292278      20.025408      12.869685     100.966202       3.088816       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.726188      22.399947      15.314719     101.289352       4.609619       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.916685      24.476006      17.913224     101.576042       5.978566       8.000000       7.000000     409.420723     486.958534     115.800667
max        40.672974      30.943249      26.933884     102.430878      19.946302      16.000000       8.000000    1470.000000    1064.598145     415.118225

==================== Cairns: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.543776      21.955957      15.141209     101.243141       4.545452       6.708042       4.805354     222.298950     239.049957      58.337921
std         3.645860       3.150014       3.391036       0.438741       2.335439       3.400200       2.418833     306.924164     297.331696      74.609970
min         9.584154       6.992883       2.782233      98.082695       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.197798      19.921679      12.771059     100.967106       3.154806       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.739599      22.248226      15.086411     101.287598       4.661838       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.993576      24.421745      17.779664     101.576515       6.006645       8.000000       7.000000     416.481171     496.977600     114.449785
max        42.436802      30.499886      26.148430     102.468391      19.080061      16.000000       8.000000    1470.000000    1122.555298     392.011780

==================== Cairns: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.312654      21.856779      15.116198     101.206841       4.479402       6.708042       4.805354     218.975845     232.643539      59.585491
std         3.645170       3.232189       3.448615       0.451477       2.312768       3.400200       2.418833     303.375397     290.467285      76.721802
min         9.544374       6.790306       3.020612      97.550354       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.995403      19.733068      12.645072     100.915924       3.105923       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.546236      22.219816      15.142866     101.262825       4.543682       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.753868      24.396434      17.824864     101.535416       5.969808       8.000000       7.000000     408.227516     483.988686     116.371943
max        40.867451      30.682777      26.239414     102.480606      21.414095      16.000000       8.000000    1470.000000    1081.176880     421.338318

==================== Cairns: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.86e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.077997      22.254745      15.349863     101.269348       4.472653       6.708042       4.805354     227.136444     248.364014      56.964222
std         3.785061       3.178916       3.468217       0.437581       2.291480       3.400200       2.418833     310.086823     305.034546      71.772324
min        10.627583       7.632553       2.864645      98.052231       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.607161      20.191341      12.919952     100.986404       3.134261       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.197782      22.590826      15.368166     101.314529       4.547250       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.642519      24.702378      17.953889     101.600319       5.902731       8.000000       7.000000     434.696472     517.608032     113.819267
max        45.205021      31.418583      27.136187     102.495987      17.832577      16.000000       8.000000    1470.000000    1855.680664     629.507874

==================== Cairns: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.73e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.650211      22.886679      16.060923     101.256325       4.614151       6.708042       4.805354     222.663361     240.306824      57.936111
std         3.724287       3.273432       3.698459       0.445868       2.353688       3.400200       2.418833     306.306824     297.709381      73.721329
min        10.773428       6.880146       3.179389      98.250565       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.252387      20.797121      13.483297     100.975866       3.197237       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.799503      23.199524      16.035913     101.310452       4.739256       7.000000       5.000000       0.000000       0.000000       0.000000
75%        29.134054      25.440628      18.908676     101.598541       6.111684       8.000000       7.000000     419.855278     498.589142     114.814318
max        42.683727      32.238388      28.792269     102.467415      18.831593      16.000000       8.000000    1470.000000    1727.248169     558.982300

==================== Cairns: CESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.383196      21.974489      15.238090     101.222076       4.469697       6.708042       4.805354     218.536957     237.570984      56.127113
std         3.618085       3.148434       3.360181       0.447915       2.309646       3.400200       2.418833     303.670502     297.007629      72.350166
min         9.817517       6.301236       2.695005      98.221382       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.167197      19.982626      12.850179     100.906416       3.098007       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.545810      22.345206      15.348647     101.270893       4.514607       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.800804      24.411261      17.856384     101.556595       5.969164       8.000000       7.000000     403.139008     494.428299     109.076157
max        40.591881      30.673843      26.733042     102.625969      23.258770      16.000000       8.000000    1470.000000    1225.728149     422.265869

==================== Cairns: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.629520      22.119141      15.378513     101.282646       4.366276       6.708042       4.805354     222.498489     246.492279      53.856483
std         3.879669       3.408808       3.635885       0.421327       2.265199       3.400200       2.418833     307.627197     306.781525      68.559998
min         9.212437       6.945058       2.460359      98.281456       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.274930      19.875437      12.734338     100.982086       3.036081       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.903728      22.671706      15.649978     101.324799       4.435918       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.158590      24.799428      18.260532     101.603273       5.752649       8.000000       7.000000     414.613602     514.075699     106.040190
max        40.906166      30.871672      26.972668     102.576042      23.125046      16.000000       8.000000    1470.000000    1134.941895     357.058746

==================== Cairns: CESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.39e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.747572      22.315489      15.564996     101.307213       4.417026       6.708042       4.805354     221.723557     244.358932      54.565857
std         3.625834       3.159224       3.411853       0.387544       2.256676       3.400200       2.418833     306.354462     303.719238      69.397476
min         9.323558       7.040110       2.730036      98.801826       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.516629      20.258446      13.126163     101.021057       3.069948       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.933057      22.770008      15.766090     101.332867       4.517395       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.152498      24.779343      18.248900     101.593876       5.808676       8.000000       7.000000     414.761101     508.339363     107.500011
max        40.972515      30.939312      27.310671     102.562660      18.654099      16.000000       8.000000    1470.000000    1389.587769     401.236755

==================== Cairns: CESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.260921      21.924234      15.205071     101.248230       4.470908       6.708042       4.805354     217.450302     235.050415      56.371914
std         3.553758       3.114014       3.319198       0.413168       2.287659       3.400200       2.418833     302.726471     294.514832      72.687469
min         9.303789       6.703586       2.287423      98.211075       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.110442      19.959377      12.904077     100.989906       3.083219       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.439608      22.382883      15.422143     101.282631       4.564756       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.617705      24.298039      17.755656     101.542526       5.902368       8.000000       7.000000     399.873878     488.511086     109.343351
max        40.150337      30.296480      26.086634     102.519577      18.542517      16.000000       8.000000    1470.000000    1118.006348     411.301453

==================== Cairns: CESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.857409      22.553471      15.877938     101.287544       4.456830       6.708042       4.805354     217.836731     236.395370      56.011917
std         3.547696       3.189406       3.525052       0.418353       2.272519       3.400200       2.418833     302.390564     295.548615      71.940758
min         9.751522       7.207784       2.687709      98.448799       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.732489      20.454216      13.333736     101.016762       3.090925       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.053331      22.965014      16.013921     101.315048       4.545756       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.194814      25.052724      18.660048     101.596394       5.924717       8.000000       7.000000     403.420914     490.885239     108.947859
max        41.670143      31.044537      27.522770     102.484505      20.553699      16.000000       8.000000    1470.000000    1126.255127     405.293579

==================== Cairns: CESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.032711      23.650984      17.009737     101.278793       4.387127       6.708042       4.805354     216.923996     234.358063      56.106026
std         3.447954       3.037266       3.550911       0.420588       2.276871       3.400200       2.418833     301.199524     292.849915      71.678421
min        11.897086       9.032903       2.880339      98.299583       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.892227      21.616110      14.442251     100.982460       3.016156       5.000000       2.000000       0.000000       0.000000       0.000000
50%        27.151079      24.083849      17.239579     101.300415       4.429051       7.000000       5.000000       0.000000       0.000000       0.000000
75%        29.276024      26.047289      19.842081     101.589556       5.813233       8.000000       7.000000     401.735481     486.081993     109.667908
max        43.878723      31.664711      28.322372     102.565338      19.852274      16.000000       8.000000    1470.000000    1131.720581     346.438507

==================== Cairns: CMCC-ESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.034286      21.724100      15.033784     101.195732       4.262359       6.708042       4.805354     218.775589     239.572784      55.065994
std         3.575156       3.176710       3.353921       0.424692       2.252886       3.400200       2.418833     303.150879     298.235962      70.586044
min         8.395432       6.301159       3.045443      98.162621       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.805099      19.623138      12.555273     100.908678       2.883452       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.265053      22.169847      15.201883     101.205479       4.282294       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.460354      24.249657      17.764703     101.507721       5.608362       8.000000       7.000000     405.921341     500.529137     107.144093
max        38.393005      30.558363      26.490583     102.468727      20.180681      16.000000       8.000000    1470.000000    1108.659546     385.958160

==================== Cairns: CMCC-ESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.494991      22.083681      15.334428     101.245811       4.375283       6.708042       4.805354     219.840942     241.871643      54.196655
std         3.556507       3.086185       3.345534       0.435605       2.284397       3.400200       2.418833     304.506195     300.798767      69.132790
min        10.128104       7.174377       3.064391      97.951050       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.210536      20.020762      12.880360     100.966545       2.985550       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.576197      22.471746      15.482912     101.260735       4.407843       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.891010      24.464195      17.903903     101.562469       5.790571       8.000000       7.000000     409.252731     504.190742     106.244471
max        40.737675      30.675325      26.392933     102.534225      22.624144      16.000000       8.000000    1470.000000    1145.005493     368.806915

==================== Cairns: CMCC-ESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.654634      22.267988      15.550426     101.267120       4.347141       6.708042       4.805354     220.638474     244.257599      53.438606
std         3.596723       3.191494       3.493772       0.428072       2.265322       3.400200       2.418833     305.398132     303.409821      67.997963
min         9.334566       6.538579       1.934240      98.347923       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.257184      20.102243      12.982811     100.977695       2.983892       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.821854      22.570480      15.575741     101.290634       4.400052       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.080143      24.855697      18.384112     101.596113       5.739763       8.000000       7.000000     411.197479     510.591599     105.235725
max        41.093090      30.522184      26.750902     102.522911      22.407000      16.000000       8.000000    1470.000000    1157.796265     371.895935

==================== Cairns: CMCC-ESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.020451      21.724804      15.030934     101.218300       4.303728       6.708042       4.805354     218.148880     238.179871      54.999054
std         3.540125       3.132491       3.324525       0.452875       2.277124       3.400200       2.418833     303.055908     297.413330      70.518677
min         8.510999       6.501832       2.866493      98.219383       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.793352      19.618760      12.566996     100.909157       2.858870       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.169357      22.105453      15.145775     101.263359       4.302123       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.356328      24.215089      17.722918     101.546432       5.672359       8.000000       7.000000     403.916924     496.206665     107.380657
max        39.088474      30.125029      25.833340     102.562119      23.162464      16.000000       8.000000    1470.000000    1119.504883     386.994232

==================== Cairns: CMCC-ESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.785723      22.422052      15.694793     101.240868       4.305908       6.708042       4.805354     217.771851     238.752899      54.396118
std         3.439116       3.015168       3.362821       0.436901       2.275003       3.400200       2.418833     302.290710     298.073486      69.934425
min         9.627048       7.281058       3.126570      98.020699       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.525730      20.354047      13.177091     100.959801       2.952834       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.903897      22.729213      15.741575     101.251640       4.301610       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.173269      24.761188      18.273092     101.558273       5.693930       8.000000       7.000000     403.848503     499.127289     105.744202
max        40.855434      31.458481      28.198748     102.556740      26.097029      16.000000       8.000000    1470.000000    1099.699951     394.452942

==================== Cairns: CMCC-ESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.716715      23.261166      16.544813     101.254646       4.389809       6.708042       4.805354     218.395660     239.294388      54.495815
std         3.398636       2.984664       3.467923       0.440136       2.280226       3.400200       2.418833     302.167419     297.230286      69.244354
min        10.973165       8.102011       2.770393      98.304970       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.469450      21.188897      13.926715     100.952965       2.967631       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.799616      23.591495      16.650726     101.276661       4.420696       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.995181      25.646561      19.330734     101.586067       5.743862       8.000000       7.000000     407.581779     496.665489     107.319489
max        42.439613      31.818453      28.201508     102.587967      20.901058      16.000000       8.000000    1470.000000    1143.104614     331.835724

==================== Cairns: EC-Earth3, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.48e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.248636      21.818735      15.072779     101.218369       4.398316       6.708042       4.805354     218.612564     238.439270      55.777939
std         3.604493       3.159425       3.386425       0.426935       2.279133       3.400200       2.418833     302.787506     298.747803      73.718025
min         7.276372       5.723317       2.500409      98.466179       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.991941      19.767031      12.631910     100.911972       3.025575       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.454752      22.177546      15.148835     101.254227       4.440759       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.670812      24.270371      17.699862     101.543541       5.858128       8.000000       7.000000     405.474152     495.316391     107.448137
max        40.897659      30.552999      26.192055     102.473000      18.269575      16.000000       8.000000    1470.000000    1476.296021     444.384399

==================== Cairns: EC-Earth3, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.639071      22.307489      15.605802     101.212944       4.327035       6.708042       4.805354     216.570099     235.478470      55.710518
std         3.474051       3.100722       3.394579       0.446589       2.255024       3.400200       2.418833     301.105225     295.791962      73.865654
min         9.638287       6.601241       2.741755      98.004807       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.502579      20.355954      13.211433     100.912514       2.993912       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.838271      22.698330      15.743155     101.254089       4.367719       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.978121      24.726900      18.282748     101.546257       5.670346       8.000000       7.000000     401.854019     491.801643     107.139523
max        37.929810      30.976372      26.765003     102.564034      21.546654      16.000000       8.000000    1470.000000    1473.667236     464.790955

==================== Cairns: EC-Earth3, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.728548      22.362614      15.647799     101.219734       4.378025       6.708042       4.805354     217.489090     237.692032      55.134293
std         3.508431       3.103060       3.401103       0.433471       2.259287       3.400200       2.418833     301.551147     297.375763      72.476608
min         9.999634       6.760337       2.899379      98.438332       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.578065      20.378071      13.216097     100.910515       3.020709       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.900234      22.795247      15.842502     101.253876       4.403064       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.074074      24.773051      18.325994     101.547035       5.721142       8.000000       7.000000     405.504501     496.705162     106.587297
max        41.787243      30.389860      26.183281     102.509117      23.773630      16.000000       8.000000    1470.000000    1044.982910     458.784515

==================== Cairns: EC-Earth3, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.526447      22.071745      15.304754     101.194717       4.374806       6.708042       4.805354     217.435913     235.791412      56.117477
std         3.579472       3.038801       3.275415       0.444375       2.258662       3.400200       2.418833     301.518280     295.490509      73.971710
min         9.697110       6.615901       2.839292      98.420578       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.251659      20.088767      12.942137     100.874207       2.995234       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.630490      22.356029      15.350714     101.245296       4.410964       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.899483      24.467774      17.866522     101.531105       5.736009       8.000000       7.000000     402.330864     488.937439     108.456947
max        39.531029      30.480507      26.198349     102.392334      20.830606      16.000000       8.000000    1470.000000    1064.371948     489.418304

==================== Cairns: EC-Earth3, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.52e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.200363      22.734480      16.011633     101.216690       4.419743       6.708042       4.805354     216.538956     235.564835      55.487255
std         3.558771       3.167410       3.573766       0.468287       2.295858       3.400200       2.418833     300.423370     295.423706      73.273537
min         9.657369       7.085099       2.751397      98.202087       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.891105      20.623143      13.396255     100.888794       3.076254       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.356745      23.048965      16.081601     101.266655       4.442433       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.582627      25.277878      18.928232     101.576103       5.843897       8.000000       7.000000     402.910431     490.346672     107.356958
max        40.989281      31.510374      27.558720     102.512413      19.816338      16.000000       8.000000    1470.000000    1521.096313     458.359558

==================== Cairns: EC-Earth3, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=1.87e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.116644      23.697521      17.056179     101.228561       4.378346       6.708042       4.805354     214.536194     230.974976      56.524845
std         3.375737       3.043108       3.604057       0.456823       2.261615       3.400200       2.418833     297.740997     289.935303      74.768082
min        10.138928       7.484135       3.300056      98.097244       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.044683      21.742361      14.475843     100.900490       2.960093       5.000000       2.000000       0.000000       0.000000       0.000000
50%        27.236925      24.103133      17.265551     101.274445       4.384063       7.000000       5.000000       0.000000       0.000000       0.000000
75%        29.331080      26.072760      19.892439     101.578997       5.752708       8.000000       7.000000     398.280418     479.030991     108.838751
max        41.910851      32.301853      28.752024     102.477501      19.288828      16.000000       8.000000    1470.000000    1865.311646     469.474030

==================== Cairns: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.303904      21.853790      15.094699     101.168701       4.240627       6.708042       4.805354     220.029129     237.312424      57.986897
std         3.567975       3.086907       3.303581       0.428028       2.222338       3.400200       2.418833     303.360199     294.914215      75.117355
min         8.782847       5.525243       2.615627      98.342110       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.143978      19.957584      12.823113     100.883415       2.883214       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.437648      22.215203      15.171468     101.207375       4.270715       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.725001      24.221355      17.689985     101.475639       5.658993       8.000000       7.000000     409.480560     494.168335     113.122726
max        40.078125      30.650799      27.251532     102.344902      20.610476      16.000000       8.000000    1470.000000    1058.480469     425.415802

==================== Cairns: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.260920      21.824507      15.085749     101.194038       4.248203       6.708042       4.805354     220.795975     239.946640      57.001102
std         3.655240       3.195773       3.392560       0.441579       2.218601       3.400200       2.418833     304.929230     298.410767      73.885521
min         9.450976       5.683709       2.594690      98.369926       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.045228      19.843985      12.749774     100.914764       2.878687       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.440841      22.220511      15.170042     101.233223       4.285795       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.744257      24.284556      17.726973     101.517937       5.675789       8.000000       7.000000     411.107452     501.024307     110.913357
max        39.323486      30.297583      25.842161     102.427597      20.838263      16.000000       8.000000    1470.000000    1068.606689     416.290222

==================== Cairns: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.293093      21.941755      15.221577     101.194260       4.169965       6.708042       4.805354     220.224060     238.694473      56.935074
std         3.608308       3.086058       3.268747       0.430909       2.204209       3.400200       2.418833     304.617065     297.712982      73.759529
min         9.876179       6.342648       3.121825      98.295525       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.051319      19.982002      12.933331     100.912254       2.811064       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.435987      22.356315      15.371335     101.213741       4.187685       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.738566      24.310316      17.738448     101.513979       5.578228       8.000000       7.000000     409.013977     497.979919     110.891100
max        40.037308      30.049906      26.083281     102.387993      20.771683      16.000000       8.000000    1470.000000    1121.756226     435.418640

==================== Cairns: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.158333      21.691288      14.937098     101.182045       4.257395       6.708042       4.805354     220.899979     239.434525      57.106239
std         3.698258       3.174815       3.339964       0.447403       2.242283       3.400200       2.418833     305.215332     298.302795      73.847534
min         8.833701       5.732798       2.886961      98.182480       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.854682      19.702881      12.637967     100.912918       2.895549       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.299032      22.049458      15.005542     101.236542       4.269013       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.686897      24.113711      17.513206     101.510536       5.704152       8.000000       7.000000     411.037849     498.342789     111.387974
max        40.246906      29.719528      25.266506     102.417488      18.973125      16.000000       8.000000    1470.000000    1084.599121     440.789520

==================== Cairns: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.891478      22.499067      15.769966     101.189804       4.253756       6.708042       4.805354     217.472076     233.123611      58.027271
std         3.439716       3.011761       3.362784       0.441387       2.229341       3.400200       2.418833     301.162720     291.297974      75.515549
min        10.773819       7.163683       3.008870      98.324303       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.762783      20.629994      13.461491     100.913801       2.884143       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.991259      22.795979      15.796637     101.239456       4.347736       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.240661      24.776903      18.325592     101.513771       5.616562       8.000000       7.000000     403.079201     483.962296     112.418898
max        40.431786      30.742128      27.358500     102.401352      16.804943      16.000000       8.000000    1470.000000    1064.654785     425.141937

==================== Cairns: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.404026      22.876972      16.132957     101.198219       4.234121       6.708042       4.805354     220.504608     239.584549      56.659473
std         3.608512       3.130310       3.526731       0.441118       2.229116       3.400200       2.418833     303.359833     297.532135      72.874710
min        10.761308       6.989612       2.977000      98.292542       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.175396      20.858307      13.627434     100.908936       2.834285       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.508322      23.239853      16.225437     101.246330       4.249394       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.822254      25.339662      18.949367     101.524025       5.624503       8.000000       7.000000     412.141739     499.371887     111.543501
max        41.642422      31.401510      27.008577     102.404045      15.673450      16.000000       8.000000    1470.000000    1062.430786     419.273499

==================== Cairns: NorESM2-MM, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       24.970222      21.468309      14.697152     101.258621       4.410885       6.708042       4.805354     223.232025     243.153809      57.249744
std         3.695938       3.236826       3.364616       0.398437       2.262613       3.400200       2.418833     308.225708     301.810272      73.558517
min         9.749026       6.301976       2.323719      98.299004       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.643024      19.367807      12.307726     100.988976       3.061444       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.224158      21.920769      14.848246     101.285156       4.455869       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.455332      23.989961      17.284519     101.561979       5.814979       8.000000       7.000000     417.353516     509.338425     111.950066
max        38.726772      30.231274      26.122744     102.401756      25.601274      16.000000       8.000000    1470.000000    1107.398438     398.816803

==================== Cairns: NorESM2-MM, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.245970      21.655115      14.841825     101.281853       4.380085       6.708042       4.805354     225.761368     247.213364      56.892967
std         3.733122       3.235490       3.384913       0.391674       2.220286       3.400200       2.418833     309.904938     304.918427      72.391258
min         9.288088       5.505322       2.946570      98.538017       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.840961      19.588035      12.504257     101.015049       3.040116       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.477232      22.052242      14.912424     101.309158       4.421682       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.787144      24.177556      17.454624     101.581642       5.764247       8.000000       7.000000     425.466782     515.031906     112.240524
max        40.678204      30.288593      25.843313     102.512009      20.524015      16.000000       8.000000    1470.000000    1094.502441     378.163757

==================== Cairns: NorESM2-MM, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03); rsdsdir out of range [0.0, 1300.0] (max=2.15e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.252979      21.644798      14.827679     101.301682       4.354356       6.708042       4.805354     225.460800     246.874023      56.774429
std         3.786685       3.275108       3.426222       0.391314       2.215701       3.400200       2.418833     310.110382     305.332855      72.293839
min         8.904137       5.627397       2.415872      98.357681       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.887861      19.540686      12.399941     101.040749       3.001947       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.464076      22.097082      14.975851     101.330566       4.406724       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.797424      24.171533      17.434189     101.601053       5.713254       8.000000       7.000000     423.674454     515.132141     112.194319
max        40.234264      30.656185      26.972633     102.470772      22.948065      16.000000       8.000000    1470.000000    2145.593506     666.258484

==================== Cairns: NorESM2-MM, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.161581      21.793098      15.064455     101.211197       4.389745       6.708042       4.805354     217.962875     230.529068      60.056400
std         3.523289       3.096796       3.309184       0.423862       2.250690       3.400200       2.418833     302.821198     288.115997      77.775978
min        10.015854       6.821634       2.588385      98.376839       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        22.870729      19.757236      12.702547     100.912123       3.018253       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.312488      22.112060      15.097523     101.251492       4.467043       7.000000       5.000000       0.000000       0.000000       0.000000
75%        27.518024      24.196615      17.567469     101.542261       5.842804       8.000000       7.000000     402.639244     480.068291     116.024944
max        39.134121      30.705006      26.464350     102.410736      21.757120      16.000000       8.000000    1470.000000    1062.577881     410.010529

==================== Cairns: NorESM2-MM, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       25.679123      22.180349      15.408772     101.264008       4.504567       6.708042       4.805354     221.243866     237.668747      58.476414
std         3.546184       3.169618       3.465004       0.430622       2.281421       3.400200       2.418833     305.838013     295.071899      74.885345
min        10.224999       6.697748       2.575098      97.827934       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        23.388350      20.071655      12.915501     100.976721       3.115567       5.000000       2.000000       0.000000       0.000000       0.000000
50%        25.849913      22.584064      15.532483     101.293846       4.629399       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.041993      24.640277      18.052248     101.592934       6.022642       8.000000       7.000000     413.411926     494.374611     114.461222
max        40.741352      30.858250      26.865194     102.481400      25.214161      16.000000       8.000000    1470.000000    1091.898193     386.198273

==================== Cairns: NorESM2-MM, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       26.243824      22.791687      16.073328     101.291122       4.471222       6.708042       4.805354     218.459183     233.037231      58.869602
std         3.542066       3.214268       3.609322       0.442775       2.243980       3.400200       2.418833     303.030945     290.587952      75.920204
min        10.812346       7.266387       2.592522      98.654434       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        24.011982      20.689507      13.517238     100.985565       3.120231       5.000000       2.000000       0.000000       0.000000       0.000000
50%        26.422438      23.159187      16.147547     101.336098       4.653881       7.000000       5.000000       0.000000       0.000000       0.000000
75%        28.563360      25.316793      18.870984     101.631187       5.896455       8.000000       7.000000     405.660782     485.541656     114.714539
max        40.765144      31.649410      28.124666     102.612328      20.917179      16.000000       8.000000    1470.000000    1085.255737     387.387848

==================== Canberra: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Canberra: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Canberra: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Canberra: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Canberra: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Canberra: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Canberra: CESM2, ssp126, 2021-2040 ====================
==================== Canberra: CESM2, ssp126, 2041-2060 ====================
==================== Canberra: CESM2, ssp126, 2061-2080 ====================
==================== Canberra: CESM2, ssp370, 2021-2040 ====================
==================== Canberra: CESM2, ssp370, 2041-2060 ====================
==================== Canberra: CESM2, ssp370, 2061-2080 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Canberra: EC-Earth3, ssp126, 2021-2040 ====================
==================== Canberra: EC-Earth3, ssp126, 2041-2060 ====================
==================== Canberra: EC-Earth3, ssp126, 2061-2080 ====================
==================== Canberra: EC-Earth3, ssp370, 2021-2040 ====================
==================== Canberra: EC-Earth3, ssp370, 2041-2060 ====================
==================== Canberra: EC-Earth3, ssp370, 2061-2080 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Canberra: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Canberra: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Canberra: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Canberra: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Canberra: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Canberra: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=61)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.997936      23.445616      16.511560     100.631897       3.731657       8.447432       5.051353     234.811783     260.197937      58.261044
std         3.592658       3.662610       4.522583       0.346968       2.110804       5.078871       2.216470     315.983978     314.923157      77.769714
min         4.474750       2.007257       1.317729      98.421326       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.865165      21.588086      13.884148     100.411366       2.339130       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.245336      24.690243      17.887734     100.641441       3.488234       8.000000       5.000000       8.946709       0.000000       6.779173
75%        30.609869      26.096227      19.981874     100.895794       4.885363      13.000000       7.000000     478.955856     582.146347     108.332638
max        38.501057      31.203680      28.269060     101.723190      60.984959      16.000000       8.000000    1161.244751     967.325745     418.533112

==================== Darwin: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       28.430235      23.850853      16.931219     100.635704       3.717810       8.447432       5.051353     234.997055     260.428833      58.088669
std         3.526110       3.538998       4.487511       0.347800       2.080849       5.078871       2.216470     316.044434     314.647644      77.260529
min         5.158726       3.173645       1.551681      98.466797       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        26.281105      22.040920      14.340405     100.404953       2.323812       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.696405      25.050479      18.324473     100.643028       3.463261       8.000000       5.000000       9.000000       0.000000       6.776908
75%        30.990113      26.421839      20.344649     100.899477       4.902022      13.000000       7.000000     478.798019     581.994019     108.055136
max        38.980038      31.838968      29.553957     101.733398      60.159542      16.000000       8.000000    1159.523071     965.127075     416.207886

==================== Darwin: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       28.498350      23.816839      16.862938     100.626465       3.791715       8.447432       5.051353     236.793243     263.576263      57.587849
std         3.625645       3.595416       4.529263       0.347218       2.104861       5.078871       2.216470     318.150085     317.954163      76.274544
min         5.024900       2.195188       1.441448      98.414978       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        26.346574      21.952443      14.219762     100.393196       2.395586       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.752189      25.011991      18.186371     100.625198       3.530393       8.000000       5.000000       9.000000       0.000000       6.765727
75%        31.133690      26.440657      20.342443     100.868118       4.999535      13.000000       7.000000     484.674103     590.590729     107.390499
max        38.722904      31.930834      29.938646     101.817162      60.478661      16.000000       8.000000    1162.985596     988.949097     387.192444

==================== Darwin: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=61.9)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.918060      23.399281      16.501736     100.612831       3.794518       8.447432       5.051353     232.806534     254.584457      59.565144
std         3.637331       3.778345       4.642213       0.358948       2.135244       5.078871       2.216470     314.190338     309.660706      79.256401
min         4.051133       1.135986       1.137563      98.408691       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.849394      21.434171      13.721226     100.380501       2.391032       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.217955      24.746398      18.036585     100.619694       3.536678       8.000000       5.000000       8.362651       0.000000       6.849957
75%        30.537133      26.145739      20.069642     100.862383       4.978381      13.000000       7.000000     472.146980     567.228088     111.340109
max        38.407356      31.037403      27.824249     101.739708      61.914597      16.000000       8.000000    1159.185303     966.431213     436.927826

==================== Darwin: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Darwin: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Darwin: CESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.980097      23.608160      16.750662     100.633125       3.686468       8.447432       5.051353     231.758789     254.535294      58.607399
std         3.465828       3.573181       4.498511       0.344830       2.034995       5.078871       2.216470     312.829987     310.816406      78.096527
min         3.686082       0.712542       1.239314      98.487312       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.975980      21.901113      14.170121     100.390680       2.353639       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.166549      24.842919      18.132277     100.642906       3.466268       8.000000       5.000000       8.653858       0.000000       6.827377
75%        30.456316      26.203325      20.232503     100.889229       4.844714      13.000000       7.000000     467.083275     564.639557     109.434708
max        38.338268      31.239597      28.254221     101.799629      60.715343      16.000000       8.000000    1158.981079     984.756287     430.014252

==================== Darwin: CESM2, ssp126, 2041-2060 ====================
==================== Darwin: CESM2, ssp126, 2061-2080 ====================
==================== Darwin: CESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.986254      23.563107      16.661358     100.647858       3.680558       8.447432       5.051353     231.974060     253.433701      59.132393
std         3.455936       3.498753       4.410995       0.327001       2.051766       5.078871       2.216470     313.144958     308.175446      77.427116
min         3.753082       0.881046       1.389637      98.679878       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.915573      21.822809      14.072783     100.436821       2.318175       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.160603      24.772762      18.068015     100.659988       3.437655       8.000000       5.000000       8.967239       0.000000       6.925848
75%        30.475183      26.098489      20.032863     100.876007       4.850109      13.000000       7.000000     468.660751     566.112152     112.560965
max        38.105167      30.908295      27.869295     101.789276      62.063747      16.000000       8.000000    1157.125244     979.478760     394.709534

==================== Darwin: CESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       28.653587      24.280682      17.491697     100.679588       3.683112       8.447432       5.051353     231.398193     253.411621      58.582825
std         3.393506       3.473664       4.559575       0.333767       2.063822       5.078871       2.216470     312.502228     308.450348      76.894119
min         4.196067       0.625174       1.366181      98.651978       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        26.622051      22.504507      14.865548     100.452377       2.324204       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.812897      25.437173      18.847649     100.695030       3.428073       8.000000       5.000000       8.256097       0.000000       6.905041
75%        31.091563      26.832006      21.034885     100.925959       4.825932      13.000000       7.000000     468.413231     567.621231     111.145901
max        38.906918      31.540651      28.616903     101.814178      62.006496      16.000000       8.000000    1150.158569     950.769836     399.357910

==================== Darwin: CESM2, ssp370, 2061-2080 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=61.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.553719      23.383821      16.587210     100.605659       3.641066       8.447432       5.051353     229.651688     253.681396      57.429611
std         3.403271       3.565508       4.394184       0.342036       2.036013       5.078871       2.216470     310.756317     309.353516      75.894478
min         3.789460       1.608410       1.638592      98.395988       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.547976      21.771402      14.191622     100.375778       2.283215       4.000000       3.000000       0.000000       0.000000       0.000000
50%        27.769883      24.619300      17.992637     100.604774       3.381410       8.000000       5.000000       8.966026       0.000000       6.799651
75%        29.985603      25.936604      19.988086     100.861748       4.798728      13.000000       7.000000     460.720863     564.147629     107.662384
max        38.063965      31.251369      28.864620     101.720169      61.664257      16.000000       8.000000    1158.286377     985.286743     414.090424

==================== Darwin: CMCC-ESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=61.9)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       28.215387      23.841766      16.993200     100.648399       3.699428       8.447432       5.051353     232.471115     260.206482      55.755936
std         3.353085       3.482841       4.443498       0.346952       2.036376       5.078871       2.216470     313.509399     314.740601      72.931396
min         3.824894       1.569649       1.491990      98.641441       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        26.181456      22.227319      14.510841     100.403435       2.338486       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.389032      25.002690      18.364645     100.647995       3.452598       8.000000       5.000000       9.000000       0.000000       6.783243
75%        30.635527      26.355389      20.430363     100.906334       4.905631      13.000000       7.000000     470.857033     582.771194     105.886705
max        38.463303      31.340387      28.733297     101.811447      61.896610      16.000000       8.000000    1165.714111     980.682251     385.975647

==================== Darwin: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=61.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       27.539978      23.310167      16.468201     100.630753       3.786998       8.447432       5.051353     229.687622     252.076187      57.788879
std         3.399181       3.515131       4.377041       0.352136       2.116307       5.078871       2.216470     311.766968     308.524536      76.242264
min         3.727676       2.101172       1.635494      98.705376       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        25.492655      21.577677      13.871320     100.395462       2.390296       4.000000       3.000000       0.000000       0.000000       0.000000
50%        27.695535      24.447064      17.770783     100.638123       3.537003       8.000000       5.000000       8.350688       0.000000       6.824840
75%        29.983493      25.892993      19.903334     100.898598       4.994081      13.000000       7.000000     459.126007     561.502121     109.472160
max        38.335087      31.105520      28.570515     101.819397      61.206596      16.000000       8.000000    1161.611084     994.718872     417.303741

==================== Darwin: CMCC-ESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       28.460285      24.107420      17.307489     100.652306       3.695527       8.447432       5.051353     229.861343     253.655457      57.199268
std         3.351400       3.498690       4.501740       0.343064       2.100448       5.078871       2.216470     310.674042     308.388275      74.880791
min         4.149684       2.231459       1.609333      98.618530       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        26.401548      22.526582      14.870252     100.425262       2.276119       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.630935      25.276934      18.719566     100.652020       3.367163       8.000000       5.000000       8.620739       0.000000       6.817297
75%        30.911542      26.608673      20.745685     100.887997       4.903427      13.000000       7.000000     463.459015     567.532150     108.838123
max        38.833385      31.865313      29.482109     101.767029      60.542152      16.000000       8.000000    1156.370972     985.056885     382.415161

==================== Darwin: CMCC-ESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=61.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       29.391127      24.922983      18.209520     100.651344       3.694788       8.447432       5.051353     229.651001     253.933395      56.838749
std         3.197820       3.442772       4.647129       0.354745       2.062624       5.078871       2.216470     310.149780     308.015747      74.111259
min         5.253137       3.088016       1.781996      98.562103       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        27.427878      23.398086      15.688229     100.393139       2.305070       4.000000       3.000000       0.000000       0.000000       0.000000
50%        29.510461      26.081123      19.710970     100.646736       3.417411       8.000000       5.000000       8.674380       0.000000       6.866988
75%        31.708880      27.380216      21.753977     100.922203       4.909451      13.000000       7.000000     464.768227     568.295029     108.521492
max        39.964573      32.682350      31.040461     101.877403      61.547688      16.000000       8.000000    1151.246338     980.953857     380.483734

==================== Darwin: EC-Earth3, ssp126, 2021-2040 ====================
==================== Darwin: EC-Earth3, ssp126, 2041-2060 ====================
==================== Darwin: EC-Earth3, ssp126, 2061-2080 ====================
==================== Darwin: EC-Earth3, ssp370, 2021-2040 ====================
==================== Darwin: EC-Earth3, ssp370, 2041-2060 ====================
==================== Darwin: EC-Earth3, ssp370, 2061-2080 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Darwin: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Darwin: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Darwin: NorESM2-MM, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       28.200363      23.482422      16.493788     100.669998       3.697816       8.447432       5.051353     238.119949     259.543274      61.656879
std         3.644105       3.755979       4.649892       0.343654       2.088605       5.078871       2.216470     318.877075     313.325409      80.594734
min         4.453884       0.968408       1.119686      98.621300       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        26.059198      21.657273      13.812573     100.447372       2.308932       4.000000       3.000000       0.000000       0.000000       0.000000
50%        28.408970      24.727665      17.851946     100.689499       3.361768       8.000000       5.000000       9.000000       0.000000       6.862272
75%        30.858884      26.208375      20.074524     100.917984       4.913857      13.000000       7.000000     492.291084     581.572052     117.248678
max        37.990189      31.629957      29.206964     101.875900      60.758736      16.000000       8.000000    1166.260132    1011.771057     417.724670

==================== Darwin: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Darwin: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Darwin: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Hobart: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Hobart: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Hobart: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Hobart: CESM2, ssp126, 2021-2040 ====================
==================== Hobart: CESM2, ssp126, 2041-2060 ====================
==================== Hobart: CESM2, ssp126, 2061-2080 ====================
==================== Hobart: CESM2, ssp370, 2021-2040 ====================
==================== Hobart: CESM2, ssp370, 2041-2060 ====================
==================== Hobart: CESM2, ssp370, 2061-2080 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Hobart: EC-Earth3, ssp126, 2021-2040 ====================
==================== Hobart: EC-Earth3, ssp126, 2041-2060 ====================
==================== Hobart: EC-Earth3, ssp126, 2061-2080 ====================
==================== Hobart: EC-Earth3, ssp370, 2021-2040 ====================
==================== Hobart: EC-Earth3, ssp370, 2041-2060 ====================
==================== Hobart: EC-Earth3, ssp370, 2061-2080 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Hobart: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Hobart: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Hobart: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Hobart: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Hobart: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Hobart: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Longreach: CESM2, ssp126, 2021-2040 ====================
==================== Longreach: CESM2, ssp126, 2041-2060 ====================
==================== Longreach: CESM2, ssp126, 2061-2080 ====================
==================== Longreach: CESM2, ssp370, 2021-2040 ====================
==================== Longreach: CESM2, ssp370, 2041-2060 ====================
==================== Longreach: CESM2, ssp370, 2061-2080 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Longreach: EC-Earth3, ssp126, 2021-2040 ====================
==================== Longreach: EC-Earth3, ssp126, 2041-2060 ====================
==================== Longreach: EC-Earth3, ssp126, 2061-2080 ====================
==================== Longreach: EC-Earth3, ssp370, 2021-2040 ====================
==================== Longreach: EC-Earth3, ssp370, 2041-2060 ====================
==================== Longreach: EC-Earth3, ssp370, 2061-2080 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Longreach: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Longreach: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Longreach: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Longreach: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Longreach: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Longreach: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.531325      11.811526       7.376869     100.381027       5.033895      11.070873       5.530114     178.273987     197.229126      60.457741
std         6.198773       4.013904       2.264378       0.749708       2.951959       4.549204       2.366922     267.716064     260.492004      83.693253
min        -0.103054      -0.651840       1.010355      96.607674       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.161758       8.897761       5.739625      99.915327       2.932193       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.571415      11.420112       6.927511     100.386803       4.557750      12.000000       6.000000       5.000000       0.000000       3.533095
75%        18.865087      14.537907       8.583199     100.869034       6.734211      16.000000       8.000000     292.145226     386.395157     108.606462
max        46.054981      31.133121      22.816242     102.893982      60.722473      16.000000       8.000000    1160.785400    1199.771606     384.553467

==================== Melbourne: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62.4)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.102825      12.261433       7.584716     100.425217       5.033574      11.070873       5.530114     179.911774     201.527191      59.421043
std         6.195697       3.982809       2.295161       0.750465       2.917476       4.549204       2.366922     269.445343     265.448059      81.616379
min        -0.330783      -0.876673       1.253946      96.768875       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.741392       9.379382       5.917593      99.958336       2.937562       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.206291      11.938084       7.141523     100.411938       4.572999      12.000000       6.000000       5.000000       0.000000       3.575004
75%        19.463557      14.981495       8.826676     100.919550       6.763319      16.000000       8.000000     295.530464     396.907028     107.881886
max        46.024250      30.911898      22.242794     102.889420      62.408310      16.000000       8.000000    1156.264282    1197.048340     386.100403

==================== Melbourne: ACCESS-CM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=67.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.295013      13.239286       8.100165     100.453812       5.021338      11.070873       5.530114     182.291245     208.625412      57.972675
std         6.283189       4.004872       2.475118       0.742287       2.964911       4.549204       2.366922     270.723358     272.319550      78.908920
min         1.007026       0.254081       1.359668      96.731865       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.880138      10.344679       6.307106      99.976494       2.864297       8.000000       3.000000       0.000000       0.000000       0.000000
50%        16.380933      12.928984       7.642319     100.463440       4.516448      12.000000       6.000000       5.000000       0.000000       3.536509
75%        20.707258      15.973498       9.430471     100.947010       6.786067      16.000000       8.000000     303.197510     416.881943     106.780920
max        48.716286      32.144634      24.352167     103.073837      67.160454      16.000000       8.000000    1147.663330    1197.025391     362.227722

==================== Melbourne: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.828556      11.114563       6.954268     100.316254       5.152277      11.070873       5.530114     176.140991     199.093445      57.018738
std         6.093755       3.789683       1.994021       0.774577       2.996179       4.549204       2.366922     265.821716     264.405090      78.524094
min        -0.347352      -0.767189       1.131052      96.669197       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.598959       8.426037       5.543543      99.811794       3.019137       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.876400      10.751985       6.588119     100.362915       4.711369      12.000000       6.000000       5.000000       0.000000       3.544888
75%        17.954703      13.639334       7.973189     100.857521       6.924413      16.000000       8.000000     286.340675     385.975510     102.705109
max        46.912033      28.745781      19.555138     102.676300      63.076942      16.000000       8.000000    1160.641602    1220.037964     383.724365

==================== Melbourne: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.146629      11.370245       7.072396     100.346336       5.152930      11.070873       5.530114     177.240799     201.031509      56.971783
std         6.091629       3.800953       2.057911       0.758243       2.970427       4.549204       2.366922     266.582825     265.911469      78.123215
min        -0.261397      -0.497062       1.156457      96.670677       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.864138       8.654508       5.629183      99.849119       3.054982       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.189798      11.003727       6.684732     100.386314       4.742246      12.000000       6.000000       5.000000       0.000000       3.548948
75%        18.304509      13.877388       8.086638     100.875259       6.894587      16.000000       8.000000     290.507889     390.862114     103.644030
max        45.978588      29.814081      21.138041     102.818398      66.025017      16.000000       8.000000    1159.939697    1203.588379     383.286407

==================== Melbourne: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=69.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.100798      11.310390       7.028278     100.322853       5.215484      11.070873       5.530114     177.495087     202.250504      56.695320
std         6.101746       3.755262       1.995199       0.769000       3.020826       4.549204       2.366922     267.024506     267.446899      77.713150
min         0.027173      -0.360411       1.017489      96.773369       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.849519       8.655432       5.631540      99.826332       3.097646       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.111368      10.949427       6.672438     100.371933       4.759102      12.000000       6.000000       5.000000       0.000000       3.500546
75%        18.240057      13.781954       8.035152     100.856285       6.963042      16.000000       8.000000     290.138870     392.675972     102.870564
max        46.550621      29.282137      19.659599     102.582878      69.228134      16.000000       8.000000    1162.125732    1227.623535     367.702454

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=65.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.976366      11.285618       7.082135     100.291641       5.141773      11.070873       5.530114     175.341019     197.054276      57.664921
std         6.171349       3.928288       2.140351       0.764331       2.982071       4.549204       2.366922     264.301544     261.278595      79.740746
min        -0.825777      -0.994830       1.153015      96.760666       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.673354       8.473479       5.563166      99.786680       3.021962       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.985590      10.877410       6.674997     100.328377       4.691540      12.000000       6.000000       5.000000       0.000000       3.545967
75%        18.184857      13.856338       8.127063     100.831804       6.913312      16.000000       8.000000     285.809349     382.354820     103.695465
max        46.032303      30.046921      21.127144     102.560417      65.330750      16.000000       8.000000    1158.484131    1170.394287     374.841644

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.642995      11.706628       7.209986     100.311165       5.191436      11.070873       5.530114     178.293030     203.772827      56.271217
std         6.233574       3.860063       2.114691       0.753085       2.961069       4.549204       2.366922     267.496124     269.346558      76.668312
min         0.368887      -0.375447       1.006666      96.727852       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.284374       8.945027       5.713188      99.810806       3.122939       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.667941      11.331360       6.832084     100.342907       4.770742      12.000000       6.000000       5.000000       0.000000       3.582899
75%        18.883723      14.281660       8.296448     100.828295       6.910652      16.000000       8.000000     292.990280     397.581169     102.905680
max        46.413994      29.768307      20.087963     102.531693      63.718647      16.000000       8.000000    1159.421631    1224.052856     389.263275

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.4)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.189083      12.130075       7.407357     100.360031       5.121290      11.070873       5.530114     179.314331     206.943680      55.607700
std         6.205415       3.880510       2.223178       0.764910       2.952823       4.549204       2.366922     267.747101     271.957245      75.194191
min         0.818206       0.002908       1.222068      96.575180       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.876985       9.354051       5.826601      99.862831       3.041771       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.215612      11.760901       7.001882     100.388893       4.689630      12.000000       6.000000       5.000000       0.000000       3.521764
75%        19.377103      14.722853       8.557958     100.895901       6.862641      16.000000       8.000000     296.657967     405.377205     102.686550
max        48.489529      30.728973      22.301615     102.751671      66.392021      16.000000       8.000000    1152.685791    1192.319824     375.743225

==================== Melbourne: CESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.618358      11.703814       7.222283     100.359779       5.073233      11.070873       5.530114     180.402451     197.145279      62.330433
std         6.365462       3.924424       2.115022       0.756759       2.934424       4.549204       2.366922     269.894409     260.945282      85.524086
min        -0.426962      -0.873275       0.837922      96.631165       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.180049       8.904491       5.721475      99.854332       2.987837       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.608016      11.364785       6.840560     100.373226       4.648071      12.000000       6.000000       5.000000       0.000000       3.735887
75%        18.877897      14.291894       8.315405     100.899633       6.850813      16.000000       8.000000     297.057686     384.317146     113.545074
max        46.799583      29.863213      21.101799     102.654182      63.300911      16.000000       8.000000    1158.924438    1165.750366     406.958771

==================== Melbourne: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=67)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.553931      11.659492       7.185046     100.367546       5.072341      11.070873       5.530114     180.689713     197.080963      62.863831
std         6.229958       3.784946       2.029095       0.760595       2.915873       4.549204       2.366922     269.925568     260.211029      86.372940
min         0.219515      -0.643884       1.021190      96.655914       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.252685       8.983154       5.754029      99.872574       3.034920       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.574792      11.343253       6.827004     100.387360       4.653752      12.000000       6.000000       5.000000       0.000000       3.694802
75%        18.638746      14.159052       8.257898     100.893114       6.752570      16.000000       8.000000     298.119904     383.984840     114.291817
max        46.457722      29.028280      20.292112     102.871284      66.989769      16.000000       8.000000    1155.500122    1169.142456     402.869568

==================== Melbourne: CESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=68.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.027107      12.085685       7.414402     100.398422       5.013665      11.070873       5.530114     181.493576     199.929794      61.888512
std         6.287432       3.805638       2.071223       0.746127       2.910845       4.549204       2.366922     270.781799     263.972809      84.678627
min         0.077331      -0.283639       1.042457      97.012749       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.642377       9.381410       5.941912      99.905077       2.963319       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.036129      11.782180       7.071749     100.411491       4.561976      12.000000       6.000000       5.000000       0.000000       3.641279
75%        19.217131      14.635338       8.523678     100.913704       6.738763      16.000000       8.000000     299.492050     390.650452     113.470251
max        48.034401      29.924196      21.772764     102.893127      68.064842      16.000000       8.000000    1159.782715    1173.127808     402.996185

==================== Melbourne: CESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=67.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.409580      11.577477       7.168341     100.346313       5.074358      11.070873       5.530114     180.106583     196.439148      62.615238
std         6.232045       3.812105       2.034837       0.756661       2.939443       4.549204       2.366922     269.409241     260.655060      86.445518
min        -0.455841      -0.943575       1.000136      96.336159       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.132881       8.887928       5.726488      99.851044       2.986642       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.430491      11.258000       6.813195     100.380409       4.645736      12.000000       6.000000       5.000000       0.000000       3.667901
75%        18.554040      14.100168       8.221919     100.861614       6.814796      16.000000       8.000000     297.315300     382.599304     114.043434
max        46.991314      29.282770      20.596077     102.634483      67.812027      16.000000       8.000000    1158.424561    1162.072632     401.506348

==================== Melbourne: CESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.277424      12.312138       7.544550     100.400734       5.004336      11.070873       5.530114     182.377411     202.317444      61.163937
std         6.338521       3.844607       2.130901       0.735269       2.902263       4.549204       2.366922     271.816345     267.014160      83.315300
min         0.384992      -0.149693       1.244955      96.840286       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.862821       9.577934       6.019371      99.897079       2.934524       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.304787      12.023890       7.179664     100.413010       4.559248      12.000000       6.000000       5.000000       0.000000       3.685541
75%        19.548050      14.911494       8.693742     100.913872       6.740254      16.000000       8.000000     302.206940     396.907547     113.024843
max        48.848351      30.212254      20.924976     102.773911      66.780159      16.000000       8.000000    1156.783081    1141.474121     385.536438

==================== Melbourne: CESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=71.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.149942      13.087029       7.988649     100.402092       4.929635      11.070873       5.530114     183.849945     207.137085      60.076534
std         6.367422       3.904778       2.321764       0.739396       2.903679       4.549204       2.366922     272.904755     272.059692      81.523598
min         1.097703       0.217507       1.279093      96.502502       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.710685      10.298894       6.313870      99.905987       2.821319       8.000000       3.000000       0.000000       0.000000       0.000000
50%        16.230586      12.826896       7.594050     100.408012       4.447280      12.000000       6.000000       5.000000       0.000000       3.671432
75%        20.432032      15.756885       9.244027     100.918625       6.655531      16.000000       8.000000     306.901352     410.187683     111.957632
max        49.033020      30.850632      22.706730     102.803864      71.752548      16.000000       8.000000    1153.207275    1155.737427     375.518799

==================== Melbourne: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Melbourne: EC-Earth3, ssp126, 2021-2040 ====================
==================== Melbourne: EC-Earth3, ssp126, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=64.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.379117      11.759018       7.381169     100.302284       5.110409      11.070873       5.530114     176.906204     205.732971      54.144508
std         6.167104       3.921571       2.196122       0.741903       2.971378       4.549204       2.366922     266.077881     271.369202      74.533005
min        -0.513657      -0.955252       1.209546      96.738525       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.099408       8.963434       5.824327      99.826553       3.010650       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.417142      11.357460       6.940514     100.329262       4.663867      12.000000       6.000000       5.000000       0.000000       3.472311
75%        18.617810      14.360280       8.481630     100.813065       6.853568      16.000000       8.000000     289.666878     403.137871      98.235682
max        48.870899      30.389820      20.448885     102.651031      64.113052      16.000000       8.000000    1152.597656    1263.718140     377.394135

==================== Melbourne: EC-Earth3, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.007277      11.498501       7.256409     100.298439       5.089129      11.070873       5.530114     175.957642     202.826462      54.739784
std         5.919363       3.763982       2.115470       0.741400       2.988323       4.549204       2.366922     265.242920     268.551361      75.474159
min        -0.291945      -0.690658       0.996118      96.865974       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.894992       8.840771       5.783357      99.807716       2.978769       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.087896      11.127792       6.871181     100.318207       4.644180      12.000000       6.000000       5.000000       0.000000       3.478921
75%        18.122639      13.957282       8.275850     100.823816       6.831309      16.000000       8.000000     286.274658     396.091270      99.073269
max        46.386269      31.353874      23.014818     102.531380      62.082966      16.000000       8.000000    1153.969238    1270.263306     382.604126

==================== Melbourne: EC-Earth3, ssp370, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp370, 2061-2080 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.010630      11.318649       7.095140     100.266678       5.099665      11.070873       5.530114     177.841736     194.038010      61.681107
std         6.102441       3.887536       2.083079       0.717385       2.945330       4.549204       2.366922     266.895233     257.644440      85.333916
min        -0.800102      -1.317492       1.091066      96.764015       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.721417       8.499355       5.614222      99.821081       2.989467       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.035348      10.964333       6.712484     100.293434       4.676203      12.000000       6.000000       5.000000       0.000000       3.670185
75%        18.274302      13.948295       8.182140     100.751545       6.880129      16.000000       8.000000     292.579514     377.563889     111.698244
max        47.005581      30.052673      22.415030     102.579636      63.096943      16.000000       8.000000    1158.712036    1179.791138     398.966125

==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=64.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.939062      11.253831       7.051738     100.274200       5.142421      11.070873       5.530114     177.531219     193.047150      61.971600
std         6.096351       3.824584       2.020216       0.739462       2.954115       4.549204       2.366922     266.568146     256.454468      85.877457
min        -0.761103      -1.357618       1.068552      96.717186       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.680860       8.493986       5.619788      99.803505       3.043009       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.028439      10.946495       6.692413     100.298386       4.705102      12.000000       6.000000       5.000000       0.000000       3.684438
75%        18.068648      13.850190       8.112788     100.787872       6.929862      16.000000       8.000000     291.443573     374.797844     111.835901
max        47.494614      29.919510      20.639996     102.620354      64.139435      16.000000       8.000000    1159.631226    1156.849731     407.706757

==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=65.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.045078      11.299865       7.046026     100.255524       5.152332      11.070873       5.530114     177.209137     193.270111      61.982456
std         6.080519       3.754251       1.978213       0.750326       2.984864       4.549204       2.366922     265.958466     256.157623      86.304977
min        -0.294435      -1.090013       1.073083      96.663956       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.844420       8.638255       5.655499      99.791462       3.046429       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.079565      10.982233       6.726159     100.267883       4.717704      12.000000       6.000000       5.000000       0.000000       3.646026
75%        18.123494      13.778832       8.083613     100.753658       6.906268      16.000000       8.000000     290.934433     376.129181     111.106161
max        49.065086      30.818733      20.679546     102.893700      65.127029      16.000000       8.000000    1158.171753    1170.046753     414.415405

==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.641752      11.049652       6.974258     100.275688       5.152061      11.070873       5.530114     176.404495     190.406006      62.432705
std         5.988352       3.811095       2.033363       0.745778       2.963718       4.549204       2.366922     265.362488     253.596436      86.813782
min        -0.657534      -1.088343       1.111232      96.782913       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.468550       8.310267       5.541519      99.801733       3.045237       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.734991      10.723775       6.603927     100.291935       4.710205      12.000000       6.000000       5.000000       0.000000       3.668579
75%        17.755959      13.622129       8.004312     100.784599       6.944489      16.000000       8.000000     287.925362     367.018295     111.916128
max        47.198418      30.106237      22.136194     102.598816      63.169559      16.000000       8.000000    1159.717529    1177.044312     418.088226

==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.094948      12.082659       7.410778     100.299599       5.133793      11.070873       5.530114     182.389282     205.616486      59.506870
std         6.275306       3.934172       2.216873       0.757223       2.976959       4.549204       2.366922     270.962616     269.743774      81.126572
min        -0.008120      -0.613467       1.124660      96.767090       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.664053       9.226855       5.854141      99.823576       3.015595       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.106494      11.704772       6.987552     100.319221       4.691563      12.000000       6.000000       5.000000       0.000000       3.574983
75%        19.398636      14.754706       8.560213     100.805370       6.905490      16.000000       8.000000     303.741867     406.767403     109.895704
max        49.541595      31.150095      21.669933     102.779655      63.600735      16.000000       8.000000    1154.705200    1240.042236     391.170868

==================== Melbourne: NorESM2-MM, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.341386      10.775394       6.828103     100.314827       5.216906      11.070873       5.530114     174.771301     184.578995      64.622292
std         5.941798       3.789258       1.981702       0.765910       2.970525       4.549204       2.366922     264.167816     245.787643      91.111626
min        -0.702973      -1.149123       1.143336      96.700653       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.193715       8.078682       5.417987      99.827650       3.096362       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.373537      10.401580       6.463453     100.332848       4.807735      12.000000       6.000000       5.000000       0.000000       3.729281
75%        17.370737      13.267813       7.810354     100.840769       7.018087      16.000000       8.000000     283.798363     355.016869     113.454596
max        46.190670      28.893206      21.113146     102.832909      66.669327      16.000000       8.000000    1164.892822    1151.770996     436.891113

==================== Melbourne: NorESM2-MM, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.456693      10.804914       6.802025     100.339622       5.166265      11.070873       5.530114     176.800369     188.365952      63.718540
std         6.067743       3.752761       1.933027       0.756109       2.929114       4.549204       2.366922     267.481293     252.134201      89.285355
min        -0.582734      -0.798177       1.107561      96.578819       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.252072       8.133388       5.440352      99.859947       3.130417       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.430303      10.434591       6.438679     100.375504       4.767453      12.000000       6.000000       5.000000       0.000000       3.712096
75%        17.486921      13.255364       7.770691     100.854065       6.887295      16.000000       8.000000     285.974976     359.841675     112.997406
max        46.780834      28.933035      19.434690     103.019516      62.043240      16.000000       8.000000    1163.882202    1095.593384     424.953369

==================== Melbourne: NorESM2-MM, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.376375      10.808512       6.839595     100.352852       5.223528      11.070873       5.530114     175.541580     186.619003      63.969254
std         5.956358       3.766104       1.963585       0.770118       2.960127       4.549204       2.366922     265.506531     248.840454      90.024910
min        -0.741317      -1.094702       1.125728      96.596329       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.253171       8.131505       5.436037      99.869637       3.131403       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.429887      10.483313       6.487458     100.376060       4.817501      12.000000       6.000000       5.000000       0.000000       3.706555
75%        17.380329      13.280904       7.850837     100.874527       7.018879      16.000000       8.000000     284.679085     358.851822     112.627651
max        45.872555      28.938297      20.074171     103.042595      66.300690      16.000000       8.000000    1163.136230    1132.498169     419.073212

==================== Melbourne: NorESM2-MM, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=65)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.198185      10.715555       6.838752     100.287811       5.216755      11.070873       5.530114     172.220428     177.995499      65.678856
std         5.986358       3.831620       2.005785       0.771798       2.966753       4.549204       2.366922     261.103271     238.787811      93.058708
min        -0.842186      -1.145031       1.181095      96.790092       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.036271       7.989903       5.425230      99.784302       3.079856       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.192846      10.290709       6.435675     100.306061       4.817064      12.000000       6.000000       5.000000       0.000000       3.719295
75%        17.241839      13.202083       7.818274     100.836754       7.037048      16.000000       8.000000     278.039581     339.364311     114.288290
max        45.556755      28.713484      20.913597     102.712769      65.046051      16.000000       8.000000    1162.302124    1134.821411     450.375000

==================== Melbourne: NorESM2-MM, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.041800      11.347757       7.101709     100.347649       5.161282      11.070873       5.530114     176.746445     189.716003      63.148029
std         6.099096       3.860930       2.077054       0.763508       2.940399       4.549204       2.366922     266.916473     252.595154      88.273338
min        -0.059903      -0.608210       1.177436      96.837265       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.759281       8.572299       5.628664      99.851866       3.078647       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.091337      11.005273       6.708224     100.372940       4.748676      12.000000       6.000000       5.000000       0.000000       3.712749
75%        18.238458      13.955603       8.165133     100.886909       6.880485      16.000000       8.000000     287.023048     366.506088     112.324398
max        47.338150      29.951212      21.770842     102.732330      66.084068      16.000000       8.000000    1159.131348    1158.988525     396.887817

==================== Melbourne: NorESM2-MM, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=69.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.647951      11.916795       7.420563     100.396996       5.150136      11.070873       5.530114     178.249481     193.739380      62.320957
std         6.250585       3.931626       2.201454       0.766026       2.931838       4.549204       2.366922     268.421844     256.832977      86.473854
min         0.349574      -0.158930       1.150941      96.785912       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.286812       9.076270       5.837569      99.897160       3.045976       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.642450      11.563823       6.997269     100.420929       4.751136      12.000000       6.000000       5.000000       0.000000       3.703393
75%        18.821293      14.570474       8.567862     100.928757       6.880580      16.000000       8.000000     291.056564     377.208351     111.947289
max        47.247547      29.888203      21.429182     102.843071      69.648834      16.000000       8.000000    1154.170898    1132.278076     395.328644

==================== Mildura: ACCESS-CM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.977858      11.885610       6.439435     101.162430       3.504560       8.242009       4.915679     215.937607     260.977600      56.371788
std         8.179610       4.524054       2.487178       0.701685       1.877337       4.525698       2.531601     305.430542     322.136017      72.900841
min        -3.393896      -3.709968       0.094581      97.761871       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.962532       8.832355       4.834090     100.671053       2.320109       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.106719      11.656516       5.955457     101.134937       3.189549       8.000000       5.000000       3.000000       0.000000       2.038766
75%        23.443057      14.852817       7.419673     101.635378       4.673476      12.000000       7.000000     393.374481     577.559067     113.013836
max        46.477520      28.568113      23.129454     103.536591      44.212128      16.000000       8.000000    1214.730103    1339.583008     305.358612

==================== Mildura: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.36e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.594336      12.251691       6.558155     101.175743       3.477372       8.242009       4.915679     217.510635     266.438934      54.860336
std         8.385674       4.572275       2.544026       0.707723       1.841760       4.525698       2.531601     306.309265     327.631653      70.543434
min        -3.413312      -3.362093       0.095515      97.780426       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.392579       9.129263       4.922481     100.691139       2.304806       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.725170      12.036248       6.048953     101.145580       3.181717       8.000000       5.000000       3.000000       0.000000       2.013867
75%        24.287265      15.300030       7.548825     101.652599       4.608327      12.000000       7.000000     400.568970     593.646225     110.553188
max        47.390968      28.904385      25.819323     103.581543      44.400455      16.000000       8.000000    1211.147339    1357.691040     288.461060

==================== Mildura: ACCESS-CM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.871655      12.453649       6.637494     101.149529       3.537822       8.242009       4.915679     218.686142     268.851440      54.418983
std         8.383680       4.508714       2.451715       0.700275       1.876341       4.525698       2.531601     307.621552     330.113098      69.640373
min        -2.749683      -3.189476       0.092796      97.715500       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.696931       9.386302       5.015781     100.666313       2.369315       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.957546      12.275589       6.165523     101.110188       3.195523       8.000000       5.000000       3.000000       0.000000       2.045730
75%        24.523015      15.509451       7.703041     101.627634       4.691853      12.000000       7.000000     403.054863     600.633850     110.717495
max        47.606041      27.990751      23.084795     103.663155      42.185028      16.000000       8.000000    1210.348755    1336.810547     287.333099

==================== Mildura: ACCESS-CM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.222008      12.010959       6.468851     101.156357       3.500932       8.242009       4.915679     216.667328     262.831940      55.893440
std         8.252975       4.554597       2.511326       0.689888       1.854890       4.525698       2.531601     305.529022     323.637939      72.057976
min        -3.686892      -3.532593       0.101631      97.757027       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.132220       8.924413       4.841102     100.673111       2.331859       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.277649      11.777622       5.970940     101.120644       3.209131       8.000000       5.000000       3.000000       0.000000       2.059254
75%        23.822728      15.040117       7.442114     101.629166       4.651522      12.000000       7.000000     397.243431     582.041641     112.847036
max        46.400368      28.175673      23.442816     103.351265      41.986347      16.000000       8.000000    1210.428223    1333.729126     306.509918

==================== Mildura: ACCESS-CM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.32e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.147501      12.654985       6.733161     101.210083       3.465507       8.242009       4.915679     218.932602     270.593048      53.508842
std         8.422853       4.554647       2.545750       0.728859       1.828473       4.525698       2.531601     307.901245     332.666901      68.305641
min        -2.776856      -2.832890       0.102253      97.894981       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.901569       9.570180       5.078710     100.687988       2.299111       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.307014      12.491618       6.238672     101.186138       3.205905       8.000000       5.000000       3.000000       0.000000       2.057019
75%        24.911567      15.708404       7.762609     101.711403       4.596281      12.000000       7.000000     406.115593     602.228134     108.898367
max        47.570293      28.571447      24.126297     103.616760      44.690033      16.000000       8.000000    1206.678589    1322.484741     267.278046

==================== Mildura: ACCESS-CM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.36e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.336212      13.586078       7.212930     101.224770       3.449906       8.242009       4.915679     220.063904     275.162018      52.278351
std         8.483577       4.573862       2.764879       0.712574       1.818759       4.525698       2.531601     307.909943     336.171326      66.357948
min        -2.140947      -2.894869       0.109254      97.815430       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        14.104181      10.511307       5.401660     100.712145       2.302859       5.000000       3.000000       0.000000       0.000000       0.000000
50%        19.502973      13.445055       6.675478     101.212318       3.217391       8.000000       5.000000       3.000000       0.000000       2.027247
75%        26.134420      16.625003       8.363887     101.722416       4.556680      12.000000       7.000000     412.355118     618.690292     107.127844
max        49.416546      30.376913      27.685308     103.695389      43.024021      16.000000       8.000000    1203.493530    1359.985962     259.313782

==================== Mildura: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.992468      11.609974       6.117472     101.143425       3.581250       8.242009       4.915679     217.546021     270.063141      52.052689
std         8.240036       4.264753       2.112148       0.710877       1.912774       4.525698       2.531601     307.535614     333.909515      66.870834
min        -3.280123      -3.344219       0.102344      97.872505       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.930709       8.711879       4.747997     100.650841       2.389355       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.003147      11.421243       5.791313     101.141289       3.304701       8.000000       5.000000       3.000000       0.000000       2.042014
75%        23.357869      14.498498       7.065566     101.643429       4.742691      12.000000       7.000000     399.470467     592.686203     104.641640
max        47.621250      27.568663      22.005663     103.410141      45.694412      16.000000       8.000000    1211.940308    1336.074341     270.992493

==================== Mildura: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.267479      11.852150       6.246670     101.163025       3.562934       8.242009       4.915679     218.492126     273.132935      51.462467
std         8.267843       4.292986       2.195253       0.702244       1.893392       4.525698       2.531601     308.246368     336.168518      65.862144
min        -2.875259      -3.736740       0.102338      97.894432       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.158313       8.950148       4.834793     100.666374       2.392574       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.317623      11.673169       5.910218     101.152466       3.260287       8.000000       5.000000       3.000000       0.000000       2.055467
75%        23.733959      14.735278       7.193844     101.658642       4.732720      12.000000       7.000000     403.588501     603.621826     104.132332
max        48.375011      27.522314      22.317432     103.365936      46.365562      16.000000       8.000000    1205.919312    1325.772217     263.203156

==================== Mildura: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.155504      11.786426       6.220554     101.154518       3.579608       8.242009       4.915679     219.169357     274.591614      50.929935
std         8.282110       4.248936       2.134514       0.700768       1.916053       4.525698       2.531601     309.467834     338.822479      64.977112
min        -3.913260      -3.713090       0.105869      97.925934       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.069592       8.926247       4.829109     100.673317       2.411876       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.221579      11.622683       5.899229     101.150429       3.236432       8.000000       5.000000       3.000000       0.000000       2.025152
75%        23.560091      14.651068       7.199161     101.650269       4.765748      12.000000       7.000000     404.199768     606.192673     104.137415
max        48.453926      28.238632      20.777668     103.336594      45.621933      16.000000       8.000000    1212.422119    1343.442017     273.450195

==================== Mildura: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.3e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.055653      11.868298       6.386062     101.118149       3.556358       8.242009       4.915679     215.699753     265.945740      53.149132
std         8.298412       4.482205       2.382003       0.713072       1.915422       4.525698       2.531601     304.578583     327.693909      68.286224
min        -3.836841      -3.448680       0.110194      97.910080       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.922454       8.794882       4.843705     100.610458       2.352280       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.074956      11.615836       5.961744     101.108124       3.257200       8.000000       5.000000       3.000000       0.000000       2.058979
75%        23.452259      14.858140       7.368951     101.632238       4.731716      12.000000       7.000000     395.496918     591.127930     106.945044
max        47.713799      28.527723      22.947062     103.306458      45.479034      16.000000       8.000000    1209.232422    1304.188477     259.285278

==================== Mildura: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.863214      12.169058       6.323984     101.137810       3.565980       8.242009       4.915679     219.319870     275.789337      50.673904
std         8.448847       4.338554       2.200283       0.696895       1.905373       4.525698       2.531601     308.696350     338.546112      64.311600
min        -3.076963      -3.863633       0.097688      97.885078       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.633539       9.247174       4.872472     100.646931       2.404299       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.967250      12.047653       6.017088     101.111893       3.216813       8.000000       5.000000       3.000000       0.000000       2.024786
75%        24.394352      15.116658       7.371947     101.619522       4.739775      12.000000       7.000000     405.876099     612.420822     103.797821
max        48.733627      27.570038      21.480455     103.226273      45.736557      16.000000       8.000000    1208.134277    1331.289307     249.768524

==================== Mildura: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.35e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.483433      12.492931       6.412431     101.175407       3.567625       8.242009       4.915679     221.393829     282.134125      49.461811
std         8.636171       4.474297       2.298289       0.715629       1.910340       4.525698       2.531601     309.606110     344.059326      62.408134
min        -3.496155      -3.212398       0.114141      97.875389       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        13.126342       9.463842       4.895642     100.673817       2.369460       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.671391      12.392533       6.033770     101.160423       3.262482       8.000000       5.000000       3.000000       0.000000       2.020223
75%        25.233387      15.551480       7.470992     101.690403       4.732908      12.000000       7.000000     414.840515     631.487274     101.750662
max        48.707432      27.917463      23.087645     103.394539      46.066650      16.000000       8.000000    1205.158569    1349.974731     244.682358

==================== Mildura: CESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.561827      12.074369       6.369148     101.163559       3.486235       8.242009       4.915679     219.914597     269.280609      55.088619
std         8.453737       4.438105       2.325407       0.713242       1.856418       4.525698       2.531601     309.126678     332.345551      71.268005
min        -2.915806      -3.511629       0.114309      97.966049       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.338934       9.065752       4.861569     100.650640       2.311615       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.665528      11.936816       5.965248     101.148335       3.179857       8.000000       5.000000       3.000000       0.000000       2.017315
75%        24.179994      15.046173       7.356207     101.674942       4.666584      12.000000       7.000000     407.483574     590.688156     109.943375
max        47.975384      27.873861      21.477865     103.386978      43.025204      16.000000       8.000000    1208.926758    1338.621338     314.691498

==================== Mildura: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.566628      12.030750       6.304805     101.188927       3.505174       8.242009       4.915679     221.818451     272.837585      54.632019
std         8.440686       4.348717       2.206045       0.710674       1.867569       4.525698       2.531601     311.585358     336.085846      70.044891
min        -2.792189      -3.003968       0.099506      97.953529       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.433064       9.131497       4.874277     100.686577       2.333683       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.626400      11.929005       5.951797     101.171776       3.177607       8.000000       5.000000       3.000000       0.000000       2.022543
75%        24.081388      14.984971       7.298087     101.699387       4.629974      12.000000       7.000000     410.951988     600.068588     110.925344
max        47.367344      27.379118      20.365435     103.564751      44.697594      16.000000       8.000000    1210.021362    1340.147461     293.938568

==================== Mildura: CESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.080769      12.407489       6.459314     101.207024       3.452339       8.242009       4.915679     221.398544     273.156616      54.086296
std         8.475008       4.281528       2.188748       0.699708       1.850295       4.525698       2.531601     311.195282     336.778839      69.544609
min        -2.246819      -2.878940       0.118462      98.151993       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.814917       9.526077       5.026367     100.710075       2.279613       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.173217      12.309205       6.127226     101.173683       3.145994       8.000000       5.000000       3.000000       0.000000       2.024936
75%        24.684789      15.340381       7.453546     101.686480       4.597132      12.000000       7.000000     410.429489     599.024353     109.499052
max        48.663765      27.359957      21.034061     103.524422      41.566998      16.000000       8.000000    1207.726196    1326.207642     294.173767

==================== Mildura: CESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.433640      11.982744       6.306969     101.155731       3.505031       8.242009       4.915679     219.322006     267.064087      55.512859
std         8.389296       4.293499       2.171165       0.700303       1.860470       4.525698       2.531601     309.090240     330.877930      72.084892
min        -2.636545      -2.820839       0.116145      97.736443       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.274785       9.081439       4.881571     100.670244       2.374234       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.450009      11.845946       5.951305     101.137817       3.178996       8.000000       5.000000       3.000000       0.000000       2.027508
75%        23.894346      14.889391       7.262119     101.653229       4.639207      12.000000       7.000000     403.818382     581.722321     111.257040
max        47.043770      26.214630      20.343800     103.428864      43.170872      16.000000       8.000000    1211.409424    1335.714233     336.004883

==================== Mildura: CESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.293716      12.630113       6.611058     101.199051       3.437920       8.242009       4.915679     220.854721     272.728577      53.914406
std         8.566931       4.360683       2.278360       0.695381       1.825379       4.525698       2.531601     310.169464     335.967499      69.296822
min        -3.069904      -2.689072       0.126580      98.271423       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.955896       9.681623       5.128101     100.704666       2.284101       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.429013      12.533707       6.236642     101.176674       3.139859       8.000000       5.000000       3.000000       0.000000       2.056991
75%        25.005925      15.609608       7.617700     101.681301       4.550813      12.000000       7.000000     411.307236     601.638565     108.959644
max        47.764469      27.399841      21.142408     103.423134      40.982063      16.000000       8.000000    1207.711792    1344.088623     287.528015

==================== Mildura: CESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.312326      13.403423       7.000966     101.194374       3.405898       8.242009       4.915679     222.870911     279.462372      52.272270
std         8.650393       4.418439       2.528528       0.702400       1.825280       4.525698       2.531601     311.778778     342.023438      66.813461
min        -2.566716      -2.617538       0.123797      98.008194       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        13.961487      10.457938       5.358584     100.705086       2.257682       5.000000       3.000000       0.000000       0.000000       0.000000
50%        19.480272      13.340339       6.572742     101.166973       3.129539       8.000000       5.000000       3.000000       0.000000       2.061769
75%        26.098539      16.386216       8.090837     101.689524       4.498400      12.000000       7.000000     418.309135     625.251740     107.328268
max        48.399658      29.886675      24.235958     103.432518      45.232929      16.000000       8.000000    1204.107544    1336.076904     285.721008

==================== Mildura: CMCC-ESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.32e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.791565      11.770997       6.377457     101.095528       3.549605       8.242009       4.915679     215.515869     261.199738      55.663002
std         8.080907       4.337198       2.253353       0.701291       1.864596       4.525698       2.531601     304.507935     324.219147      73.224998
min        -3.899462      -3.603228       0.102664      97.929718       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.891419       8.867028       4.896589     100.616753       2.443767       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.886484      11.569879       6.002103     101.070969       3.243378       8.000000       5.000000       3.000000       0.000000       2.045006
75%        23.012849      14.614163       7.349584     101.578583       4.705194      12.000000       7.000000     394.168434     569.573380     109.874557
max        47.875046      27.012085      21.363192     103.427223      42.853401      16.000000       8.000000    1210.746582    1319.015747     354.238251

==================== Mildura: CMCC-ESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.35e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.256884      12.211624       6.609608     101.159874       3.499678       8.242009       4.915679     215.063583     260.749969      55.407413
std         8.068719       4.264283       2.287689       0.706708       1.838100       4.525698       2.531601     304.102448     323.653381      72.828583
min        -2.200713      -2.324877       0.100627      98.229813       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.292734       9.292517       5.128929     100.669518       2.352549       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.372200      12.007436       6.206908     101.132729       3.191015       8.000000       5.000000       3.000000       0.000000       2.025699
75%        23.550121      15.073039       7.585726     101.642279       4.642619      12.000000       7.000000     393.858490     570.051788     109.291803
max        46.463413      28.336863      23.179281     103.645523      40.842228      16.000000       8.000000    1208.408569    1346.151855     326.315369

==================== Mildura: CMCC-ESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.347141      12.123137       6.478095     101.177567       3.550783       8.242009       4.915679     218.036682     268.186798      53.964954
std         8.127174       4.250553       2.232228       0.711216       1.873578       4.525698       2.531601     307.281647     330.830353      70.339401
min        -2.485389      -2.590950       0.090321      98.027328       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.409115       9.263564       4.999691     100.690084       2.425518       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.462564      11.965383       6.125478     101.146915       3.260623       8.000000       5.000000       3.000000       0.000000       2.034495
75%        23.557648      14.944701       7.485828     101.676964       4.686391      12.000000       7.000000     402.017807     594.709412     107.716179
max        47.641891      27.923458      22.804964     103.562836      44.094650      16.000000       8.000000    1206.294556    1335.720703     306.310638

==================== Mildura: CMCC-ESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.795086      11.768346       6.368642     101.135078       3.532516       8.242009       4.915679     215.776642     261.928497      55.562626
std         8.055683       4.322556       2.266504       0.706575       1.876280       4.525698       2.531601     304.802826     324.467133      72.828835
min        -3.027177      -2.663927       0.106585      97.861282       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.889552       8.841087       4.888379     100.642639       2.385752       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.951756      11.572104       5.957731     101.112442       3.209373       8.000000       5.000000       3.000000       0.000000       2.033604
75%        22.978958      14.621069       7.316842     101.630241       4.686526      12.000000       7.000000     395.307976     576.074860     109.892874
max        47.008732      26.487700      20.410830     103.505737      42.757092      16.000000       8.000000    1206.468506    1336.710938     306.775787

==================== Mildura: CMCC-ESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.35e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.692125      12.239203       6.461186     101.143860       3.538788       8.242009       4.915679     218.333328     269.546265      53.547344
std         8.320192       4.296040       2.214882       0.706361       1.859211       4.525698       2.531601     307.341919     331.938873      69.542976
min        -1.880960      -2.530902       0.089177      97.922859       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.597425       9.338455       4.983055     100.657570       2.407529       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.717120      12.053617       6.117477     101.120087       3.207206       8.000000       5.000000       3.000000       0.000000       2.023926
75%        24.114592      15.098304       7.491832     101.631210       4.699405      12.000000       7.000000     403.480125     596.878662     107.192968
max        48.215061      27.363146      21.564131     103.587166      42.800137      16.000000       8.000000    1207.298950    1351.347534     292.257538

==================== Mildura: CMCC-ESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.355696      12.935528       6.893695     101.150215       3.529615       8.242009       4.915679     218.306488     270.384521      52.825943
std         8.247384       4.260628       2.425300       0.715221       1.860013       4.525698       2.531601     307.557861     333.451996      68.374397
min        -0.794251      -0.623923       0.098253      97.971947       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        13.244780      10.037184       5.313223     100.648367       2.413173       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.440161      12.727816       6.484982     101.119251       3.199611       8.000000       5.000000       3.000000       0.000000       2.050915
75%        24.786262      15.763557       7.941140     101.651413       4.685344      12.000000       7.000000     404.367500     597.118027     106.266350
max        49.071354      28.837095      24.288363     103.508484      41.866848      16.000000       8.000000    1202.144775    1328.769287     286.282562

==================== Mildura: EC-Earth3, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.37e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.940596      11.829381       6.370868     101.123741       3.564467       8.242009       4.915679     216.341232     270.961517      51.030766
std         8.101035       4.330988       2.314165       0.697170       1.893846       4.525698       2.531601     306.124023     333.914124      66.180069
min        -3.327343      -3.224977       0.112110      97.868195       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.980175       8.869233       4.871449     100.642448       2.395342       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.956751      11.589321       5.978525     101.113537       3.280890       8.000000       5.000000       3.000000       0.000000       2.008211
75%        23.274668      14.716977       7.324835     101.611406       4.732712      12.000000       7.000000     394.332909     602.117294     101.121338
max        47.561520      27.910809      23.818201     103.312798      44.803467      16.000000       8.000000    1206.816650    1373.025024     278.890564

==================== Mildura: EC-Earth3, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.074858      12.049316       6.538706     101.117020       3.567053       8.242009       4.915679     215.472473     268.693390      51.313095
std         8.156007       4.332617       2.370135       0.710209       1.885194       4.525698       2.531601     304.985840     332.082672      66.707886
min        -2.421978      -2.271999       0.096381      97.895729       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.029721       9.092212       5.020432     100.627693       2.442938       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.001300      11.730997       6.126081     101.103886       3.220755       8.000000       5.000000       3.000000       0.000000       2.027698
75%        23.413222      14.847250       7.444775     101.623203       4.719418      12.000000       7.000000     392.449104     591.500732     101.510365
max        48.183788      29.154766      23.561003     103.411095      45.252605      16.000000       8.000000    1204.607666    1340.932373     296.709412

==================== Mildura: EC-Earth3, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.35e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.394142      12.242495       6.603329     101.115013       3.534332       8.242009       4.915679     216.154160     270.764557      50.891380
std         8.263348       4.362444       2.398561       0.690929       1.876593       4.525698       2.531601     305.726807     333.653778      65.771019
min        -2.575535      -2.387080       0.109203      97.922455       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.247734       9.261764       5.060880     100.631241       2.403573       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.337206      11.982930       6.181120     101.095024       3.194266       8.000000       5.000000       3.000000       0.000000       2.010897
75%        23.819394      15.110629       7.569112     101.599709       4.696807      12.000000       7.000000     394.855377     600.493637     101.624603
max        49.501064      28.256004      24.145527     103.323967      43.804951      16.000000       8.000000    1204.371338    1353.891479     282.594513

==================== Mildura: EC-Earth3, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.091927      12.052329       6.527284     101.106743       3.518413       8.242009       4.915679     215.491806     268.233673      51.371548
std         8.048855       4.282149       2.418377       0.692447       1.865494       4.525698       2.531601     305.165009     331.481018      66.488800
min        -3.301281      -2.350765       0.105368      98.009842       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.167070       9.129331       4.985837     100.622620       2.370948       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.050476      11.777544       6.099735     101.093498       3.211385       8.000000       5.000000       3.000000       0.000000       2.030473
75%        23.377220      14.842644       7.475374     101.608078       4.688507      12.000000       7.000000     392.410454     590.686783     102.226984
max        47.713093      28.513590      23.828608     103.293152      43.208950      16.000000       8.000000    1205.621460    1332.302246     278.986267

==================== Mildura: EC-Earth3, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.37e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.630163      12.415322       6.683437     101.132317       3.540735       8.242009       4.915679     215.819458     270.364838      50.809799
std         8.202133       4.380317       2.430436       0.716790       1.891874       4.525698       2.531601     304.652191     332.632874      65.732643
min        -2.127389      -2.878776       0.113583      98.019508       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.537755       9.417087       5.105693     100.623976       2.367337       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.624690      12.169938       6.260498     101.116096       3.200138       8.000000       5.000000       3.000000       0.000000       2.033118
75%        24.087152      15.302588       7.650411     101.647545       4.725300      12.000000       7.000000     395.764206     600.632294     101.315189
max        49.338268      29.430773      24.223524     103.516930      44.017078      16.000000       8.000000    1198.280151    1369.921265     278.025482

==================== Mildura: EC-Earth3, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.36e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.623627      13.204940       7.092534     101.133469       3.531725       8.242009       4.915679     217.563904     276.111450      48.922459
std         8.372288       4.414741       2.657018       0.716725       1.866119       4.525698       2.531601     306.406250     338.680084      62.558502
min        -1.820904      -1.357090       0.096911      97.937851       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        13.346529      10.134658       5.378837     100.623787       2.390955       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.501383      12.875147       6.618528     101.110657       3.226866       8.000000       5.000000       3.000000       0.000000       2.025498
75%        25.291667      16.118952       8.175333     101.643280       4.701530      12.000000       7.000000     402.021851     614.164520      99.126789
max        49.743305      30.142130      27.605406     103.434959      43.192719      16.000000       8.000000    1198.627319    1363.022339     254.070831

==================== Mildura: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.32e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.964170      11.878696       6.418280     101.071892       3.537709       8.242009       4.915679     215.446121     263.199127      54.447624
std         8.117304       4.355952       2.296830       0.674178       1.840773       4.525698       2.531601     304.336548     325.958099      70.426147
min        -1.868599      -2.355773       0.095659      98.190605       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.912952       8.867299       4.941728     100.612587       2.434489       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.016579      11.645437       6.012805     101.056526       3.315949       8.000000       5.000000       3.000000       0.000000       2.048481
75%        23.319716      14.803792       7.382068     101.527626       4.677382      12.000000       7.000000     393.593124     577.378738     109.182732
max        47.283550      27.773947      22.660717     103.320595      43.739128      16.000000       8.000000    1210.800049    1316.463867     308.964508

==================== Mildura: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.32e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.048990      11.835018       6.335904     101.089783       3.563955       8.242009       4.915679     216.390869     264.637421      54.285439
std         8.197054       4.347896       2.264158       0.693741       1.863956       4.525698       2.531601     305.607117     327.401672      70.128189
min        -2.305645      -2.926824       0.102074      97.961960       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.998443       8.852143       4.890281     100.623384       2.433655       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.079105      11.628048       5.961912     101.070240       3.283535       8.000000       5.000000       3.000000       0.000000       2.052946
75%        23.423937      14.763710       7.254525     101.562378       4.746821      12.000000       7.000000     394.836205     579.213135     108.398760
max        47.777538      28.677465      23.840933     103.313492      44.000671      16.000000       8.000000    1209.540283    1318.196167     295.739197

==================== Mildura: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.060190      11.877373       6.359095     101.077110       3.577160       8.242009       4.915679     217.137573     265.960846      54.167122
std         8.100837       4.242096       2.218065       0.697123       1.884076       4.525698       2.531601     306.530701     328.827484      69.836433
min        -1.809983      -3.063448       0.103657      98.077637       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.086966       8.975632       4.928710     100.613462       2.446556       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.099746      11.676716       5.984268     101.050262       3.269226       8.000000       5.000000       3.000000       0.000000       2.034034
75%        23.304955      14.699610       7.288828     101.541046       4.729985      12.000000       7.000000     397.435104     582.934006     109.574734
max        47.954960      27.939075      21.720346     103.525864      46.018299      16.000000       8.000000    1210.781494    1329.167480     290.122772

==================== Mildura: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.32e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.618134      11.665234       6.356245     101.099991       3.558439       8.242009       4.915679     215.535187     261.871063      54.743721
std         8.007963       4.398983       2.449145       0.698729       1.887747       4.525698       2.531601     305.155701     325.171661      70.704346
min        -2.494708      -2.661972       0.096161      98.026154       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.672922       8.649264       4.830942     100.611786       2.364046       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.726740      11.416473       5.884563     101.085136       3.265468       8.000000       5.000000       3.000000       0.000000       2.065167
75%        22.912426      14.542221       7.242482     101.582397       4.725334      12.000000       7.000000     390.758476     569.857132     109.767992
max        46.366764      28.057516      23.643618     103.328682      47.777344      16.000000       8.000000    1210.649414    1321.432495     297.108551

==================== Mildura: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.593094      12.248665       6.536481     101.075043       3.570842       8.242009       4.915679     217.226501     267.673889      53.175110
std         8.238235       4.405776       2.440296       0.692512       1.868539       4.525698       2.531601     306.243347     330.653412      68.204407
min        -2.610288      -3.043260       0.108101      97.999260       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.532158       9.241854       4.973217     100.604311       2.440457       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.678516      12.066059       6.110359     101.055290       3.278161       8.000000       5.000000       3.000000       0.000000       2.041460
75%        24.000358      15.169564       7.532555     101.548485       4.759493      12.000000       7.000000     398.961029     587.819916     107.274822
max        48.413021      29.179232      24.801546     103.543861      42.722008      16.000000       8.000000    1204.981445    1328.063965     284.393402

==================== Mildura: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.36e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.212391      12.578159       6.616628     101.098953       3.555290       8.242009       4.915679     220.146729     276.718231      51.237892
std         8.399134       4.430831       2.410829       0.710724       1.865258       4.525698       2.531601     308.405487     338.755280      64.955429
min        -1.539464      -2.166019       0.094690      97.814476       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.929491       9.543209       5.079642     100.605749       2.393152       5.000000       3.000000       0.000000       0.000000       0.000000
50%        18.302184      12.349297       6.210712     101.077919       3.259135       8.000000       5.000000       3.000000       0.000000       2.019448
75%        24.878159      15.550406       7.623321     101.587448       4.725873      12.000000       7.000000     410.009705     616.160919     105.400015
max        48.931095      29.195541      23.213066     103.365761      44.706429      16.000000       8.000000    1205.944458    1359.331299     253.060181

==================== Mildura: NorESM2-MM, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.33e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.355555      11.326350       6.120225     101.154243       3.576346       8.242009       4.915679     217.651627     258.522217      59.090473
std         8.094342       4.378882       2.259886       0.708473       1.932423       4.525698       2.531601     308.157806     321.280640      78.161850
min        -3.796726      -3.757602       0.095661      97.838333       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.437899       8.358866       4.650410     100.663521       2.369378       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.474597      11.129737       5.701799     101.129326       3.249894       8.000000       5.000000       3.000000       0.000000       2.040120
75%        22.563874      14.249872       7.050902     101.648941       4.763255      12.000000       7.000000     398.175980     563.601685     116.107445
max        48.150826      26.530285      22.299231     103.619171      42.430565      16.000000       8.000000    1213.867676    1334.196289     356.034607

==================== Mildura: NorESM2-MM, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.576891      11.289676       5.976936     101.177742       3.579050       8.242009       4.915679     219.648422     261.390594      58.605331
std         8.215961       4.293151       2.139171       0.698201       1.908643       4.525698       2.531601     310.835663     325.718872      76.876778
min        -3.201599      -3.245926       0.089382      97.909538       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.531711       8.353454       4.579983     100.702295       2.399945       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.610888      11.081951       5.618006     101.170052       3.246734       8.000000       5.000000       3.000000       0.000000       2.027337
75%        22.879223      14.163486       6.894607     101.655880       4.747870      12.000000       7.000000     400.692429     562.520142     116.536440
max        48.441692      25.823862      20.136665     103.628731      43.499321      16.000000       8.000000    1212.085205    1343.547729     356.714844

==================== Mildura: NorESM2-MM, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.418234      11.361883       6.117128     101.193199       3.570809       8.242009       4.915679     218.294342     259.598663      58.832504
std         8.056638       4.319836       2.228679       0.717263       1.901362       4.525698       2.531601     309.091492     322.948792      77.501648
min        -3.526998      -3.549932       0.094200      97.903053       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.557528       8.432296       4.647819     100.697479       2.391594       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.490860      11.183341       5.716732     101.175583       3.303993       8.000000       5.000000       3.000000       0.000000       2.066227
75%        22.615648      14.245339       7.075135     101.680733       4.743283      12.000000       7.000000     398.203682     563.575943     115.957809
max        47.731457      26.347633      21.339590     103.687088      45.257114      16.000000       8.000000    1210.352173    1338.180298     367.044495

==================== Mildura: NorESM2-MM, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.32e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.216673      11.300899       6.152353     101.129898       3.580683       8.242009       4.915679     214.415848     249.638626      60.879200
std         8.027030       4.341716       2.249950       0.723841       1.908063       4.525698       2.531601     304.542786     312.566925      80.890434
min        -3.626000      -3.468670       0.111024      98.121620       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.302507       8.328109       4.695711     100.617325       2.415445       5.000000       3.000000       0.000000       0.000000       0.000000
50%        16.234400      11.027945       5.718372     101.107124       3.296775       8.000000       5.000000       3.000000       0.000000       2.077909
75%        22.417418      14.150064       7.039740     101.652290       4.750504      12.000000       7.000000     387.498878     535.499008     118.955963
max        47.060467      25.630432      20.054632     103.475479      46.004974      16.000000       8.000000    1211.248657    1324.621582     391.975342

==================== Mildura: NorESM2-MM, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.31e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.149094      11.853615       6.321712     101.178940       3.525821       8.242009       4.915679     218.172012     260.196198      58.351143
std         8.261539       4.455154       2.355509       0.722354       1.891433       4.525698       2.531601     308.207367     322.916779      76.429100
min        -3.262905      -3.234428       0.099767      98.193718       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.031572       8.801332       4.778136     100.660515       2.331384       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.328928      11.695196       5.886122     101.157856       3.246863       8.000000       5.000000       3.000000       0.000000       2.103221
75%        23.654637      14.889375       7.308476     101.695786       4.700381      12.000000       7.000000     400.059380     568.129410     115.841763
max        49.325668      27.376858      23.337564     103.527199      42.702564      16.000000       8.000000    1207.955688    1307.262939     326.497742

==================== Mildura: NorESM2-MM, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: rsdsdir out of range [0.0, 1300.0] (max=1.34e+03)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.847536      12.455420       6.642845     101.205147       3.510051       8.242009       4.915679     219.353134     264.249054      57.315182
std         8.407135       4.487594       2.500965       0.729223       1.844954       4.525698       2.531601     309.366699     326.335876      74.697128
min        -2.272093      -2.049033       0.106882      98.037994       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.608722       9.342546       5.008266     100.695580       2.359604       5.000000       3.000000       0.000000       0.000000       0.000000
50%        17.926988      12.236966       6.144228     101.202080       3.271379       8.000000       5.000000       3.000000       0.000000       2.064449
75%        24.460958      15.511186       7.662532     101.720654       4.668519      12.000000       7.000000     403.443520     581.905273     115.266127
max        48.062321      27.747686      23.500938     103.608177      39.208191      16.000000       8.000000    1202.201904    1343.669556     330.515198

==================== Perth: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Perth: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Perth: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Perth: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Perth: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Perth: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Perth: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Perth: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Perth: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Perth: CESM2, ssp126, 2021-2040 ====================
==================== Perth: CESM2, ssp126, 2041-2060 ====================
==================== Perth: CESM2, ssp126, 2061-2080 ====================
==================== Perth: CESM2, ssp370, 2021-2040 ====================
==================== Perth: CESM2, ssp370, 2041-2060 ====================
==================== Perth: CESM2, ssp370, 2061-2080 ====================
==================== Perth: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Perth: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Perth: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Perth: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Perth: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Perth: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Perth: EC-Earth3, ssp126, 2021-2040 ====================
==================== Perth: EC-Earth3, ssp126, 2041-2060 ====================
==================== Perth: EC-Earth3, ssp126, 2061-2080 ====================
==================== Perth: EC-Earth3, ssp370, 2021-2040 ====================
==================== Perth: EC-Earth3, ssp370, 2041-2060 ====================
==================== Perth: EC-Earth3, ssp370, 2061-2080 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Perth: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Perth: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Perth: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Perth: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Perth: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Perth: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Sydney: ACCESS-CM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.130867      15.380145       9.612392     101.705032       5.298214       8.790234       4.708213     185.756729     215.973007      56.573566
std         5.083143       4.498854       3.441239       0.702213       2.896600       4.883113       2.710749     271.525879     275.314331      80.302734
min         3.224391       2.137795       1.003819      98.682777       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.576349      12.035764       6.910674     101.223740       3.106841       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.242184      15.537904       9.374931     101.727989       4.749761       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.606404      19.031787      12.220377     102.202068       7.186980      13.000000       8.000000     322.240479     445.330338      99.736807
max        45.894802      27.219656      20.927223     104.046432      87.129517      16.000000       8.000000    1117.243164     830.124573     343.097687

==================== Sydney: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=86.4)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.646961      15.832911       9.912708     101.737854       5.270539       8.790234       4.708213     187.645477     220.659912      55.832699
std         5.048621       4.525580       3.546287       0.693721       2.865295       4.883113       2.710749     272.646667     279.500824      78.645775
min         4.050428       2.648865       0.990809      98.711220       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.142726      12.458995       7.103464     101.275778       3.120121       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.855089      16.113082       9.744279     101.746262       4.735383       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.119240      19.538448      12.613081     102.204201       7.179427      13.000000       8.000000     328.413948     457.755447      99.058985
max        47.099106      27.174555      21.514912     104.053787      86.393425      16.000000       8.000000    1115.196045     833.689148     326.439301

==================== Sydney: ACCESS-CM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=96.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.919901      16.110983      10.135882     101.710182       5.312461       8.790234       4.708213     187.067612     220.649536      55.555740
std         5.078272       4.591629       3.654596       0.698660       2.931153       4.883113       2.710749     271.533997     279.657562      78.500870
min         3.826426       2.466673       1.177683      98.722275       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.384741      12.676339       7.222615     101.255524       3.106245       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.085644      16.356982       9.954847     101.727913       4.757182       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.430629      19.882237      12.981985     102.182922       7.192836      13.000000       8.000000     328.176620     459.146225      97.989527
max        46.599163      27.539675      21.370928     104.205872      96.658592      16.000000       8.000000    1107.312622     836.501953     319.831543

==================== Sydney: ACCESS-CM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=92.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.140362      15.498568       9.744771     101.721413       5.309072       8.790234       4.708213     185.910156     216.163040      56.762836
std         4.994163       4.530606       3.486090       0.689646       2.912945       4.883113       2.710749     270.774597     274.478271      80.333740
min         3.439166       2.103929       1.081680      98.483284       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.652525      12.102594       6.978516     101.268997       3.097584       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.328047      15.756851       9.553493     101.748810       4.753943       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.633530      19.238916      12.470263     102.189720       7.182188      13.000000       8.000000     324.302765     446.344154     100.367188
max        45.276936      26.499283      20.772552     103.912941      92.136108      16.000000       8.000000    1106.800659     836.126648     338.996338

==================== Sydney: ACCESS-CM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.264212      16.482157      10.400970     101.780830       5.221405       8.790234       4.708213     185.603928     217.188721      56.095646
std         4.997977       4.506074       3.648484       0.705399       2.849456       4.883113       2.710749     270.036469     275.499176      79.578094
min         4.188177       2.830465       1.062628      98.610748       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.850904      13.227690       7.584381     101.312965       3.070472       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.527977      16.823058      10.269603     101.770344       4.700352       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.704360      20.142984      13.169733     102.275742       7.162395      13.000000       8.000000     323.185432     451.796791      98.708824
max        46.945694      27.415136      21.812376     104.306625      87.530281      16.000000       8.000000    1101.652588     852.301270     347.261230

==================== Sydney: ACCESS-CM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=90)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       21.320488      17.496677      11.154808     101.816383       5.228554       8.790234       4.708213     185.841629     218.342422      55.541080
std         4.964953       4.426976       3.767393       0.696691       2.860062       4.883113       2.710749     269.524689     276.110413      78.085579
min         5.248045       3.734896       1.151289      98.516724       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        17.954093      14.392255       8.353779     101.356117       3.090308       5.000000       2.000000       0.000000       0.000000       0.000000
50%        21.526236      17.866513      11.095014     101.825527       4.707845       9.000000       5.000000       0.000000       0.000000       0.000000
75%        24.654543      20.978552      13.902964     102.288500       7.158161      13.000000       8.000000     326.487144     452.755981      98.673033
max        48.417183      28.799297      23.217678     104.157372      90.019249      16.000000       8.000000    1095.306885    1069.546997     324.655182

==================== Sydney: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.117714      14.963201       9.128773     101.689278       5.410279       8.790234       4.708213     190.354874     227.539108      54.406033
std         5.173940       4.372101       3.233670       0.731629       2.913703       4.883113       2.710749     276.034668     287.322418      76.556664
min         3.176171       1.903338       1.060667      98.322319       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.524606      11.761400       6.608789     101.198738       3.198404       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.230648      15.168684       8.964342     101.725723       4.885405       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.509629      18.451557      11.482535     102.220879       7.335218      13.000000       8.000000     334.004761     471.708549      96.180450
max        47.075119      26.547829      19.862635     103.908783      87.462662      16.000000       8.000000    1126.476562     914.030151     332.526978

==================== Sydney: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.291914      15.277848       9.399771     101.713570       5.369452       8.790234       4.708213     189.823212     227.032074      54.247215
std         5.088656       4.337862       3.269940       0.725004       2.929391       4.883113       2.710749     275.308319     286.603302      76.529091
min         3.745333       2.466185       1.167731      98.450401       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.789079      12.068922       6.846718     101.234621       3.124599       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.419935      15.480121       9.200344     101.753857       4.807117       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.650032      18.744640      11.804635     102.228655       7.332992      13.000000       8.000000     334.077301     470.962448      95.741003
max        47.178764      26.572117      21.131842     103.993782      87.012451      16.000000       8.000000    1119.528564     852.550781     327.878601

==================== Sydney: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=88.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.396807      15.213413       9.293191     101.691246       5.429263       8.790234       4.708213     191.185959     230.210281      53.970039
std         5.126485       4.372625       3.308504       0.726991       2.954344       4.883113       2.710749     276.536926     290.034027      76.125710
min         3.435532       2.018834       0.997163      98.424644       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.874075      12.014529       6.703171     101.200378       3.170829       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.522035      15.397211       9.104862     101.741692       4.872571       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.723463      18.632076      11.642895     102.222290       7.374318      13.000000       8.000000     337.884682     480.377289      95.328640
max        48.166832      27.264238      20.599550     104.013733      88.245621      16.000000       8.000000    1123.171143    1182.797974     321.433655

==================== Sydney: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=83.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.217329      15.130671       9.296156     101.660057       5.372105       8.790234       4.708213     190.004044     227.349274      54.122047
std         5.181469       4.477241       3.360669       0.721320       2.918305       4.883113       2.710749     275.792572     287.199860      76.226196
min         3.036946       1.630766       1.098676      98.109329       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.586909      11.791053       6.606126     101.181717       3.156326       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.352809      15.334644       9.106777     101.699661       4.831289       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.699224      18.755609      11.794032     102.172440       7.275987      13.000000       8.000000     333.119965     471.964462      95.766869
max        46.737293      26.317486      19.798868     103.732849      83.812561      16.000000       8.000000    1123.264160     860.325684     326.809265

==================== Sydney: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=90.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.006155      15.685391       9.595683     101.675026       5.401344       8.790234       4.708213     191.686935     232.056595      53.269947
std         5.152828       4.492108       3.516504       0.719912       2.942430       4.883113       2.710749     276.575165     292.071442      74.785698
min         3.978641       2.146747       0.954897      98.524017       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.458573      12.329308       6.781769     101.191540       3.157274       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.176807      15.922946       9.412530     101.699959       4.841388       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.414578      19.332032      12.234982     102.173344       7.338324      13.000000       8.000000     340.116966     483.779739      94.462643
max        48.109615      26.886425      20.441332     103.914734      90.310150      16.000000       8.000000    1111.648193     863.663818     319.931488

==================== Sydney: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=91.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.663937      16.282770      10.006137     101.709213       5.403291       8.790234       4.708213     191.132492     231.295181      53.064636
std         5.189121       4.484310       3.619161       0.728982       2.949497       4.883113       2.710749     275.912598     290.816101      74.304855
min         4.133046       2.386762       0.993263      98.419487       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        17.148976      13.022052       7.185632     101.216612       3.188873       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.769580      16.542706       9.889427     101.734390       4.843625       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.994485      19.823594      12.627955     102.234222       7.355923      13.000000       8.000000     338.255295     482.493347      94.114832
max        49.388702      27.602318      21.558802     104.051102      91.455215      16.000000       8.000000    1122.911499     871.149658     320.626312

==================== Sydney: CESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=92.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.540508      15.686734       9.758581     101.725502       5.304538       8.790234       4.708213     189.830322     219.883270      58.706833
std         5.017054       4.354149       3.332458       0.719609       2.892479       4.883113       2.710749     275.466064     277.294373      84.120033
min         3.801133       2.394082       1.173875      98.589508       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.124955      12.557096       7.221249     101.237658       3.117773       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.786051      16.061880       9.706563     101.741791       4.772340       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.879787      19.149247      12.249147     102.231506       7.223311      13.000000       8.000000     334.054649     458.363281     101.310804
max        47.501507      26.872494      21.589632     104.092903      92.809059      16.000000       8.000000    1120.284546     826.161316     348.064117

==================== Sydney: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=91.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.908197      15.814596       9.761570     101.721481       5.349599       8.790234       4.708213     192.615982     225.173996      57.950661
std         5.149636       4.403491       3.396461       0.718099       2.920070       4.883113       2.710749     278.762329     283.410645      82.118774
min         4.164094       2.670778       1.077956      98.551910       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.326440      12.550863       7.082072     101.243471       3.129902       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.107163      16.138542       9.660593     101.737701       4.801595       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.305516      19.400516      12.379400     102.217697       7.288040      13.000000       8.000000     340.486984     470.264671     101.447676
max        47.636768      27.105522      20.519081     104.112000      91.625565      16.000000       8.000000    1127.989990     838.734924     343.591461

==================== Sydney: CESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.361099      16.211662      10.016339     101.751282       5.273812       8.790234       4.708213     192.525299     225.970459      57.638718
std         5.137598       4.343216       3.386068       0.704905       2.867348       4.883113       2.710749     278.173676     283.867065      81.931763
min         5.035273       3.061779       1.115111      98.757225       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.845528      13.028732       7.416274     101.270355       3.075109       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.531579      16.568974       9.959352     101.763184       4.757268       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.707419      19.686363      12.584187     102.231323       7.166872      13.000000       8.000000     340.069756     471.848793     100.269110
max        48.195663      26.847692      19.861799     104.151779      87.271713      16.000000       8.000000    1121.716797     838.057800     364.056213

==================== Sydney: CESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=89)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.527666      15.616561       9.680019     101.711563       5.317979       8.790234       4.708213     190.707764     220.294220      58.613857
std         5.058576       4.323177       3.279553       0.716532       2.902393       4.883113       2.710749     277.509125     277.650208      83.045074
min         4.083882       2.682654       1.189131      98.276215       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.035735      12.447060       7.138543     101.229704       3.139104       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.662057      15.937656       9.632865     101.732399       4.777626       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.896958      19.090929      12.162680     102.210600       7.236626      13.000000       8.000000     333.409424     456.693741     102.344179
max        46.956959      26.460396      19.655470     104.043182      89.023300      16.000000       8.000000    1123.313232     833.368530     340.782501

==================== Sydney: CESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=85.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.513998      16.521645      10.315649     101.761574       5.244054       8.790234       4.708213     189.862411     219.539719      58.490337
std         5.118163       4.357005       3.455128       0.699007       2.826859       4.883113       2.710749     275.460571     276.732208      83.018204
min         4.701281       3.137780       1.200222      98.594414       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        17.020225      13.387198       7.697590     101.282097       3.125405       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.760334      16.892118      10.260442     101.770363       4.743732       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.814989      20.020306      12.945639     102.237106       7.180677      13.000000       8.000000     332.646904     455.211716     102.104235
max        47.787899      26.961279      20.523703     104.077431      85.724182      16.000000       8.000000    1120.266724     822.276245     346.947235

==================== Sydney: CESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=93.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       21.613008      17.540104      11.083552     101.759109       5.222222       8.790234       4.708213     190.582764     222.903397      57.584572
std         5.115983       4.395226       3.684372       0.706850       2.858745       4.883113       2.710749     275.564941     280.328888      81.979233
min         5.761855       3.881824       1.375924      98.449547       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        18.148715      14.423283       8.311391     101.277283       3.070629       5.000000       2.000000       0.000000       0.000000       0.000000
50%        21.852095      18.016865      11.125900     101.768166       4.703750       9.000000       5.000000       0.000000       0.000000       0.000000
75%        24.936454      21.076716      13.911511     102.252525       7.122719      13.000000       8.000000     336.011223     464.951469      99.271458
max        49.646404      28.409863      22.357368     104.174103      93.153740      16.000000       8.000000    1113.697632     820.782593     346.867920

==================== Sydney: CMCC-ESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=84.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.929123      15.124840       9.400747     101.636688       5.358461       8.790234       4.708213     186.823380     215.309586      58.159920
std         5.013555       4.404200       3.325956       0.712148       2.896904       4.883113       2.710749     272.776428     273.429535      83.421021
min         3.589191       2.359976       1.005018      98.288498       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.416085      11.801286       6.764636     101.166693       3.160657       5.000000       2.000000       0.000000       0.000000       0.000000
50%        18.981780      15.240316       9.148070     101.641567       4.833875       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.355111      18.721753      11.931972     102.134438       7.271905      13.000000       8.000000     323.875053     448.289810     100.502079
max        45.789799      26.790152      20.702597     104.183884      84.653671      16.000000       8.000000    1112.688599     820.545288     355.788452

==================== Sydney: CMCC-ESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=84.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.335527      15.562555       9.698311     101.705147       5.274062       8.790234       4.708213     187.312088     215.981354      58.194122
std         4.977434       4.298174       3.299382       0.723005       2.869342       4.883113       2.710749     273.118378     273.956146      83.178795
min         4.207644       2.921588       1.018421      98.298370       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.826007      12.377424       7.168018     101.202778       3.091561       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.407920      15.676935       9.427921     101.712280       4.739037       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.713381      19.069870      12.209340     102.200165       7.140107      13.000000       8.000000     325.846878     449.861252     101.412588
max        46.373104      27.074209      21.239767     104.286758      84.736916      16.000000       8.000000    1113.052368     824.226196     372.229248

==================== Sydney: CMCC-ESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=83.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.624594      15.739512       9.795660     101.719055       5.284943       8.790234       4.708213     188.854141     220.900543      57.247387
std         5.068379       4.397848       3.421524       0.711557       2.866132       4.883113       2.710749     274.627167     279.860779      82.071243
min         3.945903       2.914213       1.108918      98.382988       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.113605      12.478009       7.100474     101.239058       3.135816       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.723716      15.879097       9.558132     101.739929       4.733404       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.019068      19.342564      12.428538     102.210976       7.181647      13.000000       8.000000     330.342010     460.261841      99.164219
max        45.489510      27.118198      20.857206     104.290596      83.625038      16.000000       8.000000    1115.001831     847.504578     345.337494

==================== Sydney: CMCC-ESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=85.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.033689      15.152339       9.366933     101.674248       5.296366       8.790234       4.708213     187.648514     217.532791      58.116119
std         5.004107       4.303105       3.250567       0.715927       2.889136       4.883113       2.710749     273.048950     275.484131      83.611008
min         3.524112       2.468710       1.168382      98.044724       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.560588      11.968376       6.848586     101.199310       3.126704       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.111929      15.289232       9.097842     101.690048       4.737297       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.367392      18.611302      11.765638     102.182919       7.217061      13.000000       8.000000     327.131142     452.918762      99.995373
max        47.917866      27.109343      21.278900     104.085777      85.215942      16.000000       8.000000    1113.789673     842.323242     363.567535

==================== Sydney: CMCC-ESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=81.5)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.724266      15.804234       9.814892     101.700729       5.342705       8.790234       4.708213     188.533951     219.717987      57.282803
std         4.968547       4.305534       3.405062       0.711556       2.895678       4.883113       2.710749     274.016052     277.599335      81.606979
min         4.105843       3.070638       1.161631      98.031342       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.267798      12.645571       7.200157     101.220541       3.159566       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.740211      15.878068       9.524804     101.718643       4.799750       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.027222      19.254099      12.355280     102.196838       7.293257      13.000000       8.000000     330.338348     458.619415     100.369783
max        46.778584      27.001812      20.924664     104.187576      81.509064      16.000000       8.000000    1108.576416     826.143066     358.510254

==================== Sydney: CMCC-ESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=84.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.628523      16.581629      10.351060     101.697327       5.288880       8.790234       4.708213     189.250839     221.911285      56.606380
std         5.028895       4.357918       3.575699       0.720312       2.890655       4.883113       2.710749     274.943298     280.589630      80.538834
min         5.175585       3.851646       1.125594      98.232506       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        17.201436      13.348420       7.569716     101.220211       3.118997       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.657661      16.745590      10.110613     101.695599       4.733291       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.963028      20.105992      13.040446     102.184273       7.204733      13.000000       8.000000     331.953079     462.180252      99.139940
max        48.266209      28.117620      22.385586     104.175720      84.170639      16.000000       8.000000    1109.348145     833.052734     346.556824

==================== Sydney: EC-Earth3, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=88.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.936621      15.096919       9.371993     101.689613       5.384719       8.790234       4.708213     186.779266     223.715637      52.892899
std         5.049321       4.478930       3.381245       0.708052       2.923968       4.883113       2.710749     272.272217     284.115051      74.267227
min         3.378666       1.973551       1.181237      98.582016       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.454794      11.795077       6.722371     101.218445       3.181322       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.107829      15.324533       9.170274     101.716667       4.833542       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.358961      18.698872      11.890340     102.188065       7.272261      13.000000       8.000000     325.810089     460.702423      94.946102
max        47.768234      26.246965      20.675367     103.976463      88.275871      16.000000       8.000000    1115.527222     859.910950     314.989868

==================== Sydney: EC-Earth3, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.328835      15.559448       9.742579     101.668404       5.340842       8.790234       4.708213     185.223969     220.998978      52.978687
std         5.146472       4.521429       3.494843       0.721700       2.899224       4.883113       2.710749     271.018707     281.521698      74.843178
min         3.711089       2.719496       1.180724      98.514183       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.709004      12.194162       7.010865     101.188599       3.137599       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.437034      15.662424       9.445029     101.686325       4.782727       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.829157      19.179044      12.277869     102.180313       7.257741      13.000000       8.000000     320.906906     457.579437      94.451593
max        49.181194      27.060980      20.889868     104.092796      87.795181      16.000000       8.000000    1118.991455     855.788269     331.920929

==================== Sydney: EC-Earth3, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.509726      15.721641       9.847037     101.679382       5.326263       8.790234       4.708213     186.791779     223.818542      52.729294
std         5.126692       4.512384       3.499398       0.705171       2.884570       4.883113       2.710749     272.226807     284.155212      73.909111
min         3.449771       2.372282       1.192584      98.617981       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.919535      12.366576       7.067320     101.219025       3.155733       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.663023      15.948097       9.634707     101.703854       4.804829       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.970335      19.369747      12.487093     102.168098       7.191445      13.000000       8.000000     325.669846     462.028305      94.709551
max        48.825176      27.039373      20.830988     104.104599      86.978722      16.000000       8.000000    1109.263550     847.993042     313.628174

==================== Sydney: EC-Earth3, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=93.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.112720      15.396474       9.620296     101.674385       5.299312       8.790234       4.708213     186.065155     221.874542      52.987278
std         4.975272       4.379049       3.360207       0.710935       2.899889       4.883113       2.710749     272.165710     282.118805      74.219078
min         3.807502       2.594921       1.155352      98.399933       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.672142      12.200071       7.061078     101.189205       3.132162       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.228555      15.582821       9.417916     101.695450       4.770561       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.481441      18.874883      12.067445     102.182648       7.219351      13.000000       8.000000     322.428345     455.470581      94.815302
max        46.559917      26.895943      20.827507     104.016632      93.222885      16.000000       8.000000    1112.775391     974.498962     306.046387

==================== Sydney: EC-Earth3, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.692139      15.887500       9.965039     101.697914       5.351826       8.790234       4.708213     185.545929     221.987381      52.838043
std         5.005174       4.536829       3.599259       0.725204       2.904271       4.883113       2.710749     270.561615     281.940369      74.441872
min         4.035218       2.652611       1.182780      98.398338       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.225445      12.522087       7.131073     101.206272       3.173666       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.908654      16.110541       9.725721     101.722534       4.807928       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.135651      19.566385      12.697520     102.213642       7.251291      13.000000       8.000000     322.932571     459.458534      94.065466
max        46.886620      26.899622      20.963251     104.160896      87.167107      16.000000       8.000000    1110.687500     843.167114     313.942596

==================== Sydney: EC-Earth3, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=87.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.807716      16.838297      10.626757     101.704872       5.345179       8.790234       4.708213     186.339905     223.874771      52.353863
std         5.170136       4.603639       3.834438       0.723902       2.918766       4.883113       2.710749     271.239166     283.753387      73.468231
min         4.944921       3.190164       1.209068      98.446037       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        17.176278      13.406569       7.624472     101.210695       3.185208       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.933461      17.019756      10.351484     101.717621       4.831306       9.000000       5.000000       0.000000       0.000000       0.000000
75%        24.280448      20.581825      13.530825     102.228245       7.266913      13.000000       8.000000     325.252365     462.960480      93.923077
max        49.632126      28.507187      23.109053     104.183784      87.814789      16.000000       8.000000    1107.629150     905.719116     323.242126

==================== Sydney: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=86.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.800968      15.165354       9.505222     101.638733       5.278774       8.790234       4.708213     185.023682     222.049744      52.551964
std         4.979561       4.459069       3.341357       0.675266       2.833854       4.883113       2.710749     269.789032     281.860260      74.490135
min         3.717178       2.219874       1.060392      98.591866       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.353674      11.790500       6.794664     101.183596       3.131682       5.000000       2.000000       0.000000       0.000000       0.000000
50%        18.975651      15.497779       9.421946     101.658691       4.765966       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.142824      18.758221      12.039080     102.098282       7.172741      13.000000       8.000000     322.048790     460.892883      92.641129
max        48.723129      26.312344      19.830263     103.910469      86.346603      16.000000       8.000000    1119.553101     833.865112     336.435364

==================== Sydney: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=89.9)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.013248      15.238118       9.511286     101.637703       5.348621       8.790234       4.708213     186.838913     226.046555      51.683933
std         5.098409       4.526505       3.404675       0.697811       2.910515       4.883113       2.710749     272.133423     286.285431      72.485374
min         3.594518       1.917333       1.085616      98.585823       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.454637      11.851770       6.774126     101.171112       3.158090       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.160409      15.551848       9.372652     101.664669       4.811962       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.425245      18.869989      12.068251     102.129343       7.226556      13.000000       8.000000     325.250549     468.306404      92.255100
max        47.894234      27.059313      20.505260     103.875679      89.880600      16.000000       8.000000    1122.617554     845.095032     298.357513

==================== Sydney: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=90.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.108044      15.219426       9.435092     101.633759       5.331556       8.790234       4.708213     187.527893     227.464859      51.362545
std         5.062359       4.428411       3.359783       0.713457       2.920602       4.883113       2.710749     273.192078     288.403442      71.922455
min         3.562294       2.262865       0.937595      98.330688       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.629237      11.919974       6.724010     101.151894       3.098436       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.229891      15.423424       9.240035     101.654373       4.767128       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.431802      18.791682      11.978355     102.118759       7.227591      13.000000       8.000000     326.257736     470.622536      92.053961
max        48.277729      27.111992      20.597551     104.084465      90.114311      16.000000       8.000000    1122.708740    1298.109497     307.637970

==================== Sydney: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=90.9)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.761782      14.943567       9.287481     101.633369       5.342993       8.790234       4.708213     186.960297     225.596573      52.026051
std         5.083378       4.523093       3.391637       0.705238       2.923303       4.883113       2.710749     272.057037     285.938568      73.095367
min         3.202562       1.780023       0.977034      98.509201       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.204835      11.517488       6.526039     101.157230       3.122800       5.000000       2.000000       0.000000       0.000000       0.000000
50%        18.924299      15.215991       9.098303     101.657719       4.801315       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.179339      18.601246      11.837374     102.122581       7.248789      13.000000       8.000000     325.406876     467.844162      92.518364
max        47.660244      26.546522      20.236208     103.898819      90.932106      16.000000       8.000000    1126.188232    1041.627197     327.148956

==================== Sydney: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=89.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.595596      15.751781       9.854509     101.647133       5.295039       8.790234       4.708213     185.535248     224.303650      51.703705
std         5.069758       4.554690       3.532724       0.687799       2.889799       4.883113       2.710749     270.525055     284.601471      73.150726
min         3.326020       1.757662       1.130082      98.485077       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.081691      12.353645       7.015036     101.192909       3.112439       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.770937      16.130127       9.784194     101.665764       4.757841       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.997038      19.406802      12.514559     102.113392       7.201995      13.000000       8.000000     323.490128     465.340897      91.738951
max        47.340946      27.326462      21.320677     103.923409      89.701202      16.000000       8.000000    1120.560913     856.232544     308.139557

==================== Sydney: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=92)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       20.102457      16.293722      10.271953     101.669876       5.267241       8.790234       4.708213     185.899094     224.716873      51.627163
std         5.084523       4.564487       3.668681       0.707881       2.883838       4.883113       2.710749     270.515411     284.775452      72.875069
min         4.206340       2.736420       1.090073      98.469398       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.594614      12.908229       7.365105     101.200851       3.089826       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.197841      16.590915      10.152946     101.682953       4.730262       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.497066      19.914279      12.935164     102.152191       7.144121      13.000000       8.000000     323.960457     464.774071      91.831743
max        47.306873      27.972420      22.275547     103.975899      91.983620      16.000000       8.000000    1118.297363     865.291687     330.441833

==================== Sydney: NorESM2-MM, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=89.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.770964      14.780960       9.101697     101.676437       5.400608       8.790234       4.708213     190.471146     219.996780      59.240273
std         5.144027       4.533021       3.372924       0.704726       2.931813       4.883113       2.710749     276.686707     278.763916      84.223007
min         2.680733       1.461457       0.921548      98.632172       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.222802      11.337113       6.345542     101.202803       3.216522       5.000000       2.000000       0.000000       0.000000       0.000000
50%        18.938886      14.939991       8.828640     101.703110       4.828617       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.149313      18.478094      11.676705     102.162979       7.300865      13.000000       8.000000     334.516129     458.909111     104.588917
max        47.599560      26.484200      19.617962     104.155510      89.578697      16.000000       8.000000    1121.199463     843.275146     369.720245

==================== Sydney: NorESM2-MM, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=85.9)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.998337      14.958503       9.205315     101.689865       5.407309       8.790234       4.708213     191.994034     222.349930      58.840584
std         5.245844       4.549572       3.387186       0.699059       2.901160       4.883113       2.710749     278.734680     280.351074      82.680534
min         3.075780       1.930065       0.842170      98.222679       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.337596      11.492787       6.446735     101.220657       3.192669       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.146090      15.158618       8.959157     101.711853       4.885696       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.463410      18.650488      11.768559     102.170267       7.310407      13.000000       8.000000     337.397690     462.117119     104.872799
max        49.006836      27.236771      20.433207     104.179733      85.861885      16.000000       8.000000    1129.616821     830.221985     334.715271

==================== Sydney: NorESM2-MM, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=91.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.933384      14.975009       9.257652     101.702888       5.369986       8.790234       4.708213     190.656662     219.939499      59.323101
std         5.195873       4.594673       3.451608       0.725308       2.925116       4.883113       2.710749     276.725128     277.835541      83.909325
min         2.893104       1.379741       0.905242      98.316414       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.331696      11.526440       6.470384     101.223892       3.144147       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.183824      15.163142       8.989871     101.729794       4.816314       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.378675      18.702081      11.858664     102.194290       7.295188      13.000000       8.000000     333.800201     460.260605     104.921740
max        47.358322      26.795704      20.282049     104.155113      91.229660      16.000000       8.000000    1133.140259     819.422119     339.951935

==================== Sydney: NorESM2-MM, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=90.9)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       18.523354      14.676729       9.092067     101.651733       5.370701       8.790234       4.708213     188.422745     215.173996      59.879684
std         5.103961       4.526633       3.351208       0.725713       2.927713       4.883113       2.710749     274.456268     272.893738      85.260475
min         3.007292       1.667899       0.968783      98.415749       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        14.963457      11.271855       6.374601     101.155251       3.149055       5.000000       2.000000       0.000000       0.000000       0.000000
50%        18.642909      14.830626       8.843745     101.674362       4.807262       9.000000       5.000000       0.000000       0.000000       0.000000
75%        21.989662      18.339576      11.611631     102.158649       7.277544      13.000000       8.000000     329.894943     446.433853     105.029861
max        47.859745      26.785572      20.296682     104.010086      90.894279      16.000000       8.000000    1123.796021     808.591125     372.884216

==================== Sydney: NorESM2-MM, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=83.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.393860      15.389584       9.529109     101.717720       5.312337       8.790234       4.708213     189.813889     219.535156      59.015137
std         5.183980       4.596050       3.512263       0.710977       2.877304       4.883113       2.710749     275.624451     277.890167      83.941505
min         3.344633       1.965032       1.002830      98.729424       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        15.854742      11.889095       6.665365     101.241888       3.118707       5.000000       2.000000       0.000000       0.000000       0.000000
50%        19.636237      15.733582       9.345748     101.731232       4.778315       9.000000       5.000000       0.000000       0.000000       0.000000
75%        22.750093      19.096116      12.203608     102.213982       7.215644      13.000000       8.000000     333.052643     458.231560     103.102039
max        48.562614      27.148521      20.826513     104.017967      83.335602      16.000000       8.000000    1121.113525     819.049805     359.027405

==================== Sydney: NorESM2-MM, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=82.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       19.999115      16.088320      10.061976     101.763756       5.286878       8.790234       4.708213     188.246948     215.873856      59.495155
std         5.136320       4.553900       3.581531       0.726449       2.857944       4.883113       2.710749     273.610565     273.596619      84.549782
min         3.560622       2.241216       1.049449      98.270203       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        16.490033      12.694622       7.203699     101.289902       3.104640       5.000000       2.000000       0.000000       0.000000       0.000000
50%        20.248775      16.510550       9.990279     101.783882       4.754998       9.000000       5.000000       0.000000       0.000000       0.000000
75%        23.385255      19.741238      12.789201     102.277208       7.218602      13.000000       8.000000     329.770927     448.833176     103.640825
max        47.508217      27.678799      22.023497     104.237320      82.115776      16.000000       8.000000    1115.096069     814.281982     368.808624

                                                  file     loc       model     ssp time_period  flagged                                     flag_reason   n_min  any_nan  any_const
84   Cairns_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM_B...  Cairns  ACCESS-CM2  ssp126   2021-2040     True  rsds out of range [0.0, 1300.0] (max=1.47e+03)  175200    False      False
85   Cairns_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM_B...  Cairns  ACCESS-CM2  ssp126   2041-2060     True  rsds out of range [0.0, 1300.0] (max=1.47e+03)  175200    False      False
86   Cairns_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM_B...  Cairns  ACCESS-CM2  ssp126   2061-2080     True  rsds out of range [0.0, 1300.0] (max=1.47e+03)  175200    False      False
87   Cairns_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BOM_B...  Cairns  ACCESS-CM2  ssp370   2021-2040     True  rsds out of range [0.0, 1300.0] (max=1.47e+03)  175200    False      False
88   Cairns_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BOM_B...  Cairns  ACCESS-CM2  ssp370   2041-2060     True  rsds out of range [0.0, 1300.0] (max=1.47e+03)  175200    False      False
..                                                 ...     ...         ...     ...         ...      ...                                             ...     ...      ...        ...
415  Perth_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BOM_BA...   Perth  NorESM2-MM  ssp126   2041-2060    False                                                  175200    False      False
416  Perth_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BOM_BA...   Perth  NorESM2-MM  ssp126   2061-2080    False                                                  175200    False      False
417  Perth_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_BA...   Perth  NorESM2-MM  ssp370   2021-2040    False                                                  175200    False      False
418  Perth_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_BA...   Perth  NorESM2-MM  ssp370   2041-2060    False                                                  175200    False      False
419  Perth_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_BA...   Perth  NorESM2-MM  ssp370   2061-2080    False                                                  175200    False      False

[462 rows x 10 columns]

In [39]:
qc_rows

[]

# Check NatHERS

In [18]:
show_only_if_flagged = False

#==========================================
nathers_dir = "/g/data/eg3/spr548/projects/nesp_bff/data/raw_data/NatHERS/historical/"
# location = "Sydney"
vars_to_summarise_nathers = ["tas","huss","psl","sfcWind","wind_dir","clt","rsds","rsdsdir","rsdsdif"]
locations = ["Darwin","Cairns","Brisbane","Longreach","Mildura","Adelaide","Perth","Sydney","Melbourne","Canberra","Hobart"]
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]

In [19]:
files = glob.glob(f"{nathers_dir}*.nc")
len(files)

11

In [22]:
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]
RANGES_NATHERS = {
   # temps: keep the K→C heuristic because files might still be in K
   "tas":  {"min": -60, "max":  60, "units": "C_or_K"},
   "twbt": {"min": -60, "max":  60, "units": "C_or_K"},
   # specific humidity (kg/kg)
   "huss": {"min": 0.0, "max": 0.04, "units": "kg/kg"},
   # sea level pressure in kPa (typical ~ 90–110 kPa; give generous bounds)
   "psl":  {"min": 80000, "max": 110000, "units": "Pa"},
   # wind speed (m/s)
   "sfcWind": {"min": 0.0, "max": 60.0, "units": "m/s"},
   # 16-point direction code (0..16). If you treat 0 as calm, keep it allowed.
   "wind_dir": {"min": 0.0, "max": 16.0, "units": "dir16"},
   # cloud cover in fraction classes (0..100)
   "clt": {"min": 0.0, "max": 100.0, "units": "%"},
   # radiation (W/m²)
   "rsds":    {"min": 0.0, "max": 1300.0, "units": "W/m2"},
   "rsdsdir": {"min": 0.0, "max": 1300.0, "units": "W/m2"},
   "rsdsdif": {"min": 0.0, "max": 1300.0, "units": "W/m2"},
}

def _convert_for_check(var, vmin, vmax):
    rule = RANGES_NATHERS.get(var)
    if rule is None:
        return vmin, vmax, None, None, None
    rmin, rmax = rule["min"], rule["max"]
    note = None
    # Temperature heuristic: if values look like Kelvin, convert to Celsius for checking
    if var in ("tas", "twbt"):
        if np.isfinite(vmax) and vmax > 150:  # likely Kelvin
            vmin = vmin - 273.15
            vmax = vmax - 273.15
            note = "converted K→C (heuristic)"
    return vmin, vmax, rmin, rmax, note

def flag_df(df, desc, vars_to_check):
   reasons = []
   # NaN + constant checks (overall)
   if df[vars_to_check].isna().any().any():
       reasons.append("has NaNs")
   if (df[vars_to_check].nunique(dropna=True) <= 1).any():
       const_vars = list(df[vars_to_check].columns[(df[vars_to_check].nunique(dropna=True) <= 1)])
       reasons.append(f"constant: {const_vars[:5]}" + ("..." if len(const_vars) > 5 else ""))
   # Range checks per variable
   for v in vars_to_check:
       if v not in desc.columns:
           reasons.append(f"missing column: {v}")
           continue
       vmin = desc.loc["min", v]
       vmax = desc.loc["max", v]
       vmin2, vmax2, rmin, rmax, note = _convert_for_check(v, vmin, vmax)
       if rmin is None:
           continue
       out_low = np.isfinite(vmin2) and (vmin2 < rmin)
       out_high = np.isfinite(vmax2) and (vmax2 > rmax)
       if out_low or out_high:
           msg = f"{v} out of range [{rmin}, {rmax}]"
           if out_low:
               msg += f" (min={vmin2:.3g})"
           if out_high:
               msg += f" (max={vmax2:.3g})"
           if note:
               msg += f" [{note}]"
           reasons.append(msg)
   return reasons

qc_rows, errors = [], []
for file in sorted(files):
   base = file.split("/")[-1]
   parts = base.split("_")
   loc = parts[0] if len(parts) > 0 else None
   model_ = parts[2] if len(parts) > 2 else None
   ssp = parts[3] if len(parts) > 3 else None
   time_period_ = parts[9] if len(parts) > 9 else None
   header = f"{loc}: {model_}, {ssp}, {time_period_}"
   print(f"==================== {header} ====================")
   try:
       with xr.open_dataset(file) as da:
           df = (
               da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
                 [vars_to_summarise_nathers]
                 .to_dataframe()
           )
       desc = df.describe()
       reasons = flag_df(df, desc, vars_to_summarise_nathers)
       flagged = len(reasons) > 0
       if (not show_only_if_flagged) or flagged:
           print("⚠️ Flagged" if flagged else "OK")
           if flagged:
               print("Reasons:", "; ".join(reasons[:6]) + (" ..." if len(reasons) > 6 else ""))
           display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
           display(desc)
           display(HTML("</div>"))
       qc_rows.append({
           "file": base,
           "loc": loc,
           "model": model_,
           "ssp": ssp,
           "time_period": time_period_,
           "flagged": flagged,
           "flag_reason": "; ".join(reasons[:8]) + (" ..." if len(reasons) > 8 else ""),
           "n_min": int(desc.loc["count"].min()),
           "any_nan": bool(df.isna().any().any()),
           "any_const": bool((df.nunique(dropna=True) <= 1).any()),
       })
   except Exception as e:
       errors.append({
           "file": base,
           "loc": loc,
           "model": model_,
           "ssp": ssp,
           "time_period": time_period_,
           "error": repr(e),
       })
qc_df = pd.DataFrame(qc_rows)
err_df = pd.DataFrame(errors)
# display(qc_df.sort_values(["flagged", "loc", "model"], ascending=[False, True, True]))
if not err_df.empty:
   display(err_df)

==================== Adelaide: AD, NatHERS, None ====================
⚠️ Flagged
Reasons: clt out of range [0.0, 100.0] (max=112)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      290.235447       0.006868  101141.887374       3.095014       7.551807      47.187138     195.122306     200.690435      67.456534
std         6.360441       0.001892     690.444434       1.949950       5.005412      33.541743     287.828158     332.992905     104.313754
min       273.760000       0.000400   97700.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       285.760000       0.005600  100700.000000       1.600000       3.000000      12.500000       0.000000       0.000000       0.000000
50%       289.160000       0.006600  101100.000000       3.100000       8.000000      50.000000       0.000000       0.000000       0.000000
75%       293.860000       0.007900  101600.000000       4.300000      11.000000      75.000000     331.000000     274.000000      97.000000
max       318.260000       0.020200  103300.000000      39.700000      16.000000     112.500000    1133.000000     996.000000     733.000000

==================== Brisbane: BR, NatHERS, None ====================
OK

                 tas           huss            psl       sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.00000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      293.397539       0.010743  101530.786208       3.21166       5.965306      49.725652     214.592447     227.532435      69.152046
std         5.062948       0.003374     541.671168       2.48058       5.113696      30.958146     302.448910     340.985109     107.799817
min       274.760000       0.001000   99100.000000       0.00000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       290.060000       0.008400  101200.000000       0.00000       0.000000      25.000000       0.000000       0.000000       0.000000
50%       293.960000       0.010700  101500.000000       3.10000       6.000000      50.000000       0.000000       0.000000       0.000000
75%       297.160000       0.013100  101900.000000       4.70000      10.000000      75.000000     395.000000     458.250000      99.000000
max       312.160000       0.023500  103300.000000      18.10000      16.000000     100.000000    1138.000000     998.000000     708.000000

==================== Cairns: CN, NatHERS, None ====================
⚠️ Flagged
Reasons: sfcWind out of range [0.0, 60.0] (max=97.8); clt out of range [0.0, 100.0] (max=112); rsds out of range [0.0, 1300.0] (max=1.47e+03)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      297.630034       0.014386  101188.709720       4.223242       6.487868      47.582590     217.733449     190.491624      87.975051
std         3.648949       0.003216     429.762044       2.417271       3.546017      30.915563     304.414772     306.509250     129.324208
min       281.960000       0.000700   98300.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       295.160000       0.012100  100900.000000       2.500000       5.000000      12.500000       0.000000       0.000000       0.000000
50%       297.860000       0.014500  101200.000000       4.200000       7.000000      37.500000       0.000000       0.000000       0.000000
75%       300.160000       0.016800  101500.000000       5.800000       8.000000      75.000000     403.000000     296.000000     133.000000
max       313.160000       0.025700  102400.000000      97.800000      16.000000     112.500000    1470.000000    1057.000000     735.000000

==================== Canberra: CA, NatHERS, None ====================
⚠️ Flagged
Reasons: sfcWind out of range [0.0, 60.0] (max=66.9); clt out of range [0.0, 100.0] (max=112)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      286.384890       0.006771   94887.085791       3.061769       7.514927      48.948900     193.211751     206.277744      66.319257
std         7.391301       0.002444     654.577246       2.706059       5.908184      31.707146     283.106853     331.986165     103.201032
min       265.160000       0.000700   83800.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       281.160000       0.004900   94500.000000       0.600000       1.000000      12.500000       0.000000       0.000000       0.000000
50%       286.160000       0.006300   94900.000000       2.500000       7.000000      50.000000       0.000000       0.000000       0.000000
75%       291.160000       0.008300   95300.000000       4.700000      14.000000      75.000000     338.000000     315.000000      94.000000
max       313.260000       0.018800   97000.000000      66.900000      16.000000     112.500000    1147.000000     996.000000     747.000000

==================== Darwin: DA, NatHERS, None ====================
OK

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      300.312559       0.015880  100611.297739       3.613253       8.330104      50.062581     231.277788     217.213590      81.892929
std         3.467332       0.004246     334.819961       2.041443       5.128771      28.932356     314.790270     314.141902     119.199053
min       276.460000       0.001400   98500.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       298.160000       0.013500  100400.000000       2.200000       4.000000      25.000000       0.000000       0.000000       0.000000
50%       300.460000       0.017000  100600.000000       3.600000       8.000000      50.000000       6.000000       0.000000       5.000000
75%       302.860000       0.019100  100900.000000       4.700000      13.000000      75.000000     466.000000     446.000000     126.000000
max       310.560000       0.027200  101900.000000      59.700000      16.000000     100.000000    1185.000000    1012.000000     744.000000

==================== Hobart: HO, NatHERS, None ====================
OK

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      285.767041       0.006024  100758.519377       4.294047      10.846615      56.226251     155.922810     144.149607      73.403301
std         4.803931       0.001704     923.897153       2.439805       4.618949      31.646616     238.182315     271.171031     110.997231
min       272.160000       0.001300   96100.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       282.360000       0.004800  100200.000000       2.500000       8.000000      25.000000       0.000000       0.000000       0.000000
50%       285.460000       0.005700  100800.000000       4.200000      12.000000      62.500000       0.000000       0.000000       0.000000
75%       288.760000       0.007000  101400.000000       5.800000      15.000000      87.500000     254.000000     123.000000     113.000000
max       314.060000       0.016400  103400.000000      20.000000      16.000000     100.000000    1083.000000     994.000000     732.000000

==================== Longreach: LO, NatHERS, None ====================
⚠️ Flagged
Reasons: clt out of range [0.0, 100.0] (max=112)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      296.780653       0.007817   99134.541298       3.464635       4.821341      35.841407     240.939760     273.253888      60.832188
std         7.799288       0.004132     517.056235       2.455036       4.246768      32.451944     328.854756     369.995124      96.366009
min       272.760000       0.000100   96900.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       291.560000       0.004400   98800.000000       1.400000       1.000000      12.500000       0.000000       0.000000       0.000000
50%       297.160000       0.007100   99100.000000       3.600000       4.000000      25.000000       0.000000       0.000000       0.000000
75%       302.360000       0.010600   99500.000000       5.000000       7.000000      62.500000     484.000000     652.000000      90.000000
max       318.660000       0.025100  100800.000000      16.900000      16.000000     112.500000    1217.000000    1080.000000     708.000000

==================== Melbourne: TU, NatHERS, None ====================
⚠️ Flagged
Reasons: sfcWind out of range [0.0, 60.0] (max=62.2)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      287.479500       0.006850  100275.938992       5.015985      10.841666      57.482975     172.196126     166.280285      73.501865
std         5.941164       0.001958     745.317907       3.053792       4.733737      29.843818     261.858218     294.744649     109.128367
min       272.160000       0.001000   96700.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       283.160000       0.005500   99800.000000       2.500000       8.000000      25.000000       0.000000       0.000000       0.000000
50%       286.460000       0.006500  100300.000000       4.700000      11.000000      62.500000       2.000000       0.000000       2.000000
75%       290.560000       0.007800  100800.000000       6.700000      16.000000      87.500000     279.000000     189.000000     113.000000
max       318.960000       0.019300  102600.000000      62.200000      16.000000     100.000000    1162.000000    1074.000000     692.000000

==================== Mildura: MI, NatHERS, None ====================
⚠️ Flagged
Reasons: sfcWind out of range [0.0, 60.0] (max=67.8)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      290.392557       0.006154  101096.453770       3.376092       7.814523      51.602758     211.120551     243.133082      61.173283
std         7.876479       0.002137     680.405195       2.048971       4.777829      32.435900     302.029779     355.681053      95.304209
min       269.760000       0.000100   97900.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       284.560000       0.004700  100600.000000       2.200000       4.000000      25.000000       0.000000       0.000000       0.000000
50%       289.560000       0.005800  101100.000000       3.100000       8.000000      50.000000       1.000000       0.000000       1.000000
75%       295.460000       0.007100  101600.000000       4.700000      11.000000      87.500000     381.000000     512.000000      87.000000
max       319.260000       0.020700  103300.000000      67.800000      16.000000     100.000000    1212.000000    1092.000000     669.000000

==================== Perth: PE, NatHERS, None ====================
OK

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      291.444065       0.007744  101410.508811       4.048331       6.586098      39.159306     212.210264     234.947737      62.874991
std         6.581836       0.002227     604.293313       2.688214       4.748247      33.615397     305.001587     352.114248      97.628902
min       272.160000       0.001300   99000.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       286.860000       0.006100  101000.000000       2.200000       3.000000      12.500000       0.000000       0.000000       0.000000
50%       290.860000       0.007500  101400.000000       3.600000       6.000000      25.000000       0.000000       0.000000       0.000000
75%       295.360000       0.009100  101800.000000       5.800000      10.000000      75.000000     380.000000     460.000000      92.000000
max       319.160000       0.022400  103600.000000      18.100000      16.000000     100.000000    1149.000000     997.000000     684.000000

==================== Sydney: MA, NatHERS, None ====================
⚠️ Flagged
Reasons: sfcWind out of range [0.0, 60.0] (max=87.5); clt out of range [0.0, 100.0] (max=112)

                 tas           huss            psl        sfcWind       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000  227904.000000
mean      291.389073       0.008956  101635.820345       4.425809       7.264857      48.550706     186.517051     191.603719      69.822377
std         4.994831       0.003165     707.614930       3.331891       5.548381      33.913310     274.045984     317.734324     107.536489
min       276.160000       0.001000   98500.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%       288.060000       0.006500  101200.000000       2.200000       1.000000      12.500000       0.000000       0.000000       0.000000
50%       291.460000       0.008700  101700.000000       4.200000       8.000000      50.000000       0.000000       0.000000       0.000000
75%       294.760000       0.011300  102100.000000       6.700000      12.000000      87.500000     323.000000     273.000000     100.000000
max       318.660000       0.020000  103900.000000      87.500000      16.000000     112.500000    1125.000000     997.000000     700.000000