# Checking output files

In [3]:
from datetime import datetime, timedelta
import calendar
import collections
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
import sys

import glob
import pandas as pd
import xarray as xr
from IPython.display import display, HTML

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)


my_dir = "/g/data/eg3/spr548/projects/"
sys.path.append(os.path.join(my_dir, "nesp_bff")+os.sep)
from nathers import location_details

# import utils
# from utils import locations, model_dict, vars_1hr, vars_day

In [7]:
step = "step3"
show_only_if_flagged = True

#==========================================
root_dir = "/g/data/eg3/nesp_bff/"
# location = "Sydney"
# scenario = "ssp370"
# model = "CESM2"
# time_period = "2041-2060"
vars_to_summarise_step2 = ["tas","huss","sfcWind","psl","uas","vas","clt","rsds","rsdsdir","rsdsdif"]
vars_to_summarise_step3 = ["tas","twbt","huss","psl","wind_speed","wind_dir","total_cloud_cover","rsds","rsdsdir","rsdsdif"]
locations = ["Darwin","Cairns","Brisbane","Longreach","Mildura","Adelaide","Perth","Sydney","Melbourne","Canberra","Hobart"]
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]

input_dir = f"{root_dir}step3_calc_missing_vars/" if step == "step3" else f"{root_dir}step2_qdc_scaling/BARPA-R/"
vars_to_summarise = vars_to_summarise_step3 if step == "step3" else vars_to_summarise_step2

In [8]:
files = glob.glob(f"{input_dir}*.nc")
len(files)

462

In [9]:
qc_rows = []
errors = []

for file in sorted(files):
    base = file.split("/")[-1]
    parts = base.split("_")

    loc = parts[0] if len(parts) > 0 else None
    model_ = parts[2] if len(parts) > 2 else None
    ssp = parts[3] if len(parts) > 3 else None
    time_period_ = parts[9] if len(parts) > 9 else None

    header = f"{loc}: {model_}, {ssp}, {time_period_}"
    print(f"==================== {header} ====================")

    try:
        with xr.open_dataset(file) as da:
            df = (
                da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
                  [vars_to_summarise]
                  .to_dataframe()
            )

        desc = df.describe()

        flagged = df.isna().any().any() or (df.nunique(dropna=True) <= 1).any()

        if (not show_only_if_flagged) or flagged:
            print("⚠️ Flagged" if flagged else "OK")
            display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
            display(desc)
            display(HTML("</div>"))

        qc_rows.append({
            "file": base,
            "loc": loc,
            "model": model_,
            "ssp": ssp,
            "time_period": time_period_,
            "n_min": int(desc.loc["count"].min()),
            "any_nan": bool(df.isna().any().any()),
            "any_const": bool((df.nunique(dropna=True) <= 1).any()),
            "rsds_min": float(desc.loc["min", "rsds"]) if "rsds" in desc.columns else None,
            "rsds_max": float(desc.loc["max", "rsds"]) if "rsds" in desc.columns else None,
        })

    except Exception as e:
        errors.append({
            "file": base,
            "loc": loc,
            "model": model_,
            "ssp": ssp,
            "time_period": time_period_,
            "error": repr(e),
        })

qc_df = pd.DataFrame(qc_rows)
err_df = pd.DataFrame(errors)

print("\n=== QC summary (all files) ===")
display(qc_df)

if not err_df.empty:
    print("\n=== Errors ===")
    display(err_df)

==================== Adelaide: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Adelaide: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       18.224072      12.929590       7.277942     101.227280       3.017486       7.487785           3.873362     202.196320     218.943024      64.824539
std         6.816612       3.682003       2.185331       0.728413       1.932686       4.646043           3.159390     293.196198     345.765442     100.089554
min         1.497444       0.693034       0.392788      97.528481       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        13.391983      10.324612       5.793806     100.749371       1.430837       4.000000           0.000000       0.000000       0.000000       0.000000
50%        16.970230      12.697818       7.048119     101.208359       2.935286       7.000000           4.000000       0.000000       0.000000       0.000000
75%        22.168592      15.318844       8.448796     101.695820       4.358454      11.000000           7.000000     345.881592     382.683289      92.500240
max        46.586071      28.978638      21.822971     103.618294      13.799576      16.000000           9.000000    1113.045410    1296.002319     723.055786

==================== Adelaide: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175197.000000  175197.000000  175200.000000
mean       17.960510      12.628146       7.048107     101.196266       3.095285       7.617768           3.604355     201.684570     219.847733      64.121094
std         6.701255       3.438688       1.944658       0.715963       1.951415       4.674092           3.142279     292.196564     345.416138      97.803108
min         1.636778       0.822517       0.315108      97.727646       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        13.210593      10.201679       5.740314     100.711750       1.512857       4.000000           0.000000       0.000000       0.000000       0.000000
50%        16.638847      12.364718       6.849160     101.194939       3.056092       8.000000           3.000000       0.000000       0.000000       0.000000
75%        21.654992      14.855695       8.146292     101.690510       4.479830      11.000000           7.000000     341.344330     386.854431      92.647224
max        46.816719      27.362404      19.093647     103.256668      14.285907      16.000000           9.000000    1108.401978    1296.081299     721.370239

==================== Adelaide: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       17.792776      12.599466       7.113799     101.162956       3.065931       7.647603           3.727745     200.596481     214.229675      65.994339
std         6.708610       3.596795       2.087996       0.733833       1.940050       4.668462           3.162042     290.422485     340.635223     101.075096
min         1.876732       0.872281       0.368703      97.757515       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        12.994435      10.031316       5.703965     100.656271       1.513911       4.000000           0.000000       0.000000       0.000000       0.000000
50%        16.498283      12.292150       6.864150     101.153889       3.006999       8.000000           3.000000       0.000000       0.000000       0.000000
75%        21.511269      14.914911       8.225477     101.668205       4.396422      11.000000           7.000000     341.935638     363.088989      95.347128
max        46.044228      28.555279      21.655827     103.452171      14.596431      16.000000           9.000000    1119.023560    1251.932739     725.034546

==================== Adelaide: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Adelaide: CESM2, ssp126, 2021-2040 ====================
==================== Adelaide: CESM2, ssp126, 2041-2060 ====================
==================== Adelaide: CESM2, ssp126, 2061-2080 ====================
==================== Adelaide: CESM2, ssp370, 2021-2040 ====================
==================== Adelaide: CESM2, ssp370, 2041-2060 ====================
==================== Adelaide: CESM2, ssp370, 2061-2080 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Adelaide: EC-Earth3, ssp126, 2021-2040 ====================
==================== Adelaide: EC-Earth3, ssp126, 2041-2060 ====================
==================== Adelaide: EC-Earth3, ssp126, 2061-2080 ====================
==================== Adelaide: EC-Earth3, ssp370, 2021-2040 ====================
==================== Adelaide: EC-Earth3, ssp370, 2041-2060 ====================
==================== Adelaide: EC-Earth3, ssp370, 2061-2080 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175196.000000  175196.000000  175200.000000
mean       21.491701      18.181116      11.953569     101.599167       3.970654       6.985228           3.353037     217.436264     234.967056      69.252708
std         4.967919       4.405015       3.691981       0.540449       2.156758       4.687046           3.052678     300.929382     347.139160     106.485909
min         2.571559       0.343329       1.021642      98.978935       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        18.254986      15.369861       9.414450     101.229195       2.521057       3.000000           0.000000       0.000000       0.000000       0.000000
50%        22.147840      18.778860      11.953080     101.588848       3.745500       6.000000           3.000000       0.000000       0.000000       0.000000
75%        25.243060      21.591045      14.679772     101.961849       5.026662      10.000000           6.000000     400.963501     501.565216      99.311502
max        39.683266      29.604212      24.461315     103.433472      19.488085      16.000000           9.000000    1123.558960    1295.044067     696.827942

==================== Brisbane: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175198.000000  175198.000000  175200.000000
mean       21.197327      17.506487      11.254363     101.612076       3.995648       6.784726           3.048682     220.086411     242.965576      67.300636
std         5.124981       4.471380       3.640119       0.549213       2.189760       4.684642           2.979022     304.884918     355.722900     103.686264
min         2.465086      -0.310084       0.932599      99.022362       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        17.856015      14.711254       8.834147     101.240828       2.551210       3.000000           0.000000       0.000000       0.000000       0.000000
50%        21.777074      18.034450      11.221076     101.606453       3.780998       6.000000           2.000000       0.000000       0.000000       0.000000
75%        24.976593      20.831705      13.757590     101.998207       5.116034      10.000000           6.000000     403.839081     523.937439      96.075619
max        40.625137      29.775864      24.385191     103.533623      17.725622      16.000000           9.000000    1123.209717    1287.992310     705.562988

==================== Brisbane: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Brisbane: CESM2, ssp126, 2021-2040 ====================
==================== Brisbane: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175166.000000  175200.000000  175166.000000
mean       21.719654      18.181595      11.860492     101.623291       3.967903       6.967038           2.931210     220.484070     243.629456      66.631935
std         5.027442       4.435968       3.714687       0.539890       2.172284       4.566542           2.964021     306.344940     357.371552     102.299034
min         2.561835       0.759107       1.043361      99.174469       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        18.551569      15.373954       9.388383     101.251183       2.500135       3.000000           0.000000       0.000000       0.000000       0.000000
50%        22.380579      18.901587      12.015212     101.625168       3.720571       7.000000           2.000000       0.000000       0.000000       0.000000
75%        25.380575      21.505472      14.490440     102.013603       5.051512      10.000000           6.000000     402.313995     525.972839      95.578880
max        40.065311      29.838207      25.373165     103.532249      17.683781      16.000000           8.000000    1121.531860    1296.729492     697.811401

==================== Brisbane: CESM2, ssp126, 2061-2080 ====================
==================== Brisbane: CESM2, ssp370, 2021-2040 ====================
==================== Brisbane: CESM2, ssp370, 2041-2060 ====================
==================== Brisbane: CESM2, ssp370, 2061-2080 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Brisbane: EC-Earth3, ssp126, 2021-2040 ====================
==================== Brisbane: EC-Earth3, ssp126, 2041-2060 ====================
==================== Brisbane: EC-Earth3, ssp126, 2061-2080 ====================
==================== Brisbane: EC-Earth3, ssp370, 2021-2040 ====================
==================== Brisbane: EC-Earth3, ssp370, 2041-2060 ====================
==================== Brisbane: EC-Earth3, ssp370, 2061-2080 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Cairns: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Cairns: ACCESS-CM2, ssp126, 2041-2060 ====================
==================== Cairns: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Cairns: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Cairns: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Cairns: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Cairns: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Cairns: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Cairns: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Cairns: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       25.302654      21.846779      15.116198     101.206841       4.479402       6.489589           4.185046     219.438324     192.371399      89.229805
std         3.645171       3.232188       3.448615       0.451477       2.312768       3.092036           2.899275     303.241974     309.923706     130.381195
min         9.534373       6.780306       3.020612      97.550354       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        22.985404      19.723068      12.645072     100.915924       3.105923       6.000000           2.000000       0.000000       0.000000       0.000000
50%        25.536236      22.209816      15.142866     101.262825       4.543682       6.000000           4.000000       0.000000       0.000000       0.000000
75%        27.743870      24.386434      17.824864     101.535416       5.969808       7.000000           7.000000     404.797974     306.312469     135.645683
max        40.857452      30.672777      26.239414     102.480606      21.414095      16.000000           9.000000    1505.238281    1294.881348     749.130371

==================== Cairns: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Cairns: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Cairns: CESM2, ssp126, 2021-2040 ====================
==================== Cairns: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175197.000000  175200.000000  175197.000000
mean       25.619524      22.109140      15.378513     101.282646       4.366276       6.500559           3.812540     218.996353     196.977097      85.765289
std         3.879667       3.408809       3.635885       0.421327       2.265199       3.302622           2.987655     303.756531     316.499023     124.160629
min         9.202436       6.935059       2.460359      98.281456       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        23.264929      19.865437      12.734338     100.982086       3.036081       5.000000           1.000000       0.000000       0.000000       0.000000
50%        25.893727      22.661706      15.649978     101.324799       4.435918       6.000000           3.000000       0.000000       0.000000       0.000000
75%        28.148590      24.789427      18.260532     101.603273       5.752649       7.000000           7.000000     399.363068     314.596695     130.488846
max        40.896164      30.861673      26.972668     102.576042      23.125046      16.000000           8.000000    1454.032593    1249.699585     736.871887

==================== Cairns: CESM2, ssp126, 2061-2080 ====================
==================== Cairns: CESM2, ssp370, 2021-2040 ====================
==================== Cairns: CESM2, ssp370, 2041-2060 ====================
==================== Cairns: CESM2, ssp370, 2061-2080 ====================
==================== Cairns: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Cairns: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Cairns: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Cairns: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Cairns: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Cairns: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Cairns: EC-Earth3, ssp126, 2021-2040 ====================
==================== Cairns: EC-Earth3, ssp126, 2041-2060 ====================
==================== Cairns: EC-Earth3, ssp126, 2061-2080 ====================
==================== Cairns: EC-Earth3, ssp370, 2021-2040 ====================
==================== Cairns: EC-Earth3, ssp370, 2041-2060 ====================
==================== Cairns: EC-Earth3, ssp370, 2061-2080 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Cairns: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Cairns: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Cairns: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Cairns: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Cairns: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Cairns: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Canberra: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Canberra: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175198.000000  175198.000000  175200.000000
mean       14.635444      10.767797       7.414339      94.984245       3.198728       8.118545           4.126513     200.006943     225.167252      64.677612
std         7.726335       5.425263       2.841205       0.643271       2.554190       5.534085           3.198665     285.959076     345.702057     100.326096
min        -7.213067      -7.520553       0.718678      83.775261       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%         9.213961       6.903190       5.172075      94.561007       1.253104       4.000000           1.000000       0.000000       0.000000       0.000000
50%        14.470340      10.941931       6.823960      94.996258       2.558644       7.000000           4.000000       0.000000       0.000000       0.000000
75%        19.716887      15.064637       9.369803      95.417130       4.778659      14.000000           8.000000     355.061371     420.854431      90.869400
max        42.455204      25.817459      20.705618      97.158119      26.831976      16.000000           9.000000    1142.617188    1283.469604     744.279785

==================== Canberra: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175197.000000  175197.000000  175200.000000
mean       14.332050      10.149666       6.876747      94.929428       3.325162       8.238642           3.736027     199.803833     227.353821      62.827244
std         7.797479       5.111996       2.507792       0.672233       2.692190       5.595875           3.205991     287.190308     348.154388      97.062164
min        -6.820395      -7.218543       0.596527      83.839882       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%         8.823238       6.544158       4.976848      94.485252       1.336357       4.000000           0.000000       0.000000       0.000000       0.000000
50%        13.886065      10.199945       6.340114      94.954571       2.604708       7.000000           3.000000       0.000000       0.000000       0.000000
75%        19.276005      14.075585       8.438473      95.406654       4.952218      14.000000           7.000000     349.547668     424.432648      88.848352
max        42.175648      25.628656      19.926565      97.129356      29.657646      16.000000           9.000000    1128.128052    1298.053467     730.614136

==================== Canberra: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Canberra: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Canberra: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Canberra: CESM2, ssp126, 2021-2040 ====================
==================== Canberra: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175171.000000  175200.000000  175171.000000
mean       14.875294      10.694003       7.204521      94.963745       3.241022       7.994018           4.053116     203.064209     235.277695      61.696392
std         7.855166       5.214343       2.648180       0.663261       2.618984       5.514355           3.197500     291.512848     355.736633      94.991577
min        -7.361791      -7.412772       0.634586      83.891373       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%         9.360259       7.023243       5.141215      94.519035       1.244957       4.000000           1.000000       0.000000       0.000000       0.000000
50%        14.532932      10.884524       6.680359      94.963997       2.580834       7.000000           4.000000       0.000000       0.000000       0.000000
75%        19.844457      14.772361       8.949808      95.419189       4.828519      14.000000           8.000000     354.490936     455.898666      86.425858
max        41.653790      25.781862      20.180042      97.309280      29.797729      16.000000           8.000000    1123.450684    1297.522949     727.817261

==================== Canberra: CESM2, ssp126, 2061-2080 ====================
==================== Canberra: CESM2, ssp370, 2021-2040 ====================
==================== Canberra: CESM2, ssp370, 2041-2060 ====================
==================== Canberra: CESM2, ssp370, 2061-2080 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Canberra: EC-Earth3, ssp126, 2021-2040 ====================
==================== Canberra: EC-Earth3, ssp126, 2041-2060 ====================
==================== Canberra: EC-Earth3, ssp126, 2061-2080 ====================
==================== Canberra: EC-Earth3, ssp370, 2021-2040 ====================
==================== Canberra: EC-Earth3, ssp370, 2041-2060 ====================
==================== Canberra: EC-Earth3, ssp370, 2061-2080 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Canberra: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Canberra: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Canberra: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Canberra: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Canberra: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Canberra: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175198.000000  175198.000000  175200.000000
mean       28.297230      23.882069      17.072451     100.645088       3.663897       8.064971           3.462454     231.797562     220.139618      81.223602
std         3.464521       3.682964       4.649458       0.343052       2.061186       5.205673           3.247445     313.076294     317.289642     117.776642
min         4.395286       1.594839       1.368330      98.356918       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        26.305357      22.142928      14.417196     100.427269       2.281354       4.000000           0.000000       0.000000       0.000000       0.000000
50%        28.523221      25.183731      18.622381     100.647011       3.407234       6.000000           2.000000       7.991400       0.000000       7.991400
75%        30.770797      26.515734      20.614233     100.895287       4.836917      13.000000           8.000000     466.679871     465.364075     124.132269
max        38.862377      31.838991      29.735365     101.877647      58.535057      16.000000           9.000000    1155.983032    1299.944580     760.305054

==================== Darwin: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Darwin: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       27.908060      23.389282      16.501736     100.612831       3.794518       8.194777           3.373487     231.910934     218.216934      82.023079
std         3.637327       3.778344       4.642213       0.358948       2.135244       5.092748           3.246723     314.034882     314.863342     117.729805
min         4.041133       1.125986       1.137563      98.408691       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        25.839394      21.424170      13.721226     100.380501       2.391032       4.000000           0.000000       0.000000       0.000000       0.000000
50%        28.207954      24.736398      18.036585     100.619694       3.536678       7.000000           2.000000       7.919053       0.000000       7.919053
75%        30.527134      26.135740      20.069642     100.862383       4.978381      13.000000           7.000000     466.184082     457.245972     127.078217
max        38.397358      31.027403      27.824249     101.739708      61.914597      16.000000           9.000000    1150.345093    1277.183594     741.717712

==================== Darwin: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Darwin: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Darwin: CESM2, ssp126, 2021-2040 ====================
==================== Darwin: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175116.000000  175200.000000  175116.000000
mean       28.303591      23.720423      16.860655     100.694679       3.766142       8.673316           3.560194     232.945892     222.808624      80.218658
std         3.727954       3.920904       4.839852       0.334359       2.077544       5.051722           3.317917     315.121826     319.699646     115.674110
min         3.826787       0.547623       1.274576      98.756538       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        26.323203      21.733889      14.029402     100.462961       2.386947       4.000000           0.000000       0.000000       0.000000       0.000000
50%        28.629524      25.177695      18.442373     100.696259       3.519780      10.000000           2.000000       8.016317       0.000000       8.012858
75%        30.962425      26.566898      20.579689     100.948204       4.959452      13.000000           8.000000     465.298218     470.820068     123.269051
max        38.641624      31.069374      27.914246     101.855965      59.511555      16.000000           8.000000    1154.032471    1283.291992     722.284302

==================== Darwin: CESM2, ssp126, 2061-2080 ====================
==================== Darwin: CESM2, ssp370, 2021-2040 ====================
==================== Darwin: CESM2, ssp370, 2041-2060 ====================
==================== Darwin: CESM2, ssp370, 2061-2080 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Darwin: EC-Earth3, ssp126, 2021-2040 ====================
==================== Darwin: EC-Earth3, ssp126, 2041-2060 ====================
==================== Darwin: EC-Earth3, ssp126, 2061-2080 ====================
==================== Darwin: EC-Earth3, ssp370, 2021-2040 ====================
==================== Darwin: EC-Earth3, ssp370, 2041-2060 ====================
==================== Darwin: EC-Earth3, ssp370, 2061-2080 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Darwin: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Darwin: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Darwin: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Darwin: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Darwin: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Darwin: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       13.820119      10.306256       6.547153     100.897293       4.248847      11.326187           5.367215     160.426285     157.529327      71.502289
std         4.946919       3.714330       2.031509       0.958424       2.393189       4.147140           2.751113     242.375641     284.378815     107.622185
min         0.522953       0.376767       1.508861      96.866249       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        10.324018       7.628491       5.078852     100.293510       2.477067      10.000000           3.000000       0.000000       0.000000       0.000000
50%        13.423551       9.948039       6.054980     100.979164       3.976872      13.000000           6.000000       0.000000       0.000000       0.000000
75%        16.875190      12.733733       7.560090     101.573067       5.750314      14.000000           8.000000     259.985321     166.305817     108.768015
max        41.227608      25.186014      18.724277     103.768341      20.841133      16.000000           9.000000    1100.531250    1296.640991     724.848083

==================== Hobart: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175196.000000  175196.000000  175200.000000
mean       13.382289       9.862438       6.292872     100.787338       4.478587      11.555228           5.195377     159.697906     154.904373      72.325836
std         4.764525       3.473697       1.811762       0.998544       2.474753       3.959258           2.789083     240.616348     280.037994     108.319016
min        -0.525839      -0.476741       1.425916      96.388824       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        10.023572       7.369010       4.980723     100.165604       2.579830      11.000000           3.000000       0.000000       0.000000       0.000000
50%        13.016870       9.578568       5.891131     100.882370       4.328044      13.000000           6.000000       0.000000       0.000000       0.000000
75%        16.228865      12.100636       7.215924     101.517757       6.087821      14.000000           8.000000     259.155975     162.764206     111.286453
max        42.079460      24.325150      16.983534     103.584549      19.944569      16.000000           9.000000    1085.633057    1146.400024     725.393860

==================== Hobart: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       13.147203       9.700959       6.254737     100.775620       4.414424      11.465725           5.297420     158.922821     151.240906      72.780891
std         4.801939       3.593997       1.885942       0.978589       2.459357       4.042068           2.779945     240.443054     278.951172     108.842293
min        -1.017309      -1.119072       1.369919      96.720741       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%         9.757786       7.120140       4.900583     100.147470       2.560470      10.000000           3.000000       0.000000       0.000000       0.000000
50%        12.791643       9.393658       5.824017     100.883217       4.199549      13.000000           6.000000       0.000000       0.000000       0.000000
75%        16.002035      12.018484       7.203466     101.497551       6.030644      14.000000           8.000000     257.533630     147.983215     111.530073
max        41.773216      24.635368      17.481882     103.546471      20.446512      16.000000           9.000000    1086.080933    1056.003418     737.939819

==================== Hobart: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Hobart: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Hobart: CESM2, ssp126, 2021-2040 ====================
==================== Hobart: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175177.000000  175200.000000  175177.000000
mean       13.731327      10.153683       6.423873     100.844757       4.428048      11.210479           5.669463     161.257904     157.490906      71.775131
std         4.904690       3.536140       1.855056       0.974920       2.449278       4.251250           2.677521     244.272003     284.443634     107.399063
min        -0.166073       0.063455       1.390826      96.974876       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        10.343351       7.659921       5.089781     100.206093       2.578146       9.000000           4.000000       0.000000       0.000000       0.000000
50%        13.349418       9.864661       6.015407     100.911266       4.232471      13.000000           7.000000       0.000000       0.000000       0.000000
75%        16.585531      12.417732       7.360926     101.548328       6.025909      14.000000           8.000000     260.159760     166.826893     110.200005
max        43.842972      25.801912      18.299376     103.649887      21.874666      16.000000           8.000000    1123.944946    1115.654297     717.559448

==================== Hobart: CESM2, ssp126, 2061-2080 ====================
==================== Hobart: CESM2, ssp370, 2021-2040 ====================
==================== Hobart: CESM2, ssp370, 2041-2060 ====================
==================== Hobart: CESM2, ssp370, 2061-2080 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Hobart: EC-Earth3, ssp126, 2021-2040 ====================
==================== Hobart: EC-Earth3, ssp126, 2041-2060 ====================
==================== Hobart: EC-Earth3, ssp126, 2061-2080 ====================
==================== Hobart: EC-Earth3, ssp370, 2021-2040 ====================
==================== Hobart: EC-Earth3, ssp370, 2041-2060 ====================
==================== Hobart: EC-Earth3, ssp370, 2061-2080 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Hobart: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Hobart: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Hobart: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Hobart: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Hobart: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Hobart: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175196.000000  175196.000000  175200.000000
mean       25.235176      16.277069       8.630124      99.164062       4.069448       5.085080           2.502871     245.615601     287.351318      59.847450
std         7.815331       5.597203       4.526661       0.529289       2.113961       3.709319           2.942213     328.075928     380.054718      93.828094
min        -0.052564      -3.467629       0.125126      96.809219       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        20.070905      12.156914       4.898108      98.776354       2.791575       2.000000           0.000000       0.000000       0.000000       0.000000
50%        25.722447      16.836913       7.749531      99.157356       3.945100       4.000000           1.000000       0.000000       0.000000       0.000000
75%        30.899406      20.900416      11.881160      99.557678       5.153026       7.000000           5.000000     491.423340     704.898010      87.783182
max        46.951550      30.879370      26.220100     100.836105      16.232412      16.000000           9.000000    1197.721680    1298.818726     681.461609

==================== Longreach: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Longreach: CESM2, ssp126, 2021-2040 ====================
==================== Longreach: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175183.000000  175200.000000  175183.000000
mean       25.434002      16.014059       8.247617      99.198074       4.057352       5.387334           1.950268     247.197937     292.420807      57.576900
std         8.217979       5.712212       4.417497       0.519583       2.123609       3.752206           2.707424     332.231842     387.056305      89.432648
min        -0.714382      -4.190536       0.101333      96.921722       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        20.151916      11.950331       4.496683      98.798615       2.714824       2.000000           0.000000       0.000000       0.000000       0.000000
50%        25.913619      16.816124       7.571508      99.199425       3.987303       5.000000           0.000000       0.000000       0.000000       0.000000
75%        31.340373      20.660408      11.407794      99.601799       5.095737       8.000000           3.000000     491.127289     717.279236      86.445633
max        47.892506      30.482914      26.843262     100.914604      18.013985      16.000000           8.000000    1198.008789    1285.475342     712.668396

==================== Longreach: CESM2, ssp126, 2061-2080 ====================
==================== Longreach: CESM2, ssp370, 2021-2040 ====================
==================== Longreach: CESM2, ssp370, 2041-2060 ====================
==================== Longreach: CESM2, ssp370, 2061-2080 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Longreach: EC-Earth3, ssp126, 2021-2040 ====================
==================== Longreach: EC-Earth3, ssp126, 2041-2060 ====================
==================== Longreach: EC-Earth3, ssp126, 2061-2080 ====================
==================== Longreach: EC-Earth3, ssp370, 2021-2040 ====================
==================== Longreach: EC-Earth3, ssp370, 2041-2060 ====================
==================== Longreach: EC-Earth3, ssp370, 2061-2080 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Longreach: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Longreach: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Longreach: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Longreach: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Longreach: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Longreach: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175198.000000  175198.000000  175200.000000
mean       15.521329      11.801522       7.376869     100.381027       5.033895      10.315742           4.768493     176.968140     174.314789      72.435425
std         6.198771       4.013904       2.264378       0.749708       2.951959       4.421010           3.105384     267.798431     308.737488     106.528954
min        -0.113054      -0.661840       1.010355      96.607674       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        11.151758       8.887761       5.739625      99.915327       2.932193       8.000000           2.000000       0.000000       0.000000       0.000000
50%        14.561415      11.410112       6.927511     100.386803       4.557750      10.000000           6.000000       4.120999       0.000000       4.117388
75%        18.855086      14.527907       8.583199     100.869034       6.734211      14.000000           8.000000     287.424438     201.398315     109.918758
max        46.044983      31.123123      22.816242     102.893982      60.722473      16.000000           9.000000    1154.370361    1193.625122     680.682190

==================== Melbourne: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175197.000000  175197.000000  175200.000000
mean       15.090800      11.300390       7.028278     100.322853       5.215484      10.499772           4.496501     176.039597     171.847961      72.895287
std         6.101743       3.755264       1.995199       0.769000       3.020826       4.349644           3.158046     266.207062     306.125244     106.984398
min         0.017173      -0.370411       1.017489      96.773369       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        10.839519       8.645432       5.631540      99.826332       3.097646       8.000000           1.000000       0.000000       0.000000       0.000000
50%        14.101367      10.939427       6.672438     100.371933       4.759102      11.000000           5.000000       4.021832       0.000000       4.006863
75%        18.230056      13.771954       8.035152     100.856285       6.963042      14.000000           8.000000     285.510529     194.127869     111.061714
max        46.540623      29.272137      19.659599     102.582878      69.228134      16.000000           9.000000    1154.229004    1287.991699     688.271118

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175198.000000  175198.000000  175200.000000
mean       14.966367      11.275617       7.082135     100.291641       5.141773      10.468293           4.603567     175.057938     167.838669      74.043411
std         6.171350       3.928287       2.140351       0.764331       2.982071       4.379442           3.149278     264.567230     301.541718     108.592262
min        -0.835777      -1.004830       1.153015      96.760666       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        10.663354       8.463479       5.563166      99.786680       3.021962       8.000000           1.000000       0.000000       0.000000       0.000000
50%        13.975591      10.867410       6.674997     100.328377       4.691540      11.000000           5.000000       3.888922       0.000000       3.857302
75%        18.174857      13.846338       8.127063     100.831804       6.913312      14.000000           8.000000     283.877747     181.768463     113.563875
max        46.022305      30.036921      21.127144     102.560417      65.330750      16.000000           9.000000    1146.936157    1150.791382     689.079529

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Melbourne: CESM2, ssp126, 2021-2040 ====================
==================== Melbourne: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175110.000000  175200.000000  175110.000000
mean       15.543933      11.649491       7.185046     100.367546       5.072341      10.230468           4.969492     178.435593     177.859451      72.001427
std         6.229963       3.784950       2.029095       0.760595       2.915873       4.337674           3.087047     269.721436     312.129028     106.067390
min         0.209515      -0.653884       1.021190      96.655914       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        11.242686       8.973154       5.754029      99.872574       3.034920       8.000000           2.000000       0.000000       0.000000       0.000000
50%        14.564792      11.333252       6.827004     100.387360       4.653752      10.000000           6.000000       3.873055       0.000000       3.872812
75%        18.628746      14.149052       8.257898     100.893114       6.752570      14.000000           8.000000     290.030762     215.791615     108.770401
max        46.447720      29.018280      20.292112     102.871284      66.989769      16.000000           8.000000    1193.120850    1249.893921     679.784790

==================== Melbourne: CESM2, ssp126, 2061-2080 ====================
==================== Melbourne: CESM2, ssp370, 2021-2040 ====================
==================== Melbourne: CESM2, ssp370, 2041-2060 ====================
==================== Melbourne: CESM2, ssp370, 2061-2080 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Melbourne: EC-Earth3, ssp126, 2021-2040 ====================
==================== Melbourne: EC-Earth3, ssp126, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp126, 2061-2080 ====================
==================== Melbourne: EC-Earth3, ssp370, 2021-2040 ====================
==================== Melbourne: EC-Earth3, ssp370, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp370, 2061-2080 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Melbourne: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Melbourne: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Melbourne: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Melbourne: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Melbourne: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Melbourne: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Mildura: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Mildura: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175197.000000  175197.000000  175200.000000
mean       18.584335      12.241691       6.558155     101.175743       3.477372       8.333350           3.419812     217.713547     257.952606      58.597546
std         8.385668       4.572274       2.544026       0.707723       1.841760       4.447876           3.292601     307.382904     372.738800      91.073753
min        -3.423312      -3.372093       0.095515      97.780426       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        12.382579       9.119262       4.922481     100.691139       2.304806       6.000000           0.000000       0.000000       0.000000       0.000000
50%        17.715171      12.026248       6.048953     101.145580       3.181717       8.000000           3.000000       2.317680       0.000000       2.315746
75%        24.277265      15.290030       7.548825     101.652599       4.608327      11.000000           7.000000     399.422852     612.507385      82.178476
max        47.380970      28.894384      25.819323     103.581543      44.400455      16.000000           9.000000    1194.404907    1295.817505     673.279968

==================== Mildura: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Mildura: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Mildura: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Mildura: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Mildura: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Mildura: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Mildura: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
==================== Mildura: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
==================== Mildura: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Mildura: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Mildura: CESM2, ssp126, 2021-2040 ====================
==================== Mildura: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175174.000000  175200.000000  175174.000000
mean       18.556633      12.020752       6.304805     101.188927       3.505174       8.397666           3.319983     220.910980     265.346436      57.174988
std         8.440685       4.348717       2.206045       0.710674       1.867569       4.316695           3.295891     312.548401     380.113464      88.610435
min        -2.802189      -3.013968       0.099506      97.953529       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        12.423063       9.121498       4.874277     100.686577       2.333683       6.000000           0.000000       0.000000       0.000000       0.000000
50%        17.616400      11.919005       5.951797     101.171776       3.177607       9.000000           2.000000       3.060025       0.000000       3.057926
75%        24.071388      14.974970       7.298087     101.699387       4.629974      11.000000           7.000000     404.703827     637.168335      80.299461
max        47.357342      27.369118      20.365435     103.564751      44.697594      16.000000           8.000000    1309.521240    1298.776611     659.316589

==================== Mildura: CESM2, ssp126, 2061-2080 ====================
==================== Mildura: CESM2, ssp370, 2021-2040 ====================
==================== Mildura: CESM2, ssp370, 2041-2060 ====================
==================== Mildura: CESM2, ssp370, 2061-2080 ====================
==================== Mildura: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Mildura: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Mildura: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Mildura: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Mildura: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Mildura: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Mildura: EC-Earth3, ssp126, 2021-2040 ====================
==================== Mildura: EC-Earth3, ssp126, 2041-2060 ====================
==================== Mildura: EC-Earth3, ssp126, 2061-2080 ====================
==================== Mildura: EC-Earth3, ssp370, 2021-2040 ====================
==================== Mildura: EC-Earth3, ssp370, 2041-2060 ====================
==================== Mildura: EC-Earth3, ssp370, 2061-2080 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Mildura: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Mildura: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Mildura: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Mildura: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Mildura: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Mildura: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Perth: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Perth: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       19.668154      14.298790       8.139125     101.445419       4.191213       6.519252           3.278379     217.875153     248.232056      60.196205
std         6.975265       3.980940       2.433507       0.639091       2.667323       4.333612           3.178209     308.531769     366.742767      92.715096
min        -0.499836      -1.209468       1.222450      98.770706       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        14.758617      11.620481       6.349009     100.993792       2.386649       4.000000           0.000000       0.000000       0.000000       0.000000
50%        19.115257      14.385201       7.932376     101.418079       4.048181       6.000000           2.000000       0.000000       0.000000       0.000000
75%        24.053925      17.105529       9.666455     101.863621       6.029737      10.000000           7.000000     393.351074     544.331787      87.955395
max        45.515266      29.373278      24.053680     103.966896      19.374535      16.000000           9.000000    1141.966919    1274.070923     705.423767

==================== Perth: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Perth: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Perth: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Perth: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       19.424627      14.183561       8.105649     101.427856       4.193567       6.661336           2.943168     217.107452     247.069427      60.835148
std         6.921167       3.899995       2.373030       0.594991       2.694751       4.317641           3.099113     306.803101     365.843750      93.335510
min        -0.426001      -1.415995       1.204373      98.960342       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        14.591497      11.555119       6.379148     100.999359       2.345618       4.000000           0.000000       0.000000       0.000000       0.000000
50%        18.772692      14.192145       7.888947     101.396622       4.047986       6.000000           2.000000       0.000000       0.000000       0.000000
75%        23.599514      16.931854       9.593180     101.822205       6.056202      10.000000           6.000000     391.362427     536.455811      89.838203
max        45.101768      29.707973      24.474560     103.758659      19.165558      16.000000           9.000000    1116.405151    1295.071777     667.273254

==================== Perth: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       19.228584      13.903440       7.883550     101.423279       4.226018       6.610126           2.897763     217.587799     248.144608      60.730045
std         6.874324       3.874440       2.329080       0.615914       2.699859       4.285226           3.090108     306.781464     365.781494      92.781746
min        -0.439375      -1.333503       1.205685      98.831230       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        14.425487      11.315169       6.168729     100.977661       2.382487       4.000000           0.000000       0.000000       0.000000       0.000000
50%        18.606868      13.940689       7.665348     101.391586       4.107408       6.000000           2.000000       0.000000       0.000000       0.000000
75%        23.448509      16.603594       9.349551     101.832970       6.086323      10.000000           6.000000     392.212341     539.128052      90.361301
max        45.177967      29.396648      24.137896     103.885391      18.743309      16.000000           9.000000    1119.229004    1298.143066     687.516541

==================== Perth: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Perth: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Perth: CESM2, ssp126, 2021-2040 ====================
==================== Perth: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175183.000000  175200.000000  175183.000000
mean       19.671173      14.401240       8.215655     101.475288       4.133259       6.576718           2.958590     218.337738     249.674911      59.843933
std         6.759233       3.781381       2.327180       0.592989       2.640664       4.266933           3.104804     308.849121     367.856293      90.846489
min         0.435934      -0.967794       1.407314      99.076111       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        14.963814      11.886724       6.483137     101.048203       2.329408       4.000000           0.000000       0.000000       0.000000       0.000000
50%        19.114889      14.474854       8.036703     101.448009       3.943410       6.000000           2.000000       0.000000       0.000000       0.000000
75%        23.780276      17.067868       9.720348     101.863897       5.959605      10.000000           6.000000     394.173950     547.405396      89.046021
max        45.496094      28.340069      21.761969     103.583855      18.327698      16.000000           8.000000    1118.978760    1293.409180     673.954346

==================== Perth: CESM2, ssp126, 2061-2080 ====================
==================== Perth: CESM2, ssp370, 2021-2040 ====================
==================== Perth: CESM2, ssp370, 2041-2060 ====================
==================== Perth: CESM2, ssp370, 2061-2080 ====================
==================== Perth: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Perth: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Perth: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Perth: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Perth: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Perth: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Perth: EC-Earth3, ssp126, 2021-2040 ====================
==================== Perth: EC-Earth3, ssp126, 2041-2060 ====================
==================== Perth: EC-Earth3, ssp126, 2061-2080 ====================
==================== Perth: EC-Earth3, ssp370, 2021-2040 ====================
==================== Perth: EC-Earth3, ssp370, 2041-2060 ====================
==================== Perth: EC-Earth3, ssp370, 2061-2080 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Perth: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Perth: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Perth: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Perth: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Perth: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Perth: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Sydney: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Sydney: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175190.000000  175190.000000  175200.000000
mean       19.636963      15.822911       9.912708     101.737854       5.270539       8.507568           3.904903     189.621323     201.023148      69.981293
std         5.048622       4.525580       3.546287       0.693721       2.865295       4.745575           3.244786     272.967377     325.711700     107.455681
min         4.040428       2.638865       0.990809      98.711220       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        16.132727      12.448995       7.103464     101.275778       3.120121       5.000000           0.000000       0.000000       0.000000       0.000000
50%        19.845089      16.103083       9.744279     101.746262       4.735383       8.000000           4.000000       0.000000       0.000000       0.000000
75%        23.109241      19.528448      12.613081     102.204201       7.179427      12.000000           8.000000     331.448669     317.930237      98.536386
max        47.089108      27.164555      21.514912     104.053787      86.393425      16.000000           9.000000    1122.154785    1286.697021     685.521851

==================== Sydney: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Sydney: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Sydney: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Sydney: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Sydney: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Sydney: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Sydney: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175195.000000  175195.000000  175200.000000
mean       19.386810      15.203412       9.293191     101.691246       5.429263       8.464292           3.553311     191.197678     206.468353      68.619850
std         5.126483       4.372624       3.308504       0.726991       2.954344       4.875651           3.237100     275.710052     330.992920     105.700203
min         3.425532       2.008834       0.997163      98.424644       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        15.864075      12.004529       6.703171     101.200378       3.170829       4.000000           0.000000       0.000000       0.000000       0.000000
50%        19.512034      15.387210       9.104862     101.741692       4.872571       8.000000           3.000000       0.000000       0.000000       0.000000
75%        22.713463      18.622076      11.642895     102.222290       7.374318      13.000000           7.000000     332.146118     339.188141      96.595043
max        48.156830      27.254238      20.599550     104.013733      88.245621      16.000000           9.000000    1113.767944    1295.448608     695.597229

==================== Sydney: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175199.000000  175199.000000  175200.000000
mean       19.207327      15.120675       9.296156     101.660057       5.372105       8.430582           3.620400     190.387894     204.485138      68.774078
std         5.181468       4.477241       3.360669       0.721320       2.918305       4.864906           3.248379     274.725586     329.255676     105.278641
min         3.026946       1.620766       1.098676      98.109329       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        15.576910      11.781052       6.606126     101.181717       3.156326       4.000000           0.000000       0.000000       0.000000       0.000000
50%        19.342810      15.324644       9.106777     101.699661       4.831289       8.000000           3.000000       0.000000       0.000000       0.000000
75%        22.689224      18.745608      11.794032     102.172440       7.275987      13.000000           7.000000     329.349182     332.648438      98.199814
max        46.727291      26.307487      19.798868     103.732849      83.812561      16.000000           9.000000    1111.323853    1292.421875     683.354492

==================== Sydney: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Sydney: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Sydney: CESM2, ssp126, 2021-2040 ====================
==================== Sydney: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           twbt           huss            psl     wind_speed       wind_dir  total_cloud_cover           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000      175200.000000  175194.000000  175200.000000  175194.000000
mean       19.898195      15.804598       9.761570     101.721481       5.349599       8.469606           3.856809     192.762100     208.417465      68.738174
std         5.149637       4.403488       3.396461       0.718099       2.920070       4.641015           3.244185     278.453369     333.169128     105.569366
min         4.154095       2.660778       1.077956      98.551910       0.000000       0.000000           0.000000       0.000000       0.000000       0.000000
25%        16.316440      12.540862       7.082072     101.243471       3.129902       5.000000           0.000000       0.000000       0.000000       0.000000
50%        20.097163      16.128542       9.660593     101.737701       4.801595       8.000000           4.000000       0.000000       0.000000       0.000000
75%        23.295516      19.390517      12.379400     102.217697       7.288040      12.000000           8.000000     333.757751     348.761421      96.453629
max        47.626766      27.095522      20.519081     104.112000      91.625565      16.000000           8.000000    1122.487793    1298.289673     711.197693

==================== Sydney: CESM2, ssp126, 2061-2080 ====================
==================== Sydney: CESM2, ssp370, 2021-2040 ====================
==================== Sydney: CESM2, ssp370, 2041-2060 ====================
==================== Sydney: CESM2, ssp370, 2061-2080 ====================
==================== Sydney: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Sydney: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Sydney: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Sydney: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Sydney: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Sydney: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Sydney: EC-Earth3, ssp126, 2021-2040 ====================
==================== Sydney: EC-Earth3, ssp126, 2041-2060 ====================
==================== Sydney: EC-Earth3, ssp126, 2061-2080 ====================
==================== Sydney: EC-Earth3, ssp370, 2021-2040 ====================
==================== Sydney: EC-Earth3, ssp370, 2041-2060 ====================
==================== Sydney: EC-Earth3, ssp370, 2061-2080 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Sydney: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Sydney: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Sydney: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Sydney: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Sydney: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Sydney: NorESM2-MM, ssp370, 2061-2080 ====================

=== QC summary (all files) ===

                                                  file       loc       model     ssp time_period   n_min  any_nan  any_const  rsds_min     rsds_max
0    Adelaide_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp126   2021-2040  175200    False      False       0.0  1125.402710
1    Adelaide_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp126   2041-2060  175199     True      False       0.0  1113.045410
2    Adelaide_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp126   2061-2080  175200    False      False       0.0  1120.985474
3    Adelaide_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp370   2021-2040  175200    False      False       0.0  1120.141968
4    Adelaide_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp370   2041-2060  175200    False      False       0.0  1106.313477
..                                                 ...       ...         ...     ...         ...     ...      ...        ...       ...          ...
457  Sydney_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp126   2041-2060  175200    False      False       0.0  1146.849243
458  Sydney_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp126   2061-2080  175200    False      False       0.0  1128.617065
459  Sydney_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp370   2021-2040  175200    False      False       0.0  1119.860840
460  Sydney_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp370   2041-2060  175200    False      False       0.0  1127.152222
461  Sydney_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp370   2061-2080  175200    False      False       0.0  1117.839478

[462 rows x 10 columns]

In [ ]:
# for file in files:
#     base = file.split('/')[-1]
#     loc = base.split('_')[0]
#     model = base.split('_')[2]
#     ssp = base.split('_')[3]
#     time_period = base.split('_')[9]
#     print(f"========================== {loc}: {model}, {ssp}, {time_period} ==========================")
#     da = xr.open_dataset(file)
#     print(da.drop_vars([v for v in ["time_offset","round_method",
#                                     "crs", "lat", "lon"] if v in da.variables])[vars_to_summarise].to_dataframe().describe())