# Checking output files

In [1]:
from datetime import datetime, timedelta
import calendar
import collections
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
import sys

import glob
import pandas as pd
import xarray as xr
from IPython.display import display, HTML

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)


my_dir = "/g/data/eg3/spr548/projects/"
sys.path.append(os.path.join(my_dir, "nesp_bff")+os.sep)
from nathers import location_details

# import utils
# from utils import locations, model_dict, vars_1hr, vars_day

In [13]:
step = "step2"
show_only_if_flagged = True

#==========================================
root_dir = "/g/data/eg3/nesp_bff/"
# location = "Sydney"
# scenario = "ssp370"
# model = "CESM2"
# time_period = "2041-2060"
vars_to_summarise_step2 = ["tas","huss","sfcWind","psl","uas","vas","clt","rsds","rsdsdir","rsdsdif"]
vars_to_summarise_step3 = ["tas","twbt","huss","psl","wind_speed","wind_dir","total_cloud_cover","rsds","rsdsdir","rsdsdif"]
locations = ["Darwin","Cairns","Brisbane","Longreach","Mildura","Adelaide","Perth","Sydney","Melbourne","Canberra","Hobart"]
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]

input_dir = f"{root_dir}step3_calc_missing_vars/" if step == "step3" else f"{root_dir}step2_qdc_scaling/BARPA-R/"
vars_to_summarise = vars_to_summarise_step3 if step == "step3" else vars_to_summarise_step2

In [12]:
files = glob.glob(f"{input_dir}*.nc")
len(files)

462

In [14]:
qc_rows = []
errors = []

for file in sorted(files):
    base = file.split("/")[-1]
    parts = base.split("_")

    loc = parts[0] if len(parts) > 0 else None
    model_ = parts[2] if len(parts) > 2 else None
    ssp = parts[3] if len(parts) > 3 else None
    time_period_ = parts[9] if len(parts) > 9 else None

    header = f"{loc}: {model_}, {ssp}, {time_period_}"
    print(f"==================== {header} ====================")

    try:
        with xr.open_dataset(file) as da:
            df = (
                da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
                  [vars_to_summarise]
                  .to_dataframe()
            )

        desc = df.describe()

        flagged = df.isna().any().any() or (df.nunique(dropna=True) <= 1).any()

        if (not show_only_if_flagged) or flagged:
            print("⚠️ Flagged" if flagged else "OK")
            display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
            display(desc)
            display(HTML("</div>"))

        qc_rows.append({
            "file": base,
            "loc": loc,
            "model": model_,
            "ssp": ssp,
            "time_period": time_period_,
            "n_min": int(desc.loc["count"].min()),
            "any_nan": bool(df.isna().any().any()),
            "any_const": bool((df.nunique(dropna=True) <= 1).any()),
            "rsds_min": float(desc.loc["min", "rsds"]) if "rsds" in desc.columns else None,
            "rsds_max": float(desc.loc["max", "rsds"]) if "rsds" in desc.columns else None,
        })

    except Exception as e:
        errors.append({
            "file": base,
            "loc": loc,
            "model": model_,
            "ssp": ssp,
            "time_period": time_period_,
            "error": repr(e),
        })

qc_df = pd.DataFrame(qc_rows)
err_df = pd.DataFrame(errors)

print("\n=== QC summary (all files) ===")
display(qc_df)

if not err_df.empty:
    print("\n=== Errors ===")
    display(err_df)

==================== Adelaide: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Adelaide: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      291.385535       0.007278       3.017569  101227.236169       0.329787       0.842004      44.470101     215.088843     218.944491      64.831755
std         6.816063       0.002185       1.932564     728.265088       3.150072       3.481682      38.724042     303.768071     345.802558     100.062575
min       274.657444       0.000393       0.000000   97528.480864     -12.920898     -12.734375       0.000000       0.000000       0.000000       0.000000
25%       286.556318       0.005794       1.431127  100749.384648      -1.917969      -1.500000       0.666016       0.000000       0.000000       0.000000
50%       290.131241       0.007049       2.935577  101208.408725      -0.251953       1.119141      40.390625       7.476562       0.000000       0.000000
75%       295.329311       0.008450       4.358450  101695.640976       2.562500       3.388672      84.832031     387.007812     382.762568      92.501919
max       319.746069       0.021823      13.799576  103618.296863      14.207031      11.372070     100.000000    1125.656250    1296.002304     723.055769

==================== Adelaide: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Adelaide: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175317.000000  175320.000000
mean      291.121911       0.007048       3.095351  101196.310087       0.502681       0.813736      41.139427     220.309468     219.872807      64.126066
std         6.701048       0.001945       1.951241     715.838373       3.159871       3.456609      38.300179     309.463621     345.418740      97.842820
min       274.796778       0.000315       0.000000   97727.649069     -12.100586     -12.073242       0.000000       0.000000       0.000000       0.000000
25%       286.372353       0.005740       1.512935  100711.925061      -1.777344      -1.521484       0.000000       0.000000       0.000000       0.000000
50%       289.799872       0.006849       3.056373  101195.045345      -0.055664       1.051758      33.410156       7.910156       0.000000       0.000000
75%       294.815562       0.008147       4.479700  101690.320890       2.750977       3.331055      79.807129     399.595703     386.964211      92.651711
max       319.976718       0.019094      14.285907  103256.669251      12.871094      11.301758     100.000000    1129.531250    1296.081298     721.370234

==================== Adelaide: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      290.954039       0.007114       3.065989  101162.978458       0.501124       0.824566      42.694114     216.736554     214.247582      65.999663
std         6.708255       0.002088       1.939921     733.702428       3.106377       3.446659      38.613767     305.110575     340.661524     101.088245
min       275.036732       0.000369       0.000000   97757.517074     -11.162109     -11.875000       0.000000       0.000000       0.000000       0.000000
25%       286.156901       0.005704       1.513986  100656.280579      -1.744141      -1.494141       0.000000       0.000000       0.000000       0.000000
50%       289.659048       0.006864       3.007519  101153.997461      -0.024414       1.088867      36.429688       7.781250       0.000000       0.000000
75%       294.671365       0.008226       4.396360  101668.037239       2.704102       3.325195      82.640625     391.971680     363.147011      95.351463
max       319.204227       0.021656      14.596430  103452.170385      14.409180      11.439453     100.000000    1124.972656    1251.932680     725.034574

==================== Adelaide: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Adelaide: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Adelaide: CESM2, ssp126, 2021-2040 ====================
==================== Adelaide: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175200.000000
mean      291.375286       0.007206       3.014515  101238.117203       0.548344       0.967130      45.059390     215.919754     224.858458      63.465110
std         6.826188       0.002075       1.917846     722.963719       3.057889       3.459385      38.664013     304.662645     351.304063      97.613153
min       274.103063       0.000404       0.000000   97686.286759     -10.610352     -13.648438       0.000000       0.000000       0.000000       0.000000
25%       286.590504       0.005849       1.443118  100752.419990      -1.666016      -1.381104       1.031250       0.000000       0.000000       0.000000
50%       290.101293       0.007015       2.937743  101240.555396       0.050781       1.282227      41.937500       7.837891       0.000000       0.000000
75%       295.116559       0.008336       4.361244  101722.212872       2.740234       3.511719      85.568359     386.597656     404.789980      90.712262
max       320.093131       0.019957      15.371843  103538.711954      12.863281      11.966797     100.000000    1130.750000    1278.062668     729.297014

==================== Adelaide: CESM2, ssp126, 2061-2080 ====================
==================== Adelaide: CESM2, ssp370, 2021-2040 ====================
==================== Adelaide: CESM2, ssp370, 2041-2060 ====================
==================== Adelaide: CESM2, ssp370, 2061-2080 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Adelaide: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Adelaide: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Adelaide: EC-Earth3, ssp126, 2021-2040 ====================
==================== Adelaide: EC-Earth3, ssp126, 2041-2060 ====================
==================== Adelaide: EC-Earth3, ssp126, 2061-2080 ====================
==================== Adelaide: EC-Earth3, ssp370, 2021-2040 ====================
==================== Adelaide: EC-Earth3, ssp370, 2041-2060 ====================
==================== Adelaide: EC-Earth3, ssp370, 2061-2080 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Adelaide: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Adelaide: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Adelaide: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Brisbane: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175316.000000  175320.000000
mean      294.654224       0.011956       3.970965  101598.854601      -1.034305       0.500361      37.881797     225.752277     234.954895      69.261362
std         4.967696       0.003693       2.156496     540.365381       2.795290       3.159500      37.272817     303.992923     347.081279     106.562005
min       275.731559       0.001022       0.000000   98978.932449     -15.742188     -13.833008       0.000000       0.000000       0.000000       0.000000
25%       291.418065       0.009416       2.521225  101228.730847      -3.026611      -1.920898       0.000000       0.000000       0.000000       0.000000
50%       295.310955       0.011956       3.746812  101588.465795      -1.126953       1.015625      25.656250       9.642578       0.000000       0.000000
75%       298.404243       0.014684       5.026967  101961.592605       0.805664       2.843750      73.636719     447.114258     501.554176      99.308903
max       312.843266       0.024461      19.488085  103433.469332      12.286133      13.095703     100.000000    1112.859375    1295.044122     696.827927

==================== Brisbane: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Brisbane: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175318.000000  175320.000000
mean      294.359600       0.011257       3.995737  101611.862673      -1.199550       0.358908      34.075294     228.721234     242.957897      67.309355
std         5.124628       0.003640       2.189493     549.106908       2.662697       3.126637      36.132453     306.814383     355.570087     103.734467
min       275.625086       0.000933       0.000000   99022.363726     -12.385742     -11.387695       0.000000       0.000000       0.000000       0.000000
25%       291.020030       0.008836       2.551257  101240.476163      -3.106445      -2.025635       0.000000       0.000000       0.000000       0.000000
50%       294.940231       0.011224       3.781224  101606.274073      -1.319336       0.865234      20.113281       9.798828       0.000000       0.000000
75%       298.138963       0.013760       5.115793  101997.934101       0.601562       2.663086      65.923828     453.952148     523.911543      96.075622
max       313.785138       0.024385      17.725622  103533.622402      10.752930      18.952148     100.000000    1124.675781    1287.992332     705.562983

==================== Brisbane: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175320.000000  175320.000000
mean      294.297846       0.011247       4.009399  101569.352698      -1.180733       0.396357      34.554228     228.180594     241.311104      67.819183
std         5.134070       0.003684       2.182173     551.868603       2.700927       3.109982      36.315958     306.050846     352.945521     104.052090
min       275.659468       0.000969       0.000000   98895.581351     -15.462891     -16.217773       0.000000       0.000000       0.000000       0.000000
25%       290.987898       0.008779       2.548680  101197.949752      -3.108398      -1.970703       0.000000       0.000000       0.000000       0.000000
50%       294.904392       0.011285       3.789151  101577.671969      -1.295898       0.905273      20.701172       9.925781       0.000000       0.000000
75%       298.073999       0.013787       5.138671  101962.452554       0.634766       2.721680      66.824219     452.961914     520.557653      97.858313
max       312.827409       0.024568      21.716225  103356.405183      12.444336      11.642578     100.000000    1128.531250    1286.211322     700.048058

==================== Brisbane: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Brisbane: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Brisbane: CESM2, ssp126, 2021-2040 ====================
==================== Brisbane: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175166.000000
mean      294.879654       0.011860       3.967903  101623.295036      -0.955699       0.678815      32.759817     229.812550     243.629442      66.631940
std         5.027524       0.003715       2.172287     539.854108       2.864745       3.175323      35.899359     306.595710     357.343942     102.277840
min       275.721835       0.001043       0.000000   99174.467458     -15.769531     -11.254883       0.000000       0.000000       0.000000       0.000000
25%       291.711570       0.009388       2.500135  101251.180401      -3.023438      -1.666992       0.000000       0.000000       0.000000       0.000000
50%       295.540579       0.012015       3.720571  101625.169351      -1.121094       1.207031      17.974609       9.970703       0.000000       0.000000
75%       298.540575       0.014490       5.051512  102013.601436       0.934570       3.028320      63.449219     459.047852     525.972836      95.578881
max       313.225310       0.025373      17.683781  103532.250825      11.957031      14.805664     100.000000    1122.218750    1296.729542     697.811408

==================== Brisbane: CESM2, ssp126, 2061-2080 ====================
==================== Brisbane: CESM2, ssp370, 2021-2040 ====================
==================== Brisbane: CESM2, ssp370, 2041-2060 ====================
==================== Brisbane: CESM2, ssp370, 2061-2080 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Brisbane: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Brisbane: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Brisbane: EC-Earth3, ssp126, 2021-2040 ====================
==================== Brisbane: EC-Earth3, ssp126, 2041-2060 ====================
==================== Brisbane: EC-Earth3, ssp126, 2061-2080 ====================
==================== Brisbane: EC-Earth3, ssp370, 2021-2040 ====================
==================== Brisbane: EC-Earth3, ssp370, 2041-2060 ====================
==================== Brisbane: EC-Earth3, ssp370, 2061-2080 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Brisbane: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Brisbane: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Brisbane: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Cairns: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Cairns: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175320.000000  175320.000000
mean      298.960669       0.015556       4.431728  101224.658899      -1.974813       2.352023      48.436278     237.636944     193.489410      88.519493
std         3.596867       0.003477       2.278002     441.467062       1.757700       2.160567      36.194287     317.196293     310.856308     128.213654
min       282.377594       0.002749       0.000000   98157.470985     -12.518555     -12.372070       0.000000       0.000000       0.000000       0.000000
25%       296.661256       0.013098       3.067673  100932.019752      -3.276367       1.337891      14.117188       0.000000       0.000000       0.000000
50%       299.132293       0.015611       4.498178  101260.346872      -1.986328       2.566406      46.299805       7.675781       0.000000       0.000000
75%       301.390310       0.018332       5.861470  101546.399423      -0.836914       3.760742      85.054688     474.644531     312.457351     134.584058
max       313.605909       0.027180      20.816994  102490.102654       8.742188      12.642578     100.000000    1106.914062    1286.690417     729.016399

==================== Cairns: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Cairns: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Cairns: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Cairns: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Cairns: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Cairns: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Cairns: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175320.000000  175320.000000
mean      298.694908       0.015144       4.544742  101242.797982      -2.024394       2.423770      45.952781     240.776232     194.899970      87.157676
std         3.645328       0.003392       2.335347     438.543088       1.723326       2.165395      35.834079     320.373118     313.883857     126.563966
min       282.734154       0.002782       0.000000   98082.692336     -18.394531     -13.625977       0.000000       0.000000       0.000000       0.000000
25%       296.349396       0.012773       3.154414  100966.162903      -3.309570       1.386719      12.294922       0.000000       0.000000       0.000000
50%       298.890483       0.015090       4.661291  101287.280795      -2.026367       2.669922      41.324219       7.685547       0.000000       0.000000
75%       301.143891       0.017784       6.006148  101576.383078      -0.879883       3.847656      81.460938     484.342773     309.313444     132.537159
max       315.586801       0.026148      19.080061  102468.388868      12.573242      15.541992     100.000000    1104.796875    1287.953198     735.471260

==================== Cairns: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      298.463773       0.015119       4.478728  101206.492620      -1.922475       2.426919      47.482747     237.117577     192.321113      89.245702
std         3.644648       0.003449       2.312827     451.380095       1.699359       2.169731      36.212716     316.073348     309.967955     130.438170
min       282.694373       0.003021       0.000000   97550.356602     -14.068359     -13.534180       0.000000       0.000000       0.000000       0.000000
25%       296.147644       0.012647       3.105700  100914.836909      -3.177734       1.409180      13.416016       0.000000       0.000000       0.000000
50%       298.697180       0.015147       4.542852  101262.410289      -1.914062       2.656250      43.674805       7.726562       0.000000       0.000000
75%       300.904379       0.017830       5.969305  101535.310928      -0.797852       3.843750      84.127930     476.454102     306.081931     135.661233
max       314.017451       0.026239      21.414094  102480.602910      11.415039      16.628906     100.000000    1122.664062    1294.881316     749.130378

==================== Cairns: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Cairns: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Cairns: CESM2, ssp126, 2021-2040 ====================
==================== Cairns: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175197.000000
mean      298.779523       0.015379       4.366277  101282.654191      -1.878904       2.083702      43.198628     248.656684     196.977110      85.765300
std         3.879771       0.003636       2.265276     420.736529       1.883849       2.196372      37.104223     328.078686     316.414256     124.180868
min       282.362437       0.002460       0.000000   98281.458341     -14.423828     -16.681641       0.000000       0.000000       0.000000       0.000000
25%       296.424929       0.012734       3.036081  100982.086140      -3.279297       0.992188       6.476562       0.000000       0.000000       0.000000
50%       299.053728       0.015650       4.435918  101324.798454      -1.868164       2.363281      34.050781       7.972656       0.000000       0.000000
75%       301.308590       0.018261       5.752649  101603.274763      -0.591797       3.497070      80.925781     505.468750     314.596699     130.488838
max       314.056164       0.026973      23.125046  102576.044633      13.272461      16.589844     100.000000    1120.218750    1249.699634     736.871882

==================== Cairns: CESM2, ssp126, 2061-2080 ====================
==================== Cairns: CESM2, ssp370, 2021-2040 ====================
==================== Cairns: CESM2, ssp370, 2041-2060 ====================
==================== Cairns: CESM2, ssp370, 2061-2080 ====================
==================== Cairns: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Cairns: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Cairns: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Cairns: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Cairns: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Cairns: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Cairns: EC-Earth3, ssp126, 2021-2040 ====================
==================== Cairns: EC-Earth3, ssp126, 2041-2060 ====================
==================== Cairns: EC-Earth3, ssp126, 2061-2080 ====================
==================== Cairns: EC-Earth3, ssp370, 2021-2040 ====================
==================== Cairns: EC-Earth3, ssp370, 2041-2060 ====================
==================== Cairns: EC-Earth3, ssp370, 2061-2080 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Cairns: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Cairns: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Cairns: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Cairns: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Cairns: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Cairns: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Cairns: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Canberra: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Canberra: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175318.000000  175320.000000
mean      287.797610       0.007415       3.198786   94984.159075       0.474548      -0.553421      47.605309     212.292835     225.141911      64.686706
std         7.725217       0.002842       2.553865     643.137560       3.128183       2.164582      39.494662     298.204458     345.478337     100.314859
min       265.946933       0.000719       0.000000   83775.258627     -10.059570     -10.538086       0.000000       0.000000       0.000000       0.000000
25%       282.377724       0.005172       1.254433   94561.034832      -1.449219      -2.022461       2.554688       0.000000       0.000000       0.000000
50%       287.633350       0.006825       2.558631   94996.206845       0.023438      -0.542969      46.077148       8.785156       0.000000       0.000000
75%       292.878247       0.009374       4.778659   95416.831925       2.514648       0.828125      90.238281     388.321289     420.759425      90.869401
max       315.615206       0.020706      26.831975   97158.120667      12.786133      10.617188     100.000000    1141.359375    1283.469586     744.279812

==================== Canberra: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Canberra: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Canberra: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175317.000000  175320.000000
mean      287.493623       0.006877       3.325223   94929.395738       0.630923      -0.692958      42.830611     218.623455     227.339797      62.832322
std         7.796405       0.002508       2.692074     672.102030       3.161696       2.120162      39.319231     304.718475     348.384304      97.033177
min       266.339605       0.000597       0.000000   83839.878356      -8.567383     -12.649414       0.000000       0.000000       0.000000       0.000000
25%       281.985740       0.004976       1.336487   94485.316362      -1.331055      -2.097656       0.039062       0.000000       0.000000       0.000000
50%       287.049160       0.006341       2.604616   94954.499903       0.140625      -0.674805      35.041016       9.082031       0.000000       0.000000
75%       292.436386       0.008440       4.952100   95406.353252       2.659180       0.712891      85.068359     404.915039     424.360142      88.848350
max       315.335649       0.019927      29.657647   97129.356404      12.832031      10.515625     100.000000    1139.300781    1298.053522     730.614152

==================== Canberra: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175320.000000  175320.000000
mean      287.333745       0.006932       3.308625   94903.535997       0.601900      -0.655332      44.116828     215.855005     222.104842      64.730433
std         7.818765       0.002596       2.680695     664.407681       3.149706       2.117991      39.451860     301.486269     343.477363     100.397117
min       265.283407       0.000694       0.000000   84008.604228      -9.303711     -10.824219       0.000000       0.000000       0.000000       0.000000
25%       281.811463       0.004950       1.288351   94466.735283      -1.345703      -2.073242       0.302734       0.000000       0.000000       0.000000
50%       286.959343       0.006369       2.613616   94932.381422       0.127930      -0.642578      38.152344       9.017578       0.000000       0.000000
75%       292.339604       0.008581       4.938755   95374.896962       2.630859       0.712891      86.811035     398.259766     410.035805      91.284627
max       314.430330       0.019730      30.294264   96995.024539      14.827148      11.673828     100.000000    1147.265625    1293.788351     745.622252

==================== Canberra: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Canberra: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Canberra: CESM2, ssp126, 2021-2040 ====================
==================== Canberra: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175171.000000
mean      288.035294       0.007205       3.241022   94963.737492       0.432503      -0.529035      46.644226     214.914035     235.277679      61.696391
std         7.855329       0.002648       2.619128     663.270439       3.168336       2.190053      39.361919     301.009787     355.781813      94.992188
min       265.798209       0.000635       0.000000   83891.375892     -11.526367     -10.796875       0.000000       0.000000       0.000000       0.000000
25%       282.520259       0.005141       1.244957   94519.033892      -1.562500      -2.020508       1.942871       0.000000       0.000000       0.000000
50%       287.692931       0.006680       2.580834   94963.997794      -0.067383      -0.541992      43.863281       8.851562       0.000000       0.000000
75%       293.004458       0.008950       4.828519   95419.191392       2.502930       0.828125      89.128906     393.954102     455.898671      86.425858
max       314.813788       0.020180      29.797729   97309.278470      12.874023      12.222656     100.000000    1154.250000    1297.522918     727.817238

==================== Canberra: CESM2, ssp126, 2061-2080 ====================
==================== Canberra: CESM2, ssp370, 2021-2040 ====================
==================== Canberra: CESM2, ssp370, 2041-2060 ====================
==================== Canberra: CESM2, ssp370, 2061-2080 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Canberra: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Canberra: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Canberra: EC-Earth3, ssp126, 2021-2040 ====================
==================== Canberra: EC-Earth3, ssp126, 2041-2060 ====================
==================== Canberra: EC-Earth3, ssp126, 2061-2080 ====================
==================== Canberra: EC-Earth3, ssp370, 2021-2040 ====================
==================== Canberra: EC-Earth3, ssp370, 2041-2060 ====================
==================== Canberra: EC-Earth3, ssp370, 2061-2080 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Canberra: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Canberra: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Canberra: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Canberra: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Canberra: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Canberra: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Canberra: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Darwin: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175318.000000  175320.000000
mean      301.457004       0.017075       3.663529  100644.828243      -0.288425      -0.535135      39.926250     235.473137     220.036064      81.246066
std         3.463771       0.004649       2.061089     343.094455       3.096135       2.210201      40.486764     310.164117     317.334655     117.751712
min       277.555285       0.001368       0.000000   98356.919143     -20.153320     -28.133789       0.000000       0.000000       0.000000       0.000000
25%       299.465489       0.014422       2.280870  100426.916645      -2.515625      -1.905273       0.000000       0.000000       0.000000       0.000000
50%       301.682437       0.018625       3.405416  100646.777335      -0.455078      -0.517578      23.817383       8.005859       0.000000       7.990724
75%       303.929812       0.020616       4.836663  100895.109427       2.028320       0.888672      87.671875     482.810547     464.946203     124.173700
max       312.022376       0.029735      58.535057  101877.650987      19.771484      25.823242     100.000000    1072.855469    1299.944585     760.305065

==================== Darwin: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Darwin: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Darwin: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175320.000000  175320.000000
mean      301.648272       0.016865       3.791157  100626.202511      -0.115154      -0.492110      37.541791     242.494278     224.061953      79.208501
std         3.625045       0.004529       2.104851     347.267033       3.165713       2.067514      40.097519     315.790488     320.284875     114.006657
min       278.174900       0.001441       0.000000   98414.981717     -24.630859     -20.012695       0.000000       0.000000       0.000000       0.000000
25%       299.496652       0.014224       2.395338  100392.877110      -2.449219      -1.818359       0.000000       0.000000       0.000000       0.000000
50%       301.901636       0.018190       3.529219  100625.092806      -0.286133      -0.502930      19.785156       8.427734       0.000000       8.015550
75%       304.283302       0.020343       4.999184  100865.944633       2.284424       0.867188      82.470703     501.110352     475.090973     122.472913
max       311.872904       0.029939      60.478661  101817.161069      15.440430      28.744141     100.000000    1079.015625    1235.154277     737.898818

==================== Darwin: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      301.067853       0.016504       3.794005  100612.568227      -0.105686      -0.394207      38.865865     238.051840     218.123581      82.043856
std         3.636795       0.004642       2.135244     358.872768       3.188005       2.089847      40.431858     311.635856     314.594640     117.739263
min       277.201133       0.001138       0.000000   98408.689969     -13.296875     -14.544922       0.000000       0.000000       0.000000       0.000000
25%       298.999450       0.013726       2.390699  100380.339072      -2.441406      -1.716797       0.000000       0.000000       0.000000       0.000000
50%       301.366880       0.018040       3.535834  100619.454681      -0.316406      -0.404297      22.027344       8.257812       0.000000       7.919052
75%       303.685941       0.020071       4.977768  100861.465699       2.274414       0.950195      86.175781     491.250977     456.963996     127.105841
max       311.557356       0.027824      61.914595  101739.709712      22.436523      13.057617     100.000000    1073.703125    1277.183632     741.717714

==================== Darwin: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Darwin: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Darwin: CESM2, ssp126, 2021-2040 ====================
==================== Darwin: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175116.000000
mean      301.463588       0.016861       3.766142  100694.679589       0.393228      -0.443045      41.307773     245.465512     222.808616      80.218657
std         3.728011       0.004840       2.077534     334.105518       3.285680       2.101381      41.335534     319.824465     319.917122     115.700596
min       276.986787       0.001275       0.000000   98756.542117     -13.866211     -14.866211       0.000000       0.000000       0.000000       0.000000
25%       299.483203       0.014029       2.386947  100462.960816      -2.035156      -1.778320       0.000000       0.000000       0.000000       0.000000
50%       301.789524       0.018442       3.519780  100696.255828       0.327148      -0.497070      24.917969       8.283203       0.000000       8.012858
75%       304.122425       0.020580       4.959452  100948.203285       2.838867       0.885742      91.775391     508.317383     470.820080     123.269048
max       311.801624       0.027914      59.511554  101855.964348      16.308594      24.308594     100.000000    1067.171875    1283.292030     722.284276

==================== Darwin: CESM2, ssp126, 2061-2080 ====================
==================== Darwin: CESM2, ssp370, 2021-2040 ====================
==================== Darwin: CESM2, ssp370, 2041-2060 ====================
==================== Darwin: CESM2, ssp370, 2061-2080 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Darwin: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Darwin: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Darwin: EC-Earth3, ssp126, 2021-2040 ====================
==================== Darwin: EC-Earth3, ssp126, 2041-2060 ====================
==================== Darwin: EC-Earth3, ssp126, 2061-2080 ====================
==================== Darwin: EC-Earth3, ssp370, 2021-2040 ====================
==================== Darwin: EC-Earth3, ssp370, 2041-2060 ====================
==================== Darwin: EC-Earth3, ssp370, 2061-2080 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Darwin: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Darwin: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Darwin: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Darwin: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Darwin: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Darwin: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Darwin: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Hobart: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      286.981085       0.006547       4.248654  100897.513684       2.160413      -0.810533      62.533894     174.552038     157.490992      71.528162
std         4.945947       0.002031       2.392939     958.263539       2.945903       2.491400      34.896531     251.984935     284.505767     107.634214
min       273.682953       0.001509       0.000000   96866.246182     -10.725586     -12.092773       0.000000       0.000000       0.000000       0.000000
25%       283.486367       0.005079       2.477062  100294.051219       0.315186      -2.213867      32.674805       0.000000       0.000000       0.000000
50%       286.585704       0.006055       3.977631  100979.428744       1.548828      -0.965820      72.216797       6.386719       0.000000       0.000000
75%       290.035467       0.007560       5.750232  101573.185410       3.934570       0.528320      96.100586     305.645508     166.241811     108.786902
max       314.387609       0.018724      20.841133  103768.341118      14.510742      11.118164     100.000000    1075.621094    1296.640932     724.848063

==================== Hobart: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Hobart: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Hobart: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175316.000000  175320.000000
mean      286.543058       0.006293       4.478705  100787.608301       2.607491      -1.025156      60.289393     180.233252     154.872421      72.350046
std         4.763563       0.001812       2.474652     998.441588       3.082759       2.563200      35.226184     258.944301     280.154918     108.318170
min       272.634161       0.001426       0.000000   96388.825393      -7.892578     -12.442383       0.000000       0.000000       0.000000       0.000000
25%       283.186266       0.004981       2.579920  100165.766863       0.577148      -2.447266      28.716797       0.000000       0.000000       0.000000
50%       286.178319       0.005891       4.328344  100882.722241       1.983398      -1.090820      68.539062       6.796875       0.000000       0.000000
75%       289.388912       0.007216       6.088587  101518.157737       4.631836       0.366211      94.640625     315.533203     162.695874     111.315920
max       315.239461       0.016984      19.944569  103584.545922      14.743164      13.747070     100.000000    1081.406250    1146.400039     725.393878

==================== Hobart: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      286.308087       0.006255       4.414446  100775.877790       2.518823      -1.013528      61.632780     178.740420     151.206079      72.805373
std         4.801047       0.001886       2.459195     978.470765       3.132996       2.535759      35.172748     258.120911     279.011239     108.909653
min       272.142691       0.001370       0.000000   96720.740570      -8.718750     -12.932617       0.000000       0.000000       0.000000       0.000000
25%       282.920435       0.004901       2.560485  100147.963878       0.455078      -2.462891      30.728516       0.000000       0.000000       0.000000
50%       285.953400       0.005824       4.200323  100883.560440       1.868164      -1.091797      71.082031       6.554688       0.000000       0.000000
75%       289.162125       0.007204       6.030819  101497.819281       4.581055       0.391602      95.589844     310.291016     147.908568     111.558707
max       314.933215       0.017482      20.446513  103546.469853      15.541992      13.153320     100.000000    1081.476562    1056.003439     737.939823

==================== Hobart: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Hobart: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Hobart: CESM2, ssp126, 2021-2040 ====================
==================== Hobart: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175177.000000
mean      286.891325       0.006424       4.428047  100844.758622       2.037760      -0.836146      66.408417     172.708870     157.490904      71.775137
std         4.904783       0.001855       2.449307     974.940258       2.909150       2.490295      33.994589     251.104559     284.599141     107.455910
min       272.993927       0.001391       0.000000   96974.873267      -7.653320     -13.703125       0.000000       0.000000       0.000000       0.000000
25%       283.503351       0.005090       2.578146  100206.089570       0.179688      -2.196289      40.804199       0.000000       0.000000       0.000000
50%       286.509418       0.006015       4.232471  100911.263690       1.479492      -0.951172      78.830078       6.314453       0.000000       0.000000
75%       289.745532       0.007361       6.025909  101548.328923       3.862305       0.535156      97.216797     298.106445     166.826888     110.200002
max       317.002973       0.018299      21.874666  103649.887026      13.985352      10.673828     100.000000    1088.820312    1115.654263     717.559426

==================== Hobart: CESM2, ssp126, 2061-2080 ====================
==================== Hobart: CESM2, ssp370, 2021-2040 ====================
==================== Hobart: CESM2, ssp370, 2041-2060 ====================
==================== Hobart: CESM2, ssp370, 2061-2080 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Hobart: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Hobart: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Hobart: EC-Earth3, ssp126, 2021-2040 ====================
==================== Hobart: EC-Earth3, ssp126, 2041-2060 ====================
==================== Hobart: EC-Earth3, ssp126, 2061-2080 ====================
==================== Hobart: EC-Earth3, ssp370, 2021-2040 ====================
==================== Hobart: EC-Earth3, ssp370, 2041-2060 ====================
==================== Hobart: EC-Earth3, ssp370, 2061-2080 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Hobart: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Hobart: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Hobart: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Hobart: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Hobart: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Hobart: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Hobart: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Longreach: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175316.000000  175320.000000
mean      298.397214       0.008633       4.069538   99163.776830      -2.392180       0.197442      28.052938     246.982210     287.317602      59.864850
std         7.814273       0.004528       2.114090     529.160737       2.505650       3.476864      35.283126     325.407090     380.097914      93.843245
min       273.107436       0.000125       0.000000   96809.217734     -12.821289     -10.329102       0.000000       0.000000       0.000000       0.000000
25%       293.234900       0.004900       2.791791   98775.904527      -4.063477      -2.469727       0.000000       0.000000       0.000000       0.000000
50%       298.883300       0.007753       3.945344   99157.096261      -2.724609       0.241211       7.125000       9.314453       0.000000       0.000000
75%       304.060633       0.011887       5.153914   99557.572678      -0.979492       3.039062      53.327148     503.583984     704.729757      87.797210
max       320.111549       0.026220      16.232413  100836.107021      10.828125      11.577148     100.000000    1157.855469    1298.818706     681.461581

==================== Longreach: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Longreach: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Longreach: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175320.000000  175320.000000
mean      298.073246       0.008017       4.123670   99179.727654      -2.511012       0.059302      23.309728     250.862612     291.922056      58.206954
std         8.058468       0.004251       2.160601     526.327884       2.436131       3.449851      32.560500     328.173674     386.310406      90.960157
min       273.097739       0.000116       0.000000   96875.451598     -15.877930     -11.648438       0.000000       0.000000       0.000000       0.000000
25%       292.782063       0.004542       2.754016   98796.764631      -4.107422      -2.512695       0.000000       0.000000       0.000000       0.000000
50%       298.530599       0.007221       4.078176   99182.185265      -2.836914       0.039062       1.480469       9.775391       0.000000       0.000000
75%       303.834707       0.010864       5.134064   99583.847508      -1.202148       2.848633      39.172852     518.752930     719.906079      86.627903
max       319.959332       0.024959      16.448286  100903.123135      10.970703      12.724609     100.000000    1155.386719    1297.688927     668.704458

==================== Longreach: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175320.000000  175320.000000
mean      297.756520       0.008098       4.114714   99149.999589      -2.463860       0.082443      24.809749     248.401237     285.953317      59.789283
std         8.022621       0.004363       2.177389     533.528657       2.454353       3.472612      33.543034     325.879264     380.642649      93.214695
min       273.539638       0.000124       0.000000   96891.270980     -13.664062     -18.159180       0.000000       0.000000       0.000000       0.000000
25%       292.449504       0.004536       2.761627   98775.750482      -4.054688      -2.556641       0.000000       0.000000       0.000000       0.000000
50%       298.256633       0.007178       4.016136   99167.359588      -2.777344       0.075195       2.628906       9.337891       0.000000       0.000000
75%       303.543488       0.011036       5.179667   99541.815844      -1.128906       2.877930      44.253906     511.004883     701.029365      89.107829
max       319.709650       0.024639      18.621272  100833.584258      12.722656      13.278320     100.000000    1168.238281    1297.136647     692.212121

==================== Longreach: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Longreach: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Longreach: CESM2, ssp126, 2021-2040 ====================
==================== Longreach: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175183.000000
mean      298.594002       0.008248       4.057351   99198.069869      -2.048245       0.626678      21.576868     255.556106     292.420742      57.576894
std         8.218101       0.004418       2.123671     519.393443       2.582337       3.658054      32.129362     333.192813     386.817323      89.406613
min       272.445618       0.000101       0.000000   96921.725478     -15.205078     -13.003906       0.000000       0.000000       0.000000       0.000000
25%       293.311916       0.004497       2.714824   98798.610907      -3.776367      -2.184814       0.000000       0.000000       0.000000       0.000000
50%       299.073620       0.007572       3.987303   99199.424112      -2.403320       0.905273       0.000000       9.792969       0.000000       0.000000
75%       304.500373       0.011408       5.095737   99601.795884      -0.534180       3.594971      34.238770     529.928711     717.279249      86.445635
max       321.052505       0.026843      18.013985  100914.607179      12.527344      13.294922     100.000000    1155.882812    1285.475356     712.668388

==================== Longreach: CESM2, ssp126, 2061-2080 ====================
==================== Longreach: CESM2, ssp370, 2021-2040 ====================
==================== Longreach: CESM2, ssp370, 2041-2060 ====================
==================== Longreach: CESM2, ssp370, 2061-2080 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Longreach: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Longreach: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Longreach: EC-Earth3, ssp126, 2021-2040 ====================
==================== Longreach: EC-Earth3, ssp126, 2041-2060 ====================
==================== Longreach: EC-Earth3, ssp126, 2061-2080 ====================
==================== Longreach: EC-Earth3, ssp370, 2021-2040 ====================
==================== Longreach: EC-Earth3, ssp370, 2041-2060 ====================
==================== Longreach: EC-Earth3, ssp370, 2061-2080 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Longreach: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Longreach: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Longreach: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Longreach: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Longreach: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Longreach: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Longreach: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175318.000000  175320.000000
mean      288.682694       0.007378       5.033474  100381.025052       1.001588      -0.102025      55.464214     190.276624     174.298898      72.454416
std         6.197794       0.002265       2.951742     749.523896       1.989649       3.697031      38.689222     276.256336     308.599439     106.551093
min       273.046946       0.001010       0.000000   96607.676551      -7.308594     -13.144531       0.000000       0.000000       0.000000       0.000000
25%       284.313612       0.005740       2.932106   99915.562048      -0.287109      -2.739258      14.138672       0.000000       0.000000       0.000000
50%       287.724878       0.006928       4.557572  100386.806296       0.656250       0.541016      63.493164       7.113281       0.000000       4.117388
75%       292.016530       0.008585       6.733923  100868.904110       2.069580       2.728516      94.998047     333.642578     201.398309     109.948818
max       319.204983       0.022816      60.722472  102893.985624      11.757812       9.188477     100.000000    1112.625000    1193.625098     680.682202

==================== Melbourne: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175317.000000  175320.000000
mean      288.251865       0.007029       5.215053  100322.942190       1.124951      -0.172952      52.081881     195.388834     171.835174      72.913250
std         6.100743       0.001996       3.020606     768.856753       1.996167       3.771517      39.149529     282.266255     305.975026     106.949351
min       273.177173       0.001017       0.000000   96773.368959      -6.283203     -13.199219       0.000000       0.000000       0.000000       0.000000
25%       284.001413       0.005631       3.097312   99826.509236      -0.187500      -2.908203       8.345703       0.000000       0.000000       0.000000
50%       287.263990       0.006673       4.758996  100371.947912       0.717773       0.449219      56.619141       7.458984       0.000000       4.006863
75%       291.391101       0.008036       6.962645  100856.303770       2.149414       2.771484      93.115234     343.606445     194.127874     111.083583
max       319.700623       0.019660      69.228133  102582.877081      11.889648       9.521484     100.000000    1111.562500    1287.991654     688.271129

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175318.000000  175320.000000
mean      288.127479       0.007083       5.141343  100291.699888       1.102347      -0.190122      53.472418     192.698484     167.823139      74.062340
std         6.170373       0.002141       2.981805     764.179717       1.989525       3.713963      39.121768     279.122161     301.303756     108.584596
min       272.324223       0.001153       0.000000   96760.667127      -7.233398     -15.771484       0.000000       0.000000       0.000000       0.000000
25%       283.824571       0.005563       3.021961   99786.787861      -0.215820      -2.882812      10.302734       0.000000       0.000000       0.000000
50%       287.137893       0.006675       4.691212  100328.434981       0.714844       0.450195      59.574219       7.302734       0.000000       3.857302
75%       291.335853       0.008128       6.912739  100831.708404       2.153320       2.677734      94.183594     338.175781     181.761510     113.579279
max       319.182303       0.021127      65.330750  102560.420692      12.899414       9.331055     100.000000    1111.542969    1150.791403     689.079535

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Melbourne: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Melbourne: CESM2, ssp126, 2021-2040 ====================
==================== Melbourne: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175110.000000
mean      288.703932       0.007185       5.072342  100367.548093       1.045839       0.068951      58.015403     189.746825     177.859454      72.001416
std         6.230075       0.002029       2.915841     760.603597       1.942790       3.713588      38.512812     276.502858     312.025595     106.006389
min       273.369515       0.001021       0.000000   96655.916735      -6.781250     -14.722656       0.000000       0.000000       0.000000       0.000000
25%       284.402686       0.005754       3.034920   99872.571450      -0.217773      -2.551758      17.971680       0.000000       0.000000       0.000000
50%       287.724792       0.006827       4.653752  100387.357329       0.690430       0.794922      69.238281       7.078125       0.000000       3.872812
75%       291.788747       0.008258       6.752570  100893.113896       2.081055       2.917969      96.185547     329.490234     215.791614     108.770399
max       319.607721       0.020292      66.989770  102871.283626      11.704102       9.434570     100.000000    1113.222656    1249.893943     679.784776

==================== Melbourne: CESM2, ssp126, 2061-2080 ====================
==================== Melbourne: CESM2, ssp370, 2021-2040 ====================
==================== Melbourne: CESM2, ssp370, 2041-2060 ====================
==================== Melbourne: CESM2, ssp370, 2061-2080 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Melbourne: EC-Earth3, ssp126, 2021-2040 ====================
==================== Melbourne: EC-Earth3, ssp126, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp126, 2061-2080 ====================
==================== Melbourne: EC-Earth3, ssp370, 2021-2040 ====================
==================== Melbourne: EC-Earth3, ssp370, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp370, 2061-2080 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Melbourne: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Melbourne: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Melbourne: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Melbourne: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Melbourne: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Melbourne: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Mildura: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Mildura: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175317.000000  175320.000000
mean      291.745547       0.006559       3.478052  101175.587925       0.653471       0.969056      39.502621     223.589283     257.957146      58.602029
std         8.384149       0.002545       1.844611     707.638401       2.925853       3.583633      40.189670     310.125270     372.974146      91.047565
min       269.736688       0.000096       0.000000   97780.426920     -11.681641     -15.123047       0.000000       0.000000       0.000000       0.000000
25%       285.546894       0.004922       2.305116  100691.195046      -1.475586      -1.671875       0.000000       0.000000       0.000000       0.000000
50%       290.877672       0.006049       3.181913  101145.464203       0.399414       1.513672      25.683594      10.638672       0.000000       2.320566
75%       297.436948       0.007550       4.608539  101652.301336       2.471680       3.666992      83.626953     413.551758     612.608731      82.187738
max       320.540969       0.025819      46.153327  103581.545850      14.562500      11.696289     100.000000    1135.062500    1295.817446     673.279981

==================== Mildura: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Mildura: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Mildura: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Mildura: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Mildura: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Mildura: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Mildura: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175320.000000  175320.000000
mean      291.306270       0.006221       3.580282  101154.492816       0.785951       0.942270      35.113811     229.070995     256.707997      57.439426
std         8.280582       0.002135       1.918438     700.676287       2.918324       3.600941      39.096641     316.169247     373.043344      88.224297
min       269.236740       0.000106       0.000000   97925.937179     -10.686523     -14.139648       0.000000       0.000000       0.000000       0.000000
25%       285.223561       0.004829       2.412052  100673.351602      -1.328125      -1.725586       0.000000       0.000000       0.000000       0.000000
50%       290.372496       0.005899       3.237228  101150.644827       0.525391       1.466309      16.357422      10.746094       0.000000       2.718130
75%       296.709655       0.007200       4.765997  101649.956934       2.573242       3.677734      74.478516     426.956055     599.676122      82.965665
max       321.603926       0.020778      45.621934  103336.596090      14.791992      13.075195     100.000000    1144.191406    1277.412226     663.529564

==================== Mildura: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175320.000000  175320.000000
mean      291.206174       0.006387       3.557020  101118.086158       0.782281       0.921068      37.062152     225.257839     251.012259      60.092670
std         8.296790       0.002383       1.918055     713.000752       2.913406       3.576591      39.536813     311.165054     366.875401      92.711809
min       269.313159       0.000110       0.000000   97910.083532      -9.460938     -13.653320       0.000000       0.000000       0.000000       0.000000
25%       285.076192       0.004844       2.352716  100610.556335      -1.311523      -1.685547       0.000000       0.000000       0.000000       0.000000
50%       290.226489       0.005962       3.258200  101108.221992       0.514648       1.426758      21.201172      10.767578       0.000000       2.313111
75%       296.601614       0.007370       4.732507  101631.963133       2.580078       3.579102      78.644531     419.222656     580.715057      85.130958
max       320.863797       0.022947      45.479034  103306.454477      15.818359      11.542969     100.000000    1138.820312    1291.168762     664.992244

==================== Mildura: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Mildura: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Mildura: CESM2, ssp126, 2021-2040 ====================
==================== Mildura: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175174.000000
mean      291.716630       0.006305       3.505175  101188.937219       0.886043       1.221768      38.295215     227.516834     265.346448      57.174987
std         8.440861       0.002206       1.867634     710.690582       2.896737       3.599919      40.081336     315.083358     380.213117      88.586062
min       270.357811       0.000100       0.000000   97953.531212     -10.768555     -13.858398       0.000000       0.000000       0.000000       0.000000
25%       285.583064       0.004874       2.333683  100686.579912      -1.167969      -1.390625       0.000000       0.000000       0.000000       0.000000
50%       290.776401       0.005952       3.177607  101171.777638       0.670410       1.892578      22.894531      10.847656       0.000000       3.057926
75%       297.231389       0.007298       4.629974  101699.384124       2.632812       3.921875      82.076172     418.708984     637.168352      80.299464
max       320.517343       0.020365      44.697595  103564.753351      15.342773      13.526367     100.000000    1139.656250    1298.776554     659.316614

==================== Mildura: CESM2, ssp126, 2061-2080 ====================
==================== Mildura: CESM2, ssp370, 2021-2040 ====================
==================== Mildura: CESM2, ssp370, 2041-2060 ====================
==================== Mildura: CESM2, ssp370, 2061-2080 ====================
==================== Mildura: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Mildura: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Mildura: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Mildura: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Mildura: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Mildura: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Mildura: EC-Earth3, ssp126, 2021-2040 ====================
==================== Mildura: EC-Earth3, ssp126, 2041-2060 ====================
==================== Mildura: EC-Earth3, ssp126, 2061-2080 ====================
==================== Mildura: EC-Earth3, ssp370, 2021-2040 ====================
==================== Mildura: EC-Earth3, ssp370, 2041-2060 ====================
==================== Mildura: EC-Earth3, ssp370, 2061-2080 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Mildura: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Mildura: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Mildura: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Mildura: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Mildura: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Mildura: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Mildura: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Perth: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Perth: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      292.833521       0.008141       4.191730  101444.985505      -0.998992       0.845098      37.328258     231.290300     248.294533      60.192128
std         6.977422       0.002436       2.667834     639.213844       3.646598       2.332283      38.406605     318.260818     366.884798      92.723363
min       272.660164       0.001222       0.000000   98770.704226     -11.823242     -11.018555       0.000000       0.000000       0.000000       0.000000
25%       287.922740       0.006350       2.387101  100992.760041      -3.735352      -0.611328       0.000000       0.000000       0.000000       0.000000
50%       292.279420       0.007933       4.048898  101417.575402      -0.851562       0.910156      24.255859      10.650391       0.000000       0.000000
75%       297.222125       0.009668       6.030334  101863.320497       1.635742       2.443359      76.398438     430.520508     544.729462      87.943804
max       318.675265       0.024054      19.374535  103966.894686      12.424805       9.255859     100.000000    1144.203125    1274.070862     705.423788

==================== Perth: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Perth: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Perth: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Perth: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Perth: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175319.000000  175320.000000
mean      292.590107       0.008107       4.194033  101427.443715      -0.718762       0.930833      33.285336     235.935309     247.121936      60.832375
std         6.923640       0.002376       2.695211     595.116466       3.672464       2.267001      37.187340     322.150218     365.706579      93.306380
min       272.733999       0.001204       0.000000   98960.344859     -13.005859     -12.589844       0.000000       0.000000       0.000000       0.000000
25%       287.754227       0.006380       2.345688  100998.769172      -3.349609      -0.479492       0.000000       0.000000       0.000000       0.000000
50%       291.937883       0.007890       4.048361  101396.267758      -0.632812       0.984375      16.302734      10.906250       0.000000       0.000000
75%       296.766100       0.009595       6.056389  101821.942287       1.958984       2.485352      68.033203     442.948242     536.802865      89.826643
max       318.261768       0.024475      19.165558  103758.663177      11.647461       9.500977     100.000000    1149.355469    1295.071759     667.273271

==================== Perth: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      292.393945       0.007885       4.226494  101422.868911      -0.776265       0.946198      32.737228     236.851833     248.207213      60.725203
std         6.876744       0.002331       2.700380     616.029354       3.698000       2.260119      37.060526     322.830734     365.898280      92.733213
min       272.720625       0.001206       0.000000   98831.232559     -11.649414     -11.021484       0.000000       0.000000       0.000000       0.000000
25%       287.588616       0.006169       2.382709  100977.108170      -3.454102      -0.475586       0.000000       0.000000       0.000000       0.000000
50%       291.771449       0.007666       4.108083  101391.082746      -0.686523       0.996094      14.810547      10.929688       0.000000       0.000000
75%       296.616682       0.009351       6.086545  101832.360495       1.939453       2.492188      66.912109     446.200195     539.702679      90.351522
max       318.337966       0.024138      18.743310  103885.393517      10.932617       8.934570     100.000000    1145.121094    1298.143024     687.516520

==================== Perth: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Perth: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Perth: CESM2, ssp126, 2021-2040 ====================
==================== Perth: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175183.000000
mean      292.831173       0.008216       4.133259  101475.292234      -0.952538       1.082162      33.465080     235.717708     249.674886      59.843940
std         6.759349       0.002327       2.640770     592.972916       3.664108       2.355981      37.289132     323.129600     367.977928      90.841146
min       273.595934       0.001407       0.000000   99076.112669     -11.798828      -9.924805       0.000000       0.000000       0.000000       0.000000
25%       288.123815       0.006483       2.329408  101048.206052      -3.627930      -0.432617       0.000000       0.000000       0.000000       0.000000
50%       292.274889       0.008037       3.943410  101448.009087      -0.788086       1.161133      16.648438      10.837891       0.000000       0.000000
75%       296.940277       0.009720       5.959605  101863.898775       1.654297       2.734375      68.726562     439.043945     547.405421      89.046025
max       318.656093       0.021762      18.327697  103583.857346      11.729492       9.788086     100.000000    1135.039062    1293.409224     673.954358

==================== Perth: CESM2, ssp126, 2061-2080 ====================
==================== Perth: CESM2, ssp370, 2021-2040 ====================
==================== Perth: CESM2, ssp370, 2041-2060 ====================
==================== Perth: CESM2, ssp370, 2061-2080 ====================
==================== Perth: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Perth: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Perth: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Perth: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Perth: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Perth: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Perth: EC-Earth3, ssp126, 2021-2040 ====================
==================== Perth: EC-Earth3, ssp126, 2041-2060 ====================
==================== Perth: EC-Earth3, ssp126, 2061-2080 ====================
==================== Perth: EC-Earth3, ssp370, 2021-2040 ====================
==================== Perth: EC-Earth3, ssp370, 2041-2060 ====================
==================== Perth: EC-Earth3, ssp370, 2061-2080 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Perth: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Perth: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Perth: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Perth: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Perth: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Perth: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Perth: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Perth: NorESM2-MM, ssp370, 2061-2080 ====================
==================== Sydney: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Sydney: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175310.000000  175320.000000
mean      292.798302       0.009915       5.271279  101737.695269       0.082019       0.298230      45.042892     206.475406     200.970026      69.998909
std         5.047811       0.003547       2.865859     693.586765       2.280821       2.601670      39.928690     286.804046     325.814928     107.493189
min       277.200428       0.000991       0.000000   98711.223143      -8.546875      -9.135742       0.000000       0.000000       0.000000       0.000000
25%       289.294434       0.007106       3.120300  101275.537716      -1.470703      -1.740234       0.218750       0.000000       0.000000       0.000000
50%       293.007278       0.009747       4.735636  101746.155787       0.045898       0.197266      39.290039       7.812500       0.000000       0.000000
75%       296.268524       0.012617       7.179900  102203.905803       1.403320       2.016602      88.851562     389.957031     317.703390      98.567028
max       320.249107       0.021515      86.393423  104053.788028      11.456055      10.193359     100.000000    1134.398438    1286.697063     685.521839

==================== Sydney: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Sydney: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Sydney: ACCESS-CM2, ssp370, 2041-2060 ====================
==================== Sydney: ACCESS-CM2, ssp370, 2061-2080 ====================
==================== Sydney: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
==================== Sydney: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
==================== Sydney: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175224.000000  175224.000000  175224.000000  175224.000000  175315.000000  175320.000000
mean      292.547757       0.009295       5.429832  101691.152826       0.031770       0.146613      40.729729     211.112852     206.421288      68.636403
std         5.125630       0.003309       2.954457     726.854834       2.280726       2.628517      39.606271     290.722450     330.798155     105.671051
min       276.585532       0.000997       0.000000   98424.646660      -7.165039      -8.181641       0.000000       0.000000       0.000000       0.000000
25%       289.026210       0.006704       3.171110  101200.465823      -1.537109      -1.909180       0.000000       0.000000       0.000000       0.000000
50%       292.674051       0.009106       4.873198  101741.545069      -0.030273      -0.032227      28.261719       8.130859       0.000000       0.000000
75%       295.872843       0.011644       7.375065  102222.097710       1.342773       1.844727      83.853516     404.137695     338.942762      96.616752
max       321.316831       0.020600      88.245624  104013.733307      11.958984      11.569336     100.000000    1133.109375    1295.448631     695.597206

==================== Sydney: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175320.000000  175320.000000  175320.000000  175320.000000  175272.000000  175272.000000  175272.000000  175272.000000  175319.000000  175320.000000
mean      292.368340       0.009298       5.372589  101659.959392       0.029983       0.133704      41.611471     209.830443     204.429530      68.790136
std         5.180563       0.003361       2.918417     721.173179       2.287112       2.572600      39.810640     290.210463     329.196021     105.281505
min       276.186946       0.001099       0.000000   98109.328687      -7.608398      -8.153320       0.000000       0.000000       0.000000       0.000000
25%       288.738618       0.006607       3.156332  101181.800171      -1.539062      -1.861328       0.000000       0.000000       0.000000       0.000000
50%       292.505073       0.009108       4.831606  101699.567905      -0.024414      -0.038574      30.220703       7.968750       0.000000       0.000000
75%       295.848537       0.011797       7.276444  102171.940461       1.375977       1.799805      85.285645     399.907227     332.373375      98.215691
max       319.887292       0.019799      83.812563  103732.845938      10.930664      12.626953     100.000000    1122.343750    1292.421917     683.354490

==================== Sydney: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
==================== Sydney: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
==================== Sydney: CESM2, ssp126, 2021-2040 ====================
==================== Sydney: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged

                 tas           huss        sfcWind            psl            uas            vas            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  166440.000000  175200.000000  175194.000000
mean      293.058195       0.009762       5.349598  101721.497987       0.098819       0.456339      44.429320     206.404806     208.417499      68.738182
std         5.149735       0.003397       2.920050     718.111819       2.296954       2.661743      39.839572     285.784495     333.346739     105.548939
min       277.314095       0.001078       0.000000   98551.912038      -9.519531      -8.971680       0.000000       0.000000       0.000000       0.000000
25%       289.476439       0.007082       3.129902  101243.471782      -1.475586      -1.621094       0.074219       0.000000       0.000000       0.000000
50%       293.257164       0.009661       4.801595  101737.699451       0.067383       0.399414      37.580078       7.666016       0.000000       0.000000
75%       296.455516       0.012379       7.288040  102217.694804       1.409180       2.210938      88.285156     391.297852     348.761426      96.453629
max       320.786767       0.020519      91.625561  104111.995900      11.110352      11.063477     100.000000    1118.656250    1298.289686     711.197684

==================== Sydney: CESM2, ssp126, 2061-2080 ====================
==================== Sydney: CESM2, ssp370, 2021-2040 ====================
==================== Sydney: CESM2, ssp370, 2041-2060 ====================
==================== Sydney: CESM2, ssp370, 2061-2080 ====================
==================== Sydney: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Sydney: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Sydney: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Sydney: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Sydney: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Sydney: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Sydney: EC-Earth3, ssp126, 2021-2040 ====================
==================== Sydney: EC-Earth3, ssp126, 2041-2060 ====================
==================== Sydney: EC-Earth3, ssp126, 2061-2080 ====================
==================== Sydney: EC-Earth3, ssp370, 2021-2040 ====================
==================== Sydney: EC-Earth3, ssp370, 2041-2060 ====================
==================== Sydney: EC-Earth3, ssp370, 2061-2080 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Sydney: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
==================== Sydney: NorESM2-MM, ssp126, 2021-2040 ====================
==================== Sydney: NorESM2-MM, ssp126, 2041-2060 ====================
==================== Sydney: NorESM2-MM, ssp126, 2061-2080 ====================
==================== Sydney: NorESM2-MM, ssp370, 2021-2040 ====================
==================== Sydney: NorESM2-MM, ssp370, 2041-2060 ====================
==================== Sydney: NorESM2-MM, ssp370, 2061-2080 ====================

=== QC summary (all files) ===

                                                  file       loc       model     ssp time_period   n_min  any_nan  any_const  rsds_min     rsds_max
0    Adelaide_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp126   2021-2040  175320    False      False       0.0  1133.582031
1    Adelaide_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp126   2041-2060  175272     True      False       0.0  1125.656250
2    Adelaide_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp126   2061-2080  175320    False      False       0.0  1127.695312
3    Adelaide_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp370   2021-2040  175320    False      False       0.0  1123.550781
4    Adelaide_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BOM...  Adelaide  ACCESS-CM2  ssp370   2041-2060  175320    False      False       0.0  1125.070312
..                                                 ...       ...         ...     ...         ...     ...      ...        ...       ...          ...
457  Sydney_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp126   2041-2060  175200    False      False       0.0  1127.769531
458  Sydney_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp126   2061-2080  175200    False      False       0.0  1124.964844
459  Sydney_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp370   2021-2040  175200    False      False       0.0  1132.242188
460  Sydney_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp370   2041-2060  175200    False      False       0.0  1125.160156
461  Sydney_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BOM_B...    Sydney  NorESM2-MM  ssp370   2061-2080  175200    False      False       0.0  1111.792969

[462 rows x 10 columns]

In [ ]:
# for file in files:
#     base = file.split('/')[-1]
#     loc = base.split('_')[0]
#     model = base.split('_')[2]
#     ssp = base.split('_')[3]
#     time_period = base.split('_')[9]
#     print(f"========================== {loc}: {model}, {ssp}, {time_period} ==========================")
#     da = xr.open_dataset(file)
#     print(da.drop_vars([v for v in ["time_offset","round_method",
#                                     "crs", "lat", "lon"] if v in da.variables])[vars_to_summarise].to_dataframe().describe())