# Checking output files

In [2]:
from datetime import datetime, timedelta
import calendar
import collections
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os
import sys

import glob
import pandas as pd
import xarray as xr
from IPython.display import display, HTML

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)


my_dir = "/g/data/eg3/spr548/projects/"
sys.path.append(os.path.join(my_dir, "nesp_bff")+os.sep)
from nathers import location_details

# import utils
# from utils import locations, model_dict, vars_1hr, vars_day

In [34]:
step = "step3"
show_only_if_flagged = False

#==========================================
root_dir = "/g/data/eg3/nesp_bff/"
# location = "Sydney"
# scenario = "ssp370"
# model = "CESM2"
# time_period = "2041-2060"
vars_to_summarise_step2 = ["tas","huss","sfcWind","psl","rsds","rsdsdir","rsdsdif"]
vars_to_summarise_step3 = ["tas","twbt","huss","psl","wind_speed","wind_dir","clt","rsds","rsdsdir","rsdsdif"]
locations = ["Darwin","Cairns","Brisbane","Longreach","Mildura","Adelaide","Perth","Sydney","Melbourne","Canberra","Hobart"]
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]

input_dir = f"{root_dir}step3_calc_missing_vars/" if step == "step3" else f"{root_dir}step2_qdc_scaling/BARPA-R/"
vars_to_summarise = vars_to_summarise_step3 if step == "step3" else vars_to_summarise_step2

In [35]:
files = glob.glob(f"{input_dir}*.nc")
len(files)

42

In [38]:
# # Old checkds
# qc_rows = []
# errors = []

# for file in sorted(files):
#     base = file.split("/")[-1]
#     parts = base.split("_")

#     loc = parts[0] if len(parts) > 0 else None
#     model_ = parts[2] if len(parts) > 2 else None
#     ssp = parts[3] if len(parts) > 3 else None
#     time_period_ = parts[9] if len(parts) > 9 else None

#     header = f"{loc}: {model_}, {ssp}, {time_period_}"
#     print(f"==================== {header} ====================")

#     try:
#         with xr.open_dataset(file) as da:
#             df = (
#                 da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
#                   [vars_to_summarise]
#                   .to_dataframe()
#             )

#         desc = df.describe()

#         flagged = df.isna().any().any() or (df.nunique(dropna=True) <= 1).any()

#         if (not show_only_if_flagged) or flagged:
#             print("⚠️ Flagged" if flagged else "OK")
#             display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
#             display(desc)
#             display(HTML("</div>"))

#         qc_rows.append({
#             "file": base,
#             "loc": loc,
#             "model": model_,
#             "ssp": ssp,
#             "time_period": time_period_,
#             "n_min": int(desc.loc["count"].min()),
#             "any_nan": bool(df.isna().any().any()),
#             "any_const": bool((df.nunique(dropna=True) <= 1).any()),
#             "rsds_min": float(desc.loc["min", "rsds"]) if "rsds" in desc.columns else None,
#             "rsds_max": float(desc.loc["max", "rsds"]) if "rsds" in desc.columns else None,
#         })

#     except Exception as e:
#         errors.append({
#             "file": base,
#             "loc": loc,
#             "model": model_,
#             "ssp": ssp,
#             "time_period": time_period_,
#             "error": repr(e),
#         })

# qc_df = pd.DataFrame(qc_rows)
# err_df = pd.DataFrame(errors)

# print("\n=== QC summary (all files) ===")
# display(qc_df)

# if not err_df.empty:
#     print("\n=== Errors ===")
#     display(err_df)

In [40]:
vars_maybe_drop = ["time_offset", "round_method", "crs", "lat", "lon"]
show_only_if_flagged = True
RANGES = {
   # temps: keep the K→C heuristic because files might still be in K
   "tas":  {"min": -60, "max":  60, "units": "C_or_K"},
   "twbt": {"min": -60, "max":  60, "units": "C_or_K"},
   # specific humidity (g/kg)
   "huss": {"min": 0.0, "max": 40., "units": "g/kg"},
   # sea level pressure in kPa (typical ~ 90–110 kPa; give generous bounds)
   "psl":  {"min": 80.0, "max": 110.0, "units": "kPa"},
   # wind speed (m/s)
   "wind_speed": {"min": 0.0, "max": 60.0, "units": "m/s"},
   # 16-point direction code (0..16). If you treat 0 as calm, keep it allowed.
   "wind_dir": {"min": 0.0, "max": 16.0, "units": "dir16"},
   # cloud cover in oktas (0..8)
   "clt": {"min": 0.0, "max": 8.0, "units": "oktas"},
   # radiation (W/m²)
   "rsds":    {"min": 0.0, "max": 1300.0, "units": "W/m2"},
   "rsdsdir": {"min": 0.0, "max": 1300.0, "units": "W/m2"},
   "rsdsdif": {"min": 0.0, "max": 1300.0, "units": "W/m2"},
}

def _convert_for_check(var, vmin, vmax):
    rule = RANGES.get(var)
    if rule is None:
        return vmin, vmax, None, None, None
    rmin, rmax = rule["min"], rule["max"]
    note = None
    # Temperature heuristic: if values look like Kelvin, convert to Celsius for checking
    if var in ("tas", "twbt"):
        if np.isfinite(vmax) and vmax > 150:  # likely Kelvin
            vmin = vmin - 273.15
            vmax = vmax - 273.15
            note = "converted K→C (heuristic)"
    return vmin, vmax, rmin, rmax, note

def flag_df(df, desc, vars_to_check):
   reasons = []
   # NaN + constant checks (overall)
   if df[vars_to_check].isna().any().any():
       reasons.append("has NaNs")
   if (df[vars_to_check].nunique(dropna=True) <= 1).any():
       const_vars = list(df[vars_to_check].columns[(df[vars_to_check].nunique(dropna=True) <= 1)])
       reasons.append(f"constant: {const_vars[:5]}" + ("..." if len(const_vars) > 5 else ""))
   # Range checks per variable
   for v in vars_to_check:
       if v not in desc.columns:
           reasons.append(f"missing column: {v}")
           continue
       vmin = desc.loc["min", v]
       vmax = desc.loc["max", v]
       vmin2, vmax2, rmin, rmax, note = _convert_for_check(v, vmin, vmax)
       if rmin is None:
           continue
       out_low = np.isfinite(vmin2) and (vmin2 < rmin)
       out_high = np.isfinite(vmax2) and (vmax2 > rmax)
       if out_low or out_high:
           msg = f"{v} out of range [{rmin}, {rmax}]"
           if out_low:
               msg += f" (min={vmin2:.3g})"
           if out_high:
               msg += f" (max={vmax2:.3g})"
           if note:
               msg += f" [{note}]"
           reasons.append(msg)
   return reasons

qc_rows, errors = [], []
for file in sorted(files):
   base = file.split("/")[-1]
   parts = base.split("_")
   loc = parts[0] if len(parts) > 0 else None
   model_ = parts[2] if len(parts) > 2 else None
   ssp = parts[3] if len(parts) > 3 else None
   time_period_ = parts[9] if len(parts) > 9 else None
   header = f"{loc}: {model_}, {ssp}, {time_period_}"
   print(f"==================== {header} ====================")
   try:
       with xr.open_dataset(file) as da:
           df = (
               da.drop_vars([v for v in vars_maybe_drop if v in da.variables])
                 [vars_to_summarise]
                 .to_dataframe()
           )
       desc = df.describe()
       reasons = flag_df(df, desc, vars_to_summarise)
       flagged = len(reasons) > 0
       if (not show_only_if_flagged) or flagged:
           print("⚠️ Flagged" if flagged else "OK")
           if flagged:
               print("Reasons:", "; ".join(reasons[:6]) + (" ..." if len(reasons) > 6 else ""))
           display(HTML('<div style="overflow-x:auto; max-width:100%;">'))
           display(desc)
           display(HTML("</div>"))
       qc_rows.append({
           "file": base,
           "loc": loc,
           "model": model_,
           "ssp": ssp,
           "time_period": time_period_,
           "flagged": flagged,
           "flag_reason": "; ".join(reasons[:8]) + (" ..." if len(reasons) > 8 else ""),
           "n_min": int(desc.loc["count"].min()),
           "any_nan": bool(df.isna().any().any()),
           "any_const": bool((df.nunique(dropna=True) <= 1).any()),
       })
   except Exception as e:
       errors.append({
           "file": base,
           "loc": loc,
           "model": model_,
           "ssp": ssp,
           "time_period": time_period_,
           "error": repr(e),
       })
qc_df = pd.DataFrame(qc_rows)
err_df = pd.DataFrame(errors)
display(qc_df.sort_values(["flagged", "loc", "model"], ascending=[False, True, True]))
if not err_df.empty:
   display(err_df)

==================== Melbourne: ACCESS-CM2, ssp126, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=60.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.531325      11.811526       7.376869     100.381027       5.033895      11.070873       5.530114     178.273987     197.229126      60.457741
std         6.198773       4.013904       2.264378       0.749708       2.951959       4.549204       2.366922     267.716064     260.492004      83.693253
min        -0.103054      -0.651840       1.010355      96.607674       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.161758       8.897761       5.739625      99.915327       2.932193       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.571415      11.420112       6.927511     100.386803       4.557750      12.000000       6.000000       5.000000       0.000000       3.533095
75%        18.865087      14.537907       8.583199     100.869034       6.734211      16.000000       8.000000     292.145226     386.395157     108.606462
max        46.054981      31.133121      22.816242     102.893982      60.722473      16.000000       8.000000    1160.785400    1199.771606     384.553467

==================== Melbourne: ACCESS-CM2, ssp126, 2061-2080 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2021-2040 ====================
==================== Melbourne: ACCESS-CM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62.4)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.102825      12.261433       7.584716     100.425217       5.033574      11.070873       5.530114     179.911774     201.527191      59.421043
std         6.195697       3.982809       2.295161       0.750465       2.917476       4.549204       2.366922     269.445343     265.448059      81.616379
min        -0.330783      -0.876673       1.253946      96.768875       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.741392       9.379382       5.917593      99.958336       2.937562       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.206291      11.938084       7.141523     100.411938       4.572999      12.000000       6.000000       5.000000       0.000000       3.575004
75%        19.463557      14.981495       8.826676     100.919550       6.763319      16.000000       8.000000     295.530464     396.907028     107.881886
max        46.024250      30.911898      22.242794     102.889420      62.408310      16.000000       8.000000    1156.264282    1197.048340     386.100403

==================== Melbourne: ACCESS-CM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=67.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.295013      13.239286       8.100165     100.453812       5.021338      11.070873       5.530114     182.291245     208.625412      57.972675
std         6.283189       4.004872       2.475118       0.742287       2.964911       4.549204       2.366922     270.723358     272.319550      78.908920
min         1.007026       0.254081       1.359668      96.731865       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.880138      10.344679       6.307106      99.976494       2.864297       8.000000       3.000000       0.000000       0.000000       0.000000
50%        16.380933      12.928984       7.642319     100.463440       4.516448      12.000000       6.000000       5.000000       0.000000       3.536509
75%        20.707258      15.973498       9.430471     100.947010       6.786067      16.000000       8.000000     303.197510     416.881943     106.780920
max        48.716286      32.144634      24.352167     103.073837      67.160454      16.000000       8.000000    1147.663330    1197.025391     362.227722

==================== Melbourne: ACCESS-ESM1-5, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.828556      11.114563       6.954268     100.316254       5.152277      11.070873       5.530114     176.140991     199.093445      57.018738
std         6.093755       3.789683       1.994021       0.774577       2.996179       4.549204       2.366922     265.821716     264.405090      78.524094
min        -0.347352      -0.767189       1.131052      96.669197       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.598959       8.426037       5.543543      99.811794       3.019137       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.876400      10.751985       6.588119     100.362915       4.711369      12.000000       6.000000       5.000000       0.000000       3.544888
75%        17.954703      13.639334       7.973189     100.857521       6.924413      16.000000       8.000000     286.340675     385.975510     102.705109
max        46.912033      28.745781      19.555138     102.676300      63.076942      16.000000       8.000000    1160.641602    1220.037964     383.724365

==================== Melbourne: ACCESS-ESM1-5, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.146629      11.370245       7.072396     100.346336       5.152930      11.070873       5.530114     177.240799     201.031509      56.971783
std         6.091629       3.800953       2.057911       0.758243       2.970427       4.549204       2.366922     266.582825     265.911469      78.123215
min        -0.261397      -0.497062       1.156457      96.670677       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.864138       8.654508       5.629183      99.849119       3.054982       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.189798      11.003727       6.684732     100.386314       4.742246      12.000000       6.000000       5.000000       0.000000       3.548948
75%        18.304509      13.877388       8.086638     100.875259       6.894587      16.000000       8.000000     290.507889     390.862114     103.644030
max        45.978588      29.814081      21.138041     102.818398      66.025017      16.000000       8.000000    1159.939697    1203.588379     383.286407

==================== Melbourne: ACCESS-ESM1-5, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=69.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.100798      11.310390       7.028278     100.322853       5.215484      11.070873       5.530114     177.495087     202.250504      56.695320
std         6.101746       3.755262       1.995199       0.769000       3.020826       4.549204       2.366922     267.024506     267.446899      77.713150
min         0.027173      -0.360411       1.017489      96.773369       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.849519       8.655432       5.631540      99.826332       3.097646       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.111368      10.949427       6.672438     100.371933       4.759102      12.000000       6.000000       5.000000       0.000000       3.500546
75%        18.240057      13.781954       8.035152     100.856285       6.963042      16.000000       8.000000     290.138870     392.675972     102.870564
max        46.550621      29.282137      19.659599     102.582878      69.228134      16.000000       8.000000    1162.125732    1227.623535     367.702454

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=65.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.976366      11.285618       7.082135     100.291641       5.141773      11.070873       5.530114     175.341019     197.054276      57.664921
std         6.171349       3.928288       2.140351       0.764331       2.982071       4.549204       2.366922     264.301544     261.278595      79.740746
min        -0.825777      -0.994830       1.153015      96.760666       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.673354       8.473479       5.563166      99.786680       3.021962       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.985590      10.877410       6.674997     100.328377       4.691540      12.000000       6.000000       5.000000       0.000000       3.545967
75%        18.184857      13.856338       8.127063     100.831804       6.913312      16.000000       8.000000     285.809349     382.354820     103.695465
max        46.032303      30.046921      21.127144     102.560417      65.330750      16.000000       8.000000    1158.484131    1170.394287     374.841644

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.642995      11.706628       7.209986     100.311165       5.191436      11.070873       5.530114     178.293030     203.772827      56.271217
std         6.233574       3.860063       2.114691       0.753085       2.961069       4.549204       2.366922     267.496124     269.346558      76.668312
min         0.368887      -0.375447       1.006666      96.727852       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.284374       8.945027       5.713188      99.810806       3.122939       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.667941      11.331360       6.832084     100.342907       4.770742      12.000000       6.000000       5.000000       0.000000       3.582899
75%        18.883723      14.281660       8.296448     100.828295       6.910652      16.000000       8.000000     292.990280     397.581169     102.905680
max        46.413994      29.768307      20.087963     102.531693      63.718647      16.000000       8.000000    1159.421631    1224.052856     389.263275

==================== Melbourne: ACCESS-ESM1-5, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.4)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.189083      12.130075       7.407357     100.360031       5.121290      11.070873       5.530114     179.314331     206.943680      55.607700
std         6.205415       3.880510       2.223178       0.764910       2.952823       4.549204       2.366922     267.747101     271.957245      75.194191
min         0.818206       0.002908       1.222068      96.575180       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.876985       9.354051       5.826601      99.862831       3.041771       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.215612      11.760901       7.001882     100.388893       4.689630      12.000000       6.000000       5.000000       0.000000       3.521764
75%        19.377103      14.722853       8.557958     100.895901       6.862641      16.000000       8.000000     296.657967     405.377205     102.686550
max        48.489529      30.728973      22.301615     102.751671      66.392021      16.000000       8.000000    1152.685791    1192.319824     375.743225

==================== Melbourne: CESM2, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.618358      11.703814       7.222283     100.359779       5.073233      11.070873       5.530114     180.402451     197.145279      62.330433
std         6.365462       3.924424       2.115022       0.756759       2.934424       4.549204       2.366922     269.894409     260.945282      85.524086
min        -0.426962      -0.873275       0.837922      96.631165       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.180049       8.904491       5.721475      99.854332       2.987837       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.608016      11.364785       6.840560     100.373226       4.648071      12.000000       6.000000       5.000000       0.000000       3.735887
75%        18.877897      14.291894       8.315405     100.899633       6.850813      16.000000       8.000000     297.057686     384.317146     113.545074
max        46.799583      29.863213      21.101799     102.654182      63.300911      16.000000       8.000000    1158.924438    1165.750366     406.958771

==================== Melbourne: CESM2, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=67)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.553931      11.659492       7.185046     100.367546       5.072341      11.070873       5.530114     180.689713     197.080963      62.863831
std         6.229958       3.784946       2.029095       0.760595       2.915873       4.549204       2.366922     269.925568     260.211029      86.372940
min         0.219515      -0.643884       1.021190      96.655914       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.252685       8.983154       5.754029      99.872574       3.034920       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.574792      11.343253       6.827004     100.387360       4.653752      12.000000       6.000000       5.000000       0.000000       3.694802
75%        18.638746      14.159052       8.257898     100.893114       6.752570      16.000000       8.000000     298.119904     383.984840     114.291817
max        46.457722      29.028280      20.292112     102.871284      66.989769      16.000000       8.000000    1155.500122    1169.142456     402.869568

==================== Melbourne: CESM2, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=68.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.027107      12.085685       7.414402     100.398422       5.013665      11.070873       5.530114     181.493576     199.929794      61.888512
std         6.287432       3.805638       2.071223       0.746127       2.910845       4.549204       2.366922     270.781799     263.972809      84.678627
min         0.077331      -0.283639       1.042457      97.012749       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.642377       9.381410       5.941912      99.905077       2.963319       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.036129      11.782180       7.071749     100.411491       4.561976      12.000000       6.000000       5.000000       0.000000       3.641279
75%        19.217131      14.635338       8.523678     100.913704       6.738763      16.000000       8.000000     299.492050     390.650452     113.470251
max        48.034401      29.924196      21.772764     102.893127      68.064842      16.000000       8.000000    1159.782715    1173.127808     402.996185

==================== Melbourne: CESM2, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=67.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.409580      11.577477       7.168341     100.346313       5.074358      11.070873       5.530114     180.106583     196.439148      62.615238
std         6.232045       3.812105       2.034837       0.756661       2.939443       4.549204       2.366922     269.409241     260.655060      86.445518
min        -0.455841      -0.943575       1.000136      96.336159       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.132881       8.887928       5.726488      99.851044       2.986642       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.430491      11.258000       6.813195     100.380409       4.645736      12.000000       6.000000       5.000000       0.000000       3.667901
75%        18.554040      14.100168       8.221919     100.861614       6.814796      16.000000       8.000000     297.315300     382.599304     114.043434
max        46.991314      29.282770      20.596077     102.634483      67.812027      16.000000       8.000000    1158.424561    1162.072632     401.506348

==================== Melbourne: CESM2, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.277424      12.312138       7.544550     100.400734       5.004336      11.070873       5.530114     182.377411     202.317444      61.163937
std         6.338521       3.844607       2.130901       0.735269       2.902263       4.549204       2.366922     271.816345     267.014160      83.315300
min         0.384992      -0.149693       1.244955      96.840286       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.862821       9.577934       6.019371      99.897079       2.934524       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.304787      12.023890       7.179664     100.413010       4.559248      12.000000       6.000000       5.000000       0.000000       3.685541
75%        19.548050      14.911494       8.693742     100.913872       6.740254      16.000000       8.000000     302.206940     396.907547     113.024843
max        48.848351      30.212254      20.924976     102.773911      66.780159      16.000000       8.000000    1156.783081    1141.474121     385.536438

==================== Melbourne: CESM2, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=71.8)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       17.149942      13.087029       7.988649     100.402092       4.929635      11.070873       5.530114     183.849945     207.137085      60.076534
std         6.367422       3.904778       2.321764       0.739396       2.903679       4.549204       2.366922     272.904755     272.059692      81.523598
min         1.097703       0.217507       1.279093      96.502502       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        12.710685      10.298894       6.313870      99.905987       2.821319       8.000000       3.000000       0.000000       0.000000       0.000000
50%        16.230586      12.826896       7.594050     100.408012       4.447280      12.000000       6.000000       5.000000       0.000000       3.671432
75%        20.432032      15.756885       9.244027     100.918625       6.655531      16.000000       8.000000     306.901352     410.187683     111.957632
max        49.033020      30.850632      22.706730     102.803864      71.752548      16.000000       8.000000    1153.207275    1155.737427     375.518799

==================== Melbourne: CMCC-ESM2, ssp126, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp126, 2061-2080 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2021-2040 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2041-2060 ====================
==================== Melbourne: CMCC-ESM2, ssp370, 2061-2080 ====================
==================== Melbourne: EC-Earth3, ssp126, 2021-2040 ====================
==================== Melbourne: EC-Earth3, ssp126, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=64.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.379117      11.759018       7.381169     100.302284       5.110409      11.070873       5.530114     176.906204     205.732971      54.144508
std         6.167104       3.921571       2.196122       0.741903       2.971378       4.549204       2.366922     266.077881     271.369202      74.533005
min        -0.513657      -0.955252       1.209546      96.738525       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.099408       8.963434       5.824327      99.826553       3.010650       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.417142      11.357460       6.940514     100.329262       4.663867      12.000000       6.000000       5.000000       0.000000       3.472311
75%        18.617810      14.360280       8.481630     100.813065       6.853568      16.000000       8.000000     289.666878     403.137871      98.235682
max        48.870899      30.389820      20.448885     102.651031      64.113052      16.000000       8.000000    1152.597656    1263.718140     377.394135

==================== Melbourne: EC-Earth3, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.007277      11.498501       7.256409     100.298439       5.089129      11.070873       5.530114     175.957642     202.826462      54.739784
std         5.919363       3.763982       2.115470       0.741400       2.988323       4.549204       2.366922     265.242920     268.551361      75.474159
min        -0.291945      -0.690658       0.996118      96.865974       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.894992       8.840771       5.783357      99.807716       2.978769       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.087896      11.127792       6.871181     100.318207       4.644180      12.000000       6.000000       5.000000       0.000000       3.478921
75%        18.122639      13.957282       8.275850     100.823816       6.831309      16.000000       8.000000     286.274658     396.091270      99.073269
max        46.386269      31.353874      23.014818     102.531380      62.082966      16.000000       8.000000    1153.969238    1270.263306     382.604126

==================== Melbourne: EC-Earth3, ssp370, 2041-2060 ====================
==================== Melbourne: EC-Earth3, ssp370, 2061-2080 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.010630      11.318649       7.095140     100.266678       5.099665      11.070873       5.530114     177.841736     194.038010      61.681107
std         6.102441       3.887536       2.083079       0.717385       2.945330       4.549204       2.366922     266.895233     257.644440      85.333916
min        -0.800102      -1.317492       1.091066      96.764015       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.721417       8.499355       5.614222      99.821081       2.989467       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.035348      10.964333       6.712484     100.293434       4.676203      12.000000       6.000000       5.000000       0.000000       3.670185
75%        18.274302      13.948295       8.182140     100.751545       6.880129      16.000000       8.000000     292.579514     377.563889     111.698244
max        47.005581      30.052673      22.415030     102.579636      63.096943      16.000000       8.000000    1158.712036    1179.791138     398.966125

==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=64.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.939062      11.253831       7.051738     100.274200       5.142421      11.070873       5.530114     177.531219     193.047150      61.971600
std         6.096351       3.824584       2.020216       0.739462       2.954115       4.549204       2.366922     266.568146     256.454468      85.877457
min        -0.761103      -1.357618       1.068552      96.717186       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.680860       8.493986       5.619788      99.803505       3.043009       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.028439      10.946495       6.692413     100.298386       4.705102      12.000000       6.000000       5.000000       0.000000       3.684438
75%        18.068648      13.850190       8.112788     100.787872       6.929862      16.000000       8.000000     291.443573     374.797844     111.835901
max        47.494614      29.919510      20.639996     102.620354      64.139435      16.000000       8.000000    1159.631226    1156.849731     407.706757

==================== Melbourne: MPI-ESM1-2-HR, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=65.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.045078      11.299865       7.046026     100.255524       5.152332      11.070873       5.530114     177.209137     193.270111      61.982456
std         6.080519       3.754251       1.978213       0.750326       2.984864       4.549204       2.366922     265.958466     256.157623      86.304977
min        -0.294435      -1.090013       1.073083      96.663956       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.844420       8.638255       5.655499      99.791462       3.046429       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.079565      10.982233       6.726159     100.267883       4.717704      12.000000       6.000000       5.000000       0.000000       3.646026
75%        18.123494      13.778832       8.083613     100.753658       6.906268      16.000000       8.000000     290.934433     376.129181     111.106161
max        49.065086      30.818733      20.679546     102.893700      65.127029      16.000000       8.000000    1158.171753    1170.046753     414.415405

==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.2)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.641752      11.049652       6.974258     100.275688       5.152061      11.070873       5.530114     176.404495     190.406006      62.432705
std         5.988352       3.811095       2.033363       0.745778       2.963718       4.549204       2.366922     265.362488     253.596436      86.813782
min        -0.657534      -1.088343       1.111232      96.782913       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.468550       8.310267       5.541519      99.801733       3.045237       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.734991      10.723775       6.603927     100.291935       4.710205      12.000000       6.000000       5.000000       0.000000       3.668579
75%        17.755959      13.622129       8.004312     100.784599       6.944489      16.000000       8.000000     287.925362     367.018295     111.916128
max        47.198418      30.106237      22.136194     102.598816      63.169559      16.000000       8.000000    1159.717529    1177.044312     418.088226

==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2041-2060 ====================
==================== Melbourne: MPI-ESM1-2-HR, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=63.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       16.094948      12.082659       7.410778     100.299599       5.133793      11.070873       5.530114     182.389282     205.616486      59.506870
std         6.275306       3.934172       2.216873       0.757223       2.976959       4.549204       2.366922     270.962616     269.743774      81.126572
min        -0.008120      -0.613467       1.124660      96.767090       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.664053       9.226855       5.854141      99.823576       3.015595       8.000000       3.000000       0.000000       0.000000       0.000000
50%        15.106494      11.704772       6.987552     100.319221       4.691563      12.000000       6.000000       5.000000       0.000000       3.574983
75%        19.398636      14.754706       8.560213     100.805370       6.905490      16.000000       8.000000     303.741867     406.767403     109.895704
max        49.541595      31.150095      21.669933     102.779655      63.600735      16.000000       8.000000    1154.705200    1240.042236     391.170868

==================== Melbourne: NorESM2-MM, ssp126, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.7)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.341386      10.775394       6.828103     100.314827       5.216906      11.070873       5.530114     174.771301     184.578995      64.622292
std         5.941798       3.789258       1.981702       0.765910       2.970525       4.549204       2.366922     264.167816     245.787643      91.111626
min        -0.702973      -1.149123       1.143336      96.700653       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.193715       8.078682       5.417987      99.827650       3.096362       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.373537      10.401580       6.463453     100.332848       4.807735      12.000000       6.000000       5.000000       0.000000       3.729281
75%        17.370737      13.267813       7.810354     100.840769       7.018087      16.000000       8.000000     283.798363     355.016869     113.454596
max        46.190670      28.893206      21.113146     102.832909      66.669327      16.000000       8.000000    1164.892822    1151.770996     436.891113

==================== Melbourne: NorESM2-MM, ssp126, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=62)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.456693      10.804914       6.802025     100.339622       5.166265      11.070873       5.530114     176.800369     188.365952      63.718540
std         6.067743       3.752761       1.933027       0.756109       2.929114       4.549204       2.366922     267.481293     252.134201      89.285355
min        -0.582734      -0.798177       1.107561      96.578819       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.252072       8.133388       5.440352      99.859947       3.130417       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.430303      10.434591       6.438679     100.375504       4.767453      12.000000       6.000000       5.000000       0.000000       3.712096
75%        17.486921      13.255364       7.770691     100.854065       6.887295      16.000000       8.000000     285.974976     359.841675     112.997406
max        46.780834      28.933035      19.434690     103.019516      62.043240      16.000000       8.000000    1163.882202    1095.593384     424.953369

==================== Melbourne: NorESM2-MM, ssp126, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.3)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.376375      10.808512       6.839595     100.352852       5.223528      11.070873       5.530114     175.541580     186.619003      63.969254
std         5.956358       3.766104       1.963585       0.770118       2.960127       4.549204       2.366922     265.506531     248.840454      90.024910
min        -0.741317      -1.094702       1.125728      96.596329       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.253171       8.131505       5.436037      99.869637       3.131403       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.429887      10.483313       6.487458     100.376060       4.817501      12.000000       6.000000       5.000000       0.000000       3.706555
75%        17.380329      13.280904       7.850837     100.874527       7.018879      16.000000       8.000000     284.679085     358.851822     112.627651
max        45.872555      28.938297      20.074171     103.042595      66.300690      16.000000       8.000000    1163.136230    1132.498169     419.073212

==================== Melbourne: NorESM2-MM, ssp370, 2021-2040 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=65)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       14.198185      10.715555       6.838752     100.287811       5.216755      11.070873       5.530114     172.220428     177.995499      65.678856
std         5.986358       3.831620       2.005785       0.771798       2.966753       4.549204       2.366922     261.103271     238.787811      93.058708
min        -0.842186      -1.145031       1.181095      96.790092       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.036271       7.989903       5.425230      99.784302       3.079856       8.000000       3.000000       0.000000       0.000000       0.000000
50%        13.192846      10.290709       6.435675     100.306061       4.817064      12.000000       6.000000       5.000000       0.000000       3.719295
75%        17.241839      13.202083       7.818274     100.836754       7.037048      16.000000       8.000000     278.039581     339.364311     114.288290
max        45.556755      28.713484      20.913597     102.712769      65.046051      16.000000       8.000000    1162.302124    1134.821411     450.375000

==================== Melbourne: NorESM2-MM, ssp370, 2041-2060 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=66.1)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.041800      11.347757       7.101709     100.347649       5.161282      11.070873       5.530114     176.746445     189.716003      63.148029
std         6.099096       3.860930       2.077054       0.763508       2.940399       4.549204       2.366922     266.916473     252.595154      88.273338
min        -0.059903      -0.608210       1.177436      96.837265       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        10.759281       8.572299       5.628664      99.851866       3.078647       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.091337      11.005273       6.708224     100.372940       4.748676      12.000000       6.000000       5.000000       0.000000       3.712749
75%        18.238458      13.955603       8.165133     100.886909       6.880485      16.000000       8.000000     287.023048     366.506088     112.324398
max        47.338150      29.951212      21.770842     102.732330      66.084068      16.000000       8.000000    1159.131348    1158.988525     396.887817

==================== Melbourne: NorESM2-MM, ssp370, 2061-2080 ====================
⚠️ Flagged
Reasons: wind_speed out of range [0.0, 60.0] (max=69.6)

                 tas           twbt           huss            psl     wind_speed       wind_dir            clt           rsds        rsdsdir        rsdsdif
count  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000  175200.000000
mean       15.647951      11.916795       7.420563     100.396996       5.150136      11.070873       5.530114     178.249481     193.739380      62.320957
std         6.250585       3.931626       2.201454       0.766026       2.931838       4.549204       2.366922     268.421844     256.832977      86.473854
min         0.349574      -0.158930       1.150941      96.785912       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        11.286812       9.076270       5.837569      99.897160       3.045976       8.000000       3.000000       0.000000       0.000000       0.000000
50%        14.642450      11.563823       6.997269     100.420929       4.751136      12.000000       6.000000       5.000000       0.000000       3.703393
75%        18.821293      14.570474       8.567862     100.928757       6.880580      16.000000       8.000000     291.056564     377.208351     111.947289
max        47.247547      29.888203      21.429182     102.843071      69.648834      16.000000       8.000000    1154.170898    1132.278076     395.328644

                                                 file        loc          model     ssp time_period  flagged                                     flag_reason   n_min  any_nan  any_const
1   Melbourne_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BO...  Melbourne     ACCESS-CM2  ssp126   2041-2060     True  wind_speed out of range [0.0, 60.0] (max=60.7)  175200    False      False
4   Melbourne_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BO...  Melbourne     ACCESS-CM2  ssp370   2041-2060     True  wind_speed out of range [0.0, 60.0] (max=62.4)  175200    False      False
5   Melbourne_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BO...  Melbourne     ACCESS-CM2  ssp370   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=67.2)  175200    False      False
6   Melbourne_AUS-15_ACCESS-ESM1-5_ssp126_r6i1p1f1...  Melbourne  ACCESS-ESM1-5  ssp126   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=63.1)  175200    False      False
7   Melbourne_AUS-15_ACCESS-ESM1-5_ssp126_r6i1p1f1...  Melbourne  ACCESS-ESM1-5  ssp126   2041-2060     True    wind_speed out of range [0.0, 60.0] (max=66)  175200    False      False
8   Melbourne_AUS-15_ACCESS-ESM1-5_ssp126_r6i1p1f1...  Melbourne  ACCESS-ESM1-5  ssp126   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=69.2)  175200    False      False
9   Melbourne_AUS-15_ACCESS-ESM1-5_ssp370_r6i1p1f1...  Melbourne  ACCESS-ESM1-5  ssp370   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=65.3)  175200    False      False
10  Melbourne_AUS-15_ACCESS-ESM1-5_ssp370_r6i1p1f1...  Melbourne  ACCESS-ESM1-5  ssp370   2041-2060     True  wind_speed out of range [0.0, 60.0] (max=63.7)  175200    False      False
11  Melbourne_AUS-15_ACCESS-ESM1-5_ssp370_r6i1p1f1...  Melbourne  ACCESS-ESM1-5  ssp370   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=66.4)  175200    False      False
12  Melbourne_AUS-15_CESM2_ssp126_r11i1p1f1_BOM_BA...  Melbourne          CESM2  ssp126   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=63.3)  175200    False      False
13  Melbourne_AUS-15_CESM2_ssp126_r11i1p1f1_BOM_BA...  Melbourne          CESM2  ssp126   2041-2060     True    wind_speed out of range [0.0, 60.0] (max=67)  175200    False      False
14  Melbourne_AUS-15_CESM2_ssp126_r11i1p1f1_BOM_BA...  Melbourne          CESM2  ssp126   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=68.1)  175200    False      False
15  Melbourne_AUS-15_CESM2_ssp370_r11i1p1f1_BOM_BA...  Melbourne          CESM2  ssp370   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=67.8)  175200    False      False
16  Melbourne_AUS-15_CESM2_ssp370_r11i1p1f1_BOM_BA...  Melbourne          CESM2  ssp370   2041-2060     True  wind_speed out of range [0.0, 60.0] (max=66.8)  175200    False      False
17  Melbourne_AUS-15_CESM2_ssp370_r11i1p1f1_BOM_BA...  Melbourne          CESM2  ssp370   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=71.8)  175200    False      False
26  Melbourne_AUS-15_EC-Earth3_ssp126_r1i1p1f1_BOM...  Melbourne      EC-Earth3  ssp126   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=64.1)  175200    False      False
27  Melbourne_AUS-15_EC-Earth3_ssp370_r1i1p1f1_BOM...  Melbourne      EC-Earth3  ssp370   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=62.1)  175200    False      False
30  Melbourne_AUS-15_MPI-ESM1-2-HR_ssp126_r1i1p1f1...  Melbourne  MPI-ESM1-2-HR  ssp126   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=63.1)  175200    False      False
31  Melbourne_AUS-15_MPI-ESM1-2-HR_ssp126_r1i1p1f1...  Melbourne  MPI-ESM1-2-HR  ssp126   2041-2060     True  wind_speed out of range [0.0, 60.0] (max=64.1)  175200    False      False
32  Melbourne_AUS-15_MPI-ESM1-2-HR_ssp126_r1i1p1f1...  Melbourne  MPI-ESM1-2-HR  ssp126   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=65.1)  175200    False      False
33  Melbourne_AUS-15_MPI-ESM1-2-HR_ssp370_r1i1p1f1...  Melbourne  MPI-ESM1-2-HR  ssp370   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=63.2)  175200    False      False
35  Melbourne_AUS-15_MPI-ESM1-2-HR_ssp370_r1i1p1f1...  Melbourne  MPI-ESM1-2-HR  ssp370   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=63.6)  175200    False      False
36  Melbourne_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BO...  Melbourne     NorESM2-MM  ssp126   2021-2040     True  wind_speed out of range [0.0, 60.0] (max=66.7)  175200    False      False
37  Melbourne_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BO...  Melbourne     NorESM2-MM  ssp126   2041-2060     True    wind_speed out of range [0.0, 60.0] (max=62)  175200    False      False
38  Melbourne_AUS-15_NorESM2-MM_ssp126_r1i1p1f1_BO...  Melbourne     NorESM2-MM  ssp126   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=66.3)  175200    False      False
39  Melbourne_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BO...  Melbourne     NorESM2-MM  ssp370   2021-2040     True    wind_speed out of range [0.0, 60.0] (max=65)  175200    False      False
40  Melbourne_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BO...  Melbourne     NorESM2-MM  ssp370   2041-2060     True  wind_speed out of range [0.0, 60.0] (max=66.1)  175200    False      False
41  Melbourne_AUS-15_NorESM2-MM_ssp370_r1i1p1f1_BO...  Melbourne     NorESM2-MM  ssp370   2061-2080     True  wind_speed out of range [0.0, 60.0] (max=69.6)  175200    False      False
0   Melbourne_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BO...  Melbourne     ACCESS-CM2  ssp126   2021-2040    False                                                  175200    False      False
2   Melbourne_AUS-15_ACCESS-CM2_ssp126_r4i1p1f1_BO...  Melbourne     ACCESS-CM2  ssp126   2061-2080    False                                                  175200    False      False
3   Melbourne_AUS-15_ACCESS-CM2_ssp370_r4i1p1f1_BO...  Melbourne     ACCESS-CM2  ssp370   2021-2040    False                                                  175200    False      False
18  Melbourne_AUS-15_CMCC-ESM2_ssp126_r1i1p1f1_BOM...  Melbourne      CMCC-ESM2  ssp126   2021-2040    False                                                  175200    False      False
19  Melbourne_AUS-15_CMCC-ESM2_ssp126_r1i1p1f1_BOM...  Melbourne      CMCC-ESM2  ssp126   2041-2060    False                                                  175200    False      False
20  Melbourne_AUS-15_CMCC-ESM2_ssp126_r1i1p1f1_BOM...  Melbourne      CMCC-ESM2  ssp126   2061-2080    False                                                  175200    False      False
21  Melbourne_AUS-15_CMCC-ESM2_ssp370_r1i1p1f1_BOM...  Melbourne      CMCC-ESM2  ssp370   2021-2040    False                                                  175200    False      False
22  Melbourne_AUS-15_CMCC-ESM2_ssp370_r1i1p1f1_BOM...  Melbourne      CMCC-ESM2  ssp370   2041-2060    False                                                  175200    False      False
23  Melbourne_AUS-15_CMCC-ESM2_ssp370_r1i1p1f1_BOM...  Melbourne      CMCC-ESM2  ssp370   2061-2080    False                                                  175200    False      False
24  Melbourne_AUS-15_EC-Earth3_ssp126_r1i1p1f1_BOM...  Melbourne      EC-Earth3  ssp126   2021-2040    False                                                  175200    False      False
25  Melbourne_AUS-15_EC-Earth3_ssp126_r1i1p1f1_BOM...  Melbourne      EC-Earth3  ssp126   2041-2060    False                                                  175200    False      False
28  Melbourne_AUS-15_EC-Earth3_ssp370_r1i1p1f1_BOM...  Melbourne      EC-Earth3  ssp370   2041-2060    False                                                  175200    False      False
29  Melbourne_AUS-15_EC-Earth3_ssp370_r1i1p1f1_BOM...  Melbourne      EC-Earth3  ssp370   2061-2080    False                                                  175200    False      False
34  Melbourne_AUS-15_MPI-ESM1-2-HR_ssp370_r1i1p1f1...  Melbourne  MPI-ESM1-2-HR  ssp370   2041-2060    False                                                  175200    False      False

In [39]:
qc_rows

[]